- README.md
Signed-off-by: Ross Turk ross@rossturk.com
Added a warning banner to the top of the README, right under the features list. At the bottom, there is now a feature wish list.
> Add beta warning and todos

- cmd/root.go
Signed-off-by: Alfredo Deza <adeza@anchore.com>
> cmd: allow no args passed, don't error

- RELEASE.md
> Add release process docs

- syft/presenter/cyclonedx/presenter.go
Thank you very much for the Syft developers and Anchore for this awesome project! I would love to see the next beta release so as to be able to use CycloneDX format...
Signed-off-by: praveenmylavarapu <saipraveenmylavarapu@gmail.com>
> remove accessing tag when not available

- cmd/completion.go
- cmd/root.go
- go.mod
- go.sum
- resources/shell-completion.sh
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> port over shell completion w/ cobra from grype, find/replace, etc.

- schema/json/schema.json
- syft/pkg/apk_metadata.go
- syft/pkg/java_metadata.go
- syft/pkg/package.go
- syft/pkg/rpm_metadata.go
- syft/presenter/json/artifact.go
- syft/presenter/json/image.go
- syft/presenter/json/location.go
- syft/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
- syft/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
@wagoodman @luhring I went through and did a find/replace:
```
json:(.+?)\-(.)(.*?)\`
```
but I'm not sure if this is sufficient. If any of these structs is stored in persistent storage (i.e. the SQLLite db) we may need to update there too.
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Change kebab case to camelCase in json keys throughout app

- .github/workflows/release.yaml
- Makefile
Additionally adds a make target for locally showing what is currently unreleased.
Closes #182
> Add notifications around the release process

- syft/scope/scope.go
- syft/scope/scope_test.go
Stereoscope has the logic to expand tilde into a path (typically reserved for shells, except for when a scheme is prefixed to the user input). This PR adds the same functionality for Syft.
> Support home dir expansion

- go.mod
- syft/cataloger/golang/parse_go_mod.go
The modfile package is in the stdlib, this PR pivots to using it.
> Replace modfile with stdlib

- syft/cataloger/java/test-fixtures/java-builds/example-jenkins-plugin/src/main/resources/index.jelly
- syft/pkg/catalog.go
- syft/presenter/text/presenter_test.go
- test/inline-compare/compare-all.sh
For https://github.com/anchore/project-toolbox/issues/15
> Remove and update TODOs

- .goreleaser.yaml
🔥 🔥 🔥  **WAIT UNTIL v0.1.0 BEFORE MERGING!**
Closes #141 
> Set prerelease to auto

- README.md
The CycloneDX presenter has already been implemented :)
> Remove CycloneDX from future plans

- syft/distro/distro.go
- syft/distro/distro_test.go
- syft/distro/identify.go
- syft/presenter/cyclonedx/presenter_test.go
- syft/presenter/json/document.go
- syft/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
- syft/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
- test/integration/distro_test.go
- test/integration/json_schema_test.go
Closes https://github.com/anchore/syft/issues/256
> Report the ID_LIKE value in the JSON presenter 

- syft/cataloger/python/parse_wheel_egg_metadata.go
- Clarifies comment on why an empty line in a `METADATA` or `PKG_INFO` file means that we cease parsing, with a reference to the spec
- Factors out field continuation logic into new function (I wasn't originally intending to do this, but the above comment clarification pushed the function's length past the linter's threshold, and it seemed like a good time to do some small cleanup.)
(This was investigated originally due to https://github.com/anchore/syft/issues/280.)
> Clarify comment on parsing new lines and factor out function

- syft/cataloger/python/package_cataloger.go
- syft/cataloger/python/package_cataloger_test.go
- syft/cataloger/python/test-fixtures/test.egg-info
> Adds globs for .egg-info file for python detection as well as tests

- Makefile
Signed-off-by: Alex Goodman <alex.goodman@anchore.com>
> add manual cache buster to the pipeline

- Makefile
- go.mod
- go.sum
- syft/cataloger/deb/cataloger_test.go
- syft/cataloger/python/package_cataloger_test.go
- syft/presenter/cyclonedx/presenter_test.go
- syft/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxDirsPresenter.golden
- syft/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxImgsPresenter.golden
- syft/presenter/json/presenter_test.go
- syft/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
- syft/presenter/table/presenter_test.go
- syft/presenter/text/presenter_test.go
- syft/source/all_layers_resolver.go
- syft/source/all_layers_resolver_test.go
- syft/source/directory_resolver.go
- syft/source/directory_resolver_test.go
- syft/source/image_squash_resolver.go
- syft/source/image_squash_resolver_test.go
- syft/source/location.go
- syft/source/test-fixtures/image-symlinks/Dockerfile
- syft/source/test-fixtures/image-symlinks/new-file-4.txt
- syft/source/test-fixtures/image-symlinks/parent/file-4.txt
- test/integration/distro_test.go
- test/integration/document_import_test.go
- test/integration/json_schema_test.go
- test/integration/pkg_coverage_test.go
Pulls in link resolution fix from https://github.com/anchore/stereoscope/pull/54
> Fix symlink resolutions for constituent paths

- go.mod
- go.sum
Brings in fix to https://github.com/anchore/stereoscope/issues/56
> Bring in fix from stereoscope for zero-layers panic

- internal/ui/etui/ephemeral_tui.go
This PR fixes the problem where "Ctrl+C-ing" out of Syft would leave your terminal in a state where the cursor was hidden.
It adds a mechanism to the UI's `for`/`select` loop to listen for particular signals of interest and respond by breaking the loop. This allows the execution of the deferred statement that re-enables the user's cursor.
Currently, there are two signals being subscribed to, but this list is easily amended if anyone has suggestions.
- SIGINT (e.g. hitting Ctrl+C after running a syft command)
- SIGTERM (e.g. terminating a running syft process via `kill -TERM <syft-command>`)
> Add handling of interrupting signals to the UI

- syft/cataloger/python/parse_wheel_egg_metadata.go
- syft/cataloger/python/parse_wheel_egg_metadata_test.go
- syft/cataloger/python/test-fixtures/egg-info/PKG-INFO-INVALID
Log the warning, this shouldn't be a hard error. Add a test to validate new behavior.
Fixes #327
> Be lenient on invalid fields in PKG-INFO

- .github/workflows/acceptance-test.yaml
- Makefile
This will be fixed by https://github.com/anchore/syft/pull/339 , however, this will fix the acceptance test failures in the meantime.
> Run snapshot build on ubuntu

- .github/workflows/release.yaml
- RELEASE.md
Adds a manual approval step from the toolbox team when the release pipeline runs.
> Enable manual release approval

- go.mod
- go.sum
Pulls in fix from https://github.com/anchore/stereoscope/pull/66
> Add manifest + repo digests on registry source

- internal/file/zip_file_traversal.go
- internal/file/zip_file_traversal_test.go
We should not trust values derived from tar headers when crafting file paths; this adjusts the zip processing to consider this and error out when this case is found.
> Safely join paths derived from archive headers

- syft/pkg/cataloger/java/archive_parser.go
- syft/pkg/cataloger/java/archive_parser_test.go
Today the java packages processed are not in a guaranteed order. Additionally, java packages alter parent package metadata based on information discovered in other child package processing paths (specifically in pom properties processing). This can be problematic given the first note (order not guaranteed) and if you find a jar with multiple pom properties.
This PR refactors the pom processing path to only alter the parent if there is missing information, otherwise no change to the parent is made.
> Refactor pom properties handling relative to parent package

- syft/pkg/cataloger/cpe.go
- syft/pkg/cataloger/cpe_test.go
- syft/pkg/cataloger/java/archive_parser.go
- syft/pkg/cataloger/java/archive_parser_test.go
- syft/pkg/cataloger/java/test-fixtures/java-builds/build-example-java-app-gradle.sh
- syft/pkg/java_metadata.go
- syft/pkg/java_metadata_test.go
> Don't use pom groupId for Jenkins and Jira plugins

- syft/distro/identify_test.go
- syft/distro/type.go
- syft/pkg/kb_package_metadata.go
- syft/pkg/metadata.go
- syft/pkg/type.go
- test/integration/catalog_packages_test.go
> Support msrc types

- README.md
Signed-off-by: Alfredo Deza <adeza@anchore.com>
> update readme to point to grype

- syft/pkg/cataloger/javascript/parse_yarn_lock.go
- syft/pkg/cataloger/javascript/parse_yarn_lock_test.go
- syft/pkg/cataloger/javascript/test-fixtures/yarn/yarn.lock
> Fix yarn.lock parsing

- syft/pkg/cataloger/javascript/parse_yarn_lock.go
Addressing this comment: https://github.com/anchore/syft/pull/437#discussion_r651810859
Let me know how this looks!
> Add comments with examples for yarn.lock regexps

- README.md
> Add callout for OSS meetup

- README.md
- cmd/packages.go
Adds docs for SPDX SBOM support in the README and CLI doc.
> Update documentation to show SPDX support

- README.md
> Revert "Add callout for OSS meetup"

- .github/scripts/go-mod-tidy-check.sh
- Makefile
> Fix go module tidy checks for release pipeline

- README.md
> Revert "Add announcement for upcoming OSS meetup"

- syft/distro/identify.go
- syft/distro/identify_test.go
- syft/distro/test-fixtures/bad-redhat-release
- syft/distro/test-fixtures/bad-system-release-cpe
- syft/distro/test-fixtures/os/centos5/etc/redhat-release
- syft/distro/test-fixtures/os/centos6/etc/system-release-cpe
Fixes #429
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>
> Add support for older CentOS versions (6 & 5) by checking additional release files for information

- RELEASE.md
Update release documentation with commands run during process.
> Add command examples to release documentation

- .github/ISSUE_TEMPLATE/config.yml
> Update description for Slack link

- internal/config/application.go
Updates the syft application config parsing to be consistent with comments from https://github.com/anchore/grype/pull/406
> Split application configuration parsing to multiple methods

- README.md
> update readme with private registry section

- README.md
- cmd/packages.go
Follow up from https://github.com/anchore/syft/pull/608
> Document file scheme

- internal/formats/common/spdxhelpers/source_info.go
- internal/formats/common/spdxhelpers/source_info_test.go
- syft/pkg/cataloger/cataloger.go
- syft/pkg/cataloger/php/index_cataloger.go
- syft/pkg/cataloger/php/parse_composer_lock.go
- syft/pkg/cataloger/php/parse_composer_lock_test.go
- syft/pkg/cataloger/php/test-fixtures/composer.lock
- syft/pkg/language.go
- syft/pkg/type.go
- test/integration/catalog_packages_cases_test.go
- test/integration/catalog_packages_test.go
- test/integration/test-fixtures/image-pkg-coverage/composer/composer.lock
Signed-off-by: Nikita <33390074+Zilborg@users.noreply.github.com>
Hello, guys. 
Added parser for `composer.lock`.
Documentation: https://getcomposer.org/doc/04-schema.md
> PHP parser composer.lock

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Announce meetup on 2021-12-01

- syft/source/directory_resolver.go
- syft/source/directory_resolver_test.go
When a single file archive is provided syft had been returning paths relative to the temporary directory created for the archive instead of relative to the root of the archive itself:
```
❯ SYFT_FILE_METADATA_CATALOGER_ENABLED=true syft file:/tmp/syft.tar -o json | jq '.files'
...
{
"id": "ee5a4e3ef9a56d72",
"location": {
"path": "/var/folders/8x/gw98pp6535s4r8drc374tb1r0000gn/T/syft-archive-contents-770869922/syft/source/source.go"
},
"metadata": {
"mode": 644,
"type": "RegularFile",
"userID": 501,
"groupID": 20,
"mimeType": "text/plain"
},
"digests": [
{
"algorithm": "sha256",
"value": "f101eac52429e3fc2da43ffbb80bdacba6b8b80b9703470b2ff9d7218e9bc9ad"
}
]
},
...
```
Note the path is `/var/folders/8x/gw98pp6535s4r8drc374tb1r0000gn/T/syft-archive-contents-770869922/syft/source/source.go` …
> Fix directory resolver path resolution

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Remove webinar announcement

- README.md
Signed-off-by: Dan Luhring <dan+github@luhrings.com>
> Add section for community meetings

- cmd/check_for_application_update.go
- cmd/cmd.go
- cmd/packages.go
- cmd/power_user.go
Closes https://github.com/anchore/syft/issues/664
> add version to logs

- install.sh
> update cp statement in install script for coreutils compatibility

- syft/pkg/apk_metadata_test.go
- syft/pkg/catalog.go
- syft/pkg/cataloger/java/archive_filename.go
- syft/pkg/cataloger/java/archive_filename_test.go
- syft/pkg/cataloger/java/archive_parser.go
- syft/pkg/cataloger/java/archive_parser_test.go
- syft/pkg/dpkg_metadata_test.go
- syft/pkg/python_package_metadata_test.go
- syft/pkg/rpmdb_metadata_test.go
also cleaned up linter warning
Closes: #682
> Add lpkg as java package format

- README.md
- syft/pkg/cataloger/java/archive_filename.go
- syft/pkg/cataloger/java/archive_filename_test.go
- syft/pkg/cataloger/java/archive_parser.go
- syft/pkg/cataloger/java/cataloger.go
closes #728 
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>
> support .sar for java ecosystem

- .goreleaser.yaml
- remove replacements so install script is correct
- update checksum sign so windows zip is included
> update sign sed command to include windows zip

- Dockerfile
> convert from deprecated org.label-schema to OCI Annotations

- Makefile
Signed-off-by: Vijay Pillai <vijay.pillai@anchore.com>
> update go-bouncer to version 0.3.0 for ARM support

- go.mod
- go.sum
- syft/file/metadata_cataloger_test.go
- syft/source/image_squash_resolver_test.go
- syft/source/scheme_test.go
Change units tests to accommodate update  
> update stereoscope version - include Podman support

- .github/scripts/apple-signing/notarize.sh
To prevent https://github.com/anchore/syft/runs/5100741150?check_suite_focus=true
> Create flat notarization zip

- README.md
add metadata filed on pod usage template to make sure the yaml file can be applied succ.
> add metadata filed on pod usage template

- .goreleaser.yaml
> remove duplicate manifest lines

- syft/pkg/cpe.go
- syft/pkg/cpe_test.go
This PR adjusts the CPE parsing to be more permissive of input that can/will be sanitized in future `pkg.CPEString()` calls. Today if an input CPE string doesn't match the CPE spec suggested validation regex we error out. This PR changes the behavior to only check this against a parsable and sanitized CPE string, and not the raw input string.
Why make this change? Upstream data with CPEs are known to have non-compliant formatted CPE strings, in which case we should have a best-effort attempt to parse and use the data instead of ignoring the CPE as a whole. This change makes CPE representation tolerant to some non-compliance in parsing, but still remains compliant in terms of the CPE strings generated.
> Allow for CPE strings that can later be sanitized

- Dockerfile
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #783
> Enhance container image labels for ArtifactHub

- cmd/attest.go
- cmd/packages.go
> bump error language and remove panic

- cmd/packages.go
> tiny aligment fix in example template

- go.mod
- go.sum
Bumps containerd from v1.5.9 to v1.5.10
> Update containerd via stereoscope

- cmd/version.go
- internal/version/build.go
See attachment for new output and sample command updates
Signed-off-by: Christopher Phillips <christopher.phillips@anchore.com
> Add SchemaVersion to version command output

- README.md
Update README with OSS meetup information
> Add OSS Meetup information

- internal/formats/common/cyclonedxhelpers/component.go
Will resolve: https://github.com/anchore/grype/issues/669
> Fix panic parsing CycloneDX

- internal/constants.go
- internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
- internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
- internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
- schema/json/schema-3.2.1.json
- syft/pkg/golang_bin_metadata.go
> Omit H1Digest when empty

- README.md
Proposing changes to remove our 3/23 meetup
> Remove announcement for OSS Meetup

- .github/workflows/update-stereoscope-release.yml
We need to run `go mod tidy` after `go get ...`
> Auto-PR needs to run go mod tidy

- syft/pkg/cpe.go
Signed-off-by: Rob Dimsdale-Zucker <robert.dimsdale@gmail.com>
> Fix typo in CPE-parsing error

- go.mod
- go.sum
> golang.org/x/crypto upgrade

- syft/pkg/cataloger/golang/parse_go_bin.go
- syft/pkg/cataloger/golang/parse_go_bin_test.go
closes https://github.com/anchore/syft/issues/959
Signed-off-by: Jonas Galvão Xavier <jonasx@anchore.com>
> read Go main module version as is - (devel)

- go.mod
- go.sum
Fix https://github.com/anchore/syft/issues/927
Signed-off-by: Jonas Xavier <jonasx@anchore.com>
> bump stereoscope version to include source path fix

- README.md
We would like to leave the announcement up until after the meetup on 6/15.
> Add announcement for Anchore OSS Virtual Meetup

- README.md
> remove OSS Meetup message

- README.md
- internal/formats/common/spdxhelpers/source_info.go
- internal/formats/common/spdxhelpers/source_info_test.go
- internal/formats/syftjson/model/package.go
- syft/pkg/cataloger/cataloger.go
- syft/pkg/cataloger/cpp/cataloger.go
- syft/pkg/cataloger/cpp/parse_conanfile.go
- syft/pkg/cataloger/cpp/parse_conanfile_test.go
- syft/pkg/cataloger/cpp/test-fixtures/conanfile.txt
- syft/pkg/conan_metadata.go
- syft/pkg/language.go
- syft/pkg/language_test.go
- syft/pkg/metadata.go
- syft/pkg/type.go
- syft/pkg/type_test.go
- syft/pkg/url_test.go
- test/integration/catalog_packages_cases_test.go
- test/integration/catalog_packages_test.go
- test/integration/test-fixtures/image-pkg-coverage/conan/conanfile.txt
Adds support for indexing Conan `conanfile.txt` files
Closes https://github.com/anchore/syft/issues/1082
> feat: add support for conan packages (C/C++)

- syft/pkg/relationships_by_file_ownership.go
In the initial review, @wagoodman wanted to add a comment to clarify this addition. 
The PR was merged before that feedback could be addressed.
This PR updates the new code with the suggested changes.
> update AltRpmDbGlob with comment and context

- .github/workflows/pr_action.yaml
> Add PR action back to workflow with new token

- syft/pkg/url.go
- syft/pkg/url_test.go
> Fix package url for Go modules with no /

- Makefile
> bump cosign in bootstrap-tools to v1.10.0

- Makefile
> bump golangci-lint to v1.47.2

- .goreleaser.yaml
Signed-off-by: mayurwaghmode <waghmodemayur17@gmail.com>
This PR will add ppc64le supported to the syft:debug image
> Added ppc64le supported to the syft:debug image

- Makefile
> bump bouncer to v0.4.0

- .github/workflows/release.yaml
Source: https://github.com/docker-practice/actions-setup-docker/issues/18
The linked issue for future improvement:
#1126 
> rollback actions-setup-docker to earlier version

- .github/scripts/apple-signing/setup-prod.sh
> remove ENV checks from siging script

- .github/scripts/apple-signing/setup-prod.sh
> remove docker login from keychain

- .bouncer.yaml
- Makefile
- go.mod
- go.sum
> remove incorrect bouncer license allow

- go.mod
> retraction for mispublished versions

- .github/workflows/update-bootstrap-tools.yml
Set all of the output variables correctly
> Fix update-bootstrap-tools workflow

- go.mod
- go.sum
> update stereoscope to latest

- README.md
- cmd/syft/cli/packages.go
(Draft until #1189 addressed, likely via https://github.com/anchore/stereoscope/pull/142)
Add Singularity example to "supported sources" in README, and to image sources in online help.
> docs: improve Singularity image source docs

- syft/formats/spdx22json/encoder_test.go
- syft/formats/spdx22json/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
- syft/formats/spdx22json/to_format_model.go
- syft/formats/syftjson/to_format_model.go
- syft/sbom/sbom.go
This PR sorts relationships so SPDX JSON format should be stabilized.
Fixes #1213
> Stabilize spdx-json output

- DEVELOPING.md
- Add missing dependency Golang
- Reorder basic make commands above output
- Add sequence diagrams and directory layouts for cmd/ syft/ packages
- Add small summaries surrounding library design
> add sequence diagrams and flesh out TODO notes

- syft/formats/syftjson/format.go
- syft/formats/syftjson/to_format_model_test.go
> fix: update syftjson ID to match major schema version

- .github/ISSUE_TEMPLATE/bug_report.md
> fix: move reproduction to top of issue

- Makefile
> fix: unterminated quoted string

- .github/workflows/release.yaml
> fix: update workflow to use new cert chain

- .github/workflows/release.yaml
> fix: update ci secret to use new password

- internal/ui/ephemeral_terminal_ui.go
- internal/ui/etui_event_handlers.go
- internal/ui/select.go
- syft/source/file_details.go
Signed-off-by: Thomas Klausner <wiz@gatalith.at>
> Add NetBSD support.

- README.md
I have [created a PR to include the formula](https://github.com/Homebrew/homebrew-core/pull/118929) into the homebrew-core, the installation experience would be better (I think). Thanks!
> docs: migrate to homebrew-core

- artifacthub-repo.yml
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
cc: @wagoodman
> chore: claim artifacthub package ownership from developer-guy

- README.md
22.05 has been released, update the instructions.
> README: update Nix installation instructions

- .github/workflows/release.yaml
> chore: use checkout v2 for tag depth

- .github/workflows/release.yaml
> chore: use checkout v3 with new depth

- syft/pkg/cataloger/binary/cataloger_test.go
- syft/pkg/cataloger/binary/default_classifiers.go
- syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/memcached-1.6.18/memcached
This PR adds a binary cataloger for memcached
fixes #1459
> feat: add memcahced classifier

- .github/workflows/update-bootstrap-tools.yml
This PR corrects an issue the bootstrap tool script is not updating the Makefile properly and also corrects the warnings for using `set-output`.
> Update bootstrap tool update script

- syft/pkg/cataloger/binary/default_classifiers.go
> fix: add relevant CPEs to python classifiers

- .github/ISSUE_TEMPLATE/bug_report.md
Just a small change to the bug issue template:
* update text for reproduction steps
* reorganize slightly to make the flow a little better
> chore: update bug issue template

- DEVELOPING.md
Adds a few rules about catalogers in the developing docs.
> Add high-level details about catalogers

- syft/source/image_all_layers_resolver_test.go
Update tests to not fail on Mac M1's.
Closes #1673
> Update tests to not fail on Mac M1's.

- internal/constants.go
- schema/json/schema-8.0.1.json
- syft/pkg/cataloger/java/parse_pom_xml.go
- syft/pkg/cataloger/java/parse_pom_xml_test.go
- syft/pkg/java_metadata.go
This lays the foundation for https://github.com/anchore/grype/issues/985
> feat: add scope to pom properties

- syft/formats/common/spdxhelpers/to_syft_model.go
- syft/formats/common/spdxhelpers/to_syft_model_test.go
This PR improves the PURL validity testing / decoding while decoding SPDX documents.
> chore: improve spdx purl decoding

- .gitignore
- go.mod
Only rearranging, no additions/removals made
> Tidy the go.mod and .gitignore

- .github/workflows/release-homebrew.yaml
- .github/workflows/release.yaml
Fixes: https://github.com/anchore/syft/issues/1984
> chore: add automated homebrew action

- syft/source/file_source.go
> fix: use filepath instead of path for file source exclusions

- README.md
- cmd/syft/cli/commands/scan.go
- cmd/syft/cli/commands/scan_test.go
Fixes problems 1 & 2 as described in #2511
Additionally updates existing output to be consistent in the README.md configuration section.
> Update readme and help output to be accurate to the Syft API

- syft/pkg/cataloger/binary/cataloger.go
Follow up to #2633 based on further feedback
> Rename binary classifier cataloger name

- syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
- syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
- syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
- syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
- syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
- syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
- syft/pkg/cataloger/internal/cpegenerate/generate.go
Indexes known CPEs from `packagist.org`
> feat: index known CPEs for PHP Composer packagist.org packages

- SECURITY.md
Adds a security policy to the repo for folks to be able to report security issues appropriately.
> Publish security policy

- internal/cache/filesystem.go
- internal/cache/filesystem_test.go
- syft/pkg/cataloger/golang/licenses.go
- syft/pkg/cataloger/golang/licenses_test.go
> fix: handle errors reading go licenses

- README.md
Fix a small typo in the README
> chore: Fix apache shield in readme

- .github/scripts/trigger-release.sh
This PR just updates the release script to use the `gh` tool from binny instead of an arbitrary one on the command line and also automatically set the GITHUB_TOKEN to the currently authenticated user, if it is not provided.
This makes `make release` work without additional external setup.
Note: this version of the script was used to release: https://github.com/anchore/syft/releases/tag/v1.10.0
> chore: update release script to use gh from binny

- syft/pkg/cataloger/java/archive_filename.go
- syft/pkg/cataloger/java/archive_filename_test.go
- syft/pkg/cataloger/java/archive_parser.go
- syft/pkg/cataloger/java/cataloger_test.go
- syft/pkg/cataloger/java/test-fixtures/glob-paths/java-archives/example.kar
support .kar files
closes - https://github.com/anchore/syft/issues/2977
> support .kar files

- README.md
This clarifies the license under which the Syft "owl" logo is released. This is necessary to enable us to share the logo in certain online communities.
> doc: Add official Syft logo license information

- go.mod
- go.sum
- **Stereoscope**: `v0.0.10-0.20241209145719-40026b235333` ➔ `v0.0.10`
> chore(deps): update anchore dependencies

- .github/workflows/benchmark-testing.yaml
- .github/workflows/release-version-file.yaml
- .github/workflows/release.yaml
- .github/workflows/validations.yaml
> chore: update runners to ubuntu-24.04

- syft/pkg/cataloger/golang/internal/xcoff/file.go
- syft/pkg/cataloger/redhat/parse_rpm_db.go
fix some function names in comment
- Fixes
> chore: fix some function names in comment

- Dockerfile
- Dockerfile.debug
> Upgrade base docker image

- syft/format/internal/backfill.go
- syft/format/syftjson/model/package.go
- syft/internal/fileresolver/deferred.go
- syft/pkg/cataloger/dotnet/parse_packages_lock.go
- syft/pkg/cataloger/golang/licenses.go
- syft/pkg/cataloger/java/parse_pom_xml.go
- syft/pkg/cataloger/kernel/cataloger.go
- syft/pkg/cataloger/python/parse_poetry_lock.go
Fixes some logging output format issues
> chore: fix some logging output

- schema/json/vnd.syft+json
This PR updates the contact info in the mimetype schema documentation.
> chore: update mimetype contact info

- Taskfile.yaml
- cmd/syft/internal/test/integration/package_deduplication_test.go
With #3894 I missed one more change (there were a lot of logs to sift through). Running from this branch [now](https://github.com/anchore/syft/actions/runs/15051390731/job/42306802257)...
> chore: fix publishing test fixture images

- syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
This reverts commit 8cbdd38a63c45d0e0951b20c13776e86a4da6d5a.
This PR reverts the change in #3805 -- the reason for this is there is nothing identifying executables as graalvm executables, so every ELF binary or other executable file may end up adding incorrect unknown information, the only executables that should return unknown information from this cataloger are actual GraalVM executables, so we need to find a way to identify them before restoring the unknown behavior.
- Fixes #3942
> Revert Make Native Image contains no embedded SBOM Error Discoverable (#3805)
