.github/scripts/update-version-file.sh
.github/workflows/acceptance-test.yaml
.github/workflows/release.yaml
Makefile

Since we will be cutting betas for a while longer, we want to let users know when there is another beta available. However, after v0.1.0 release, we will not be creating betas that often, but when we do we do not want to let users know there is another version available if the new version is a pre-release (e.g. `v#.#.#-<prerelease>`).
This PR switches the source of truth for when to notify users from the semver on the git tag to using the github releases "prerelease" indicator.

Disable prerelease version update check

---

syft/cataloger/python/cataloger.go
syft/cataloger/python/parse_setup.go
syft/cataloger/python/parse_setup_test.go
syft/cataloger/python/test-fixtures/setup/setup.py
syft/pkg/type.go
test/integration/pkg_cases.go
test/integration/test-fixtures/image-pkg-coverage/python/setup/setup.py

It will go into `setup.py` files, but only capture dependencies that are pinned (using the `==` operator).
Closes #59

Add a `setup.py` cataloger

---

test/acceptance/compare.py
test/acceptance/deb.sh
test/acceptance/mac.sh
test/acceptance/rpm.sh
test/acceptance/test-fixtures/acceptance-centos-8.2.2004.json
test/inline-compare/compare.py

Acceptance test results are being piped to `tee` for ease of CI usage and the pipe has been swallowing non-zero return codes. This PR:
- addresses the problem of failing acceptance tests not indicating as a failure (add `-o pipefail` bash option)
- fixes the python compare script bug that was failing (`r/sources/locations/`)
- update the test fixture to the latest format
- updates the compare presentation to match the inline compare
- prevents syft from attempting to check for app updates in the pipeline
Closes #156

Fix acceptance tests

---

.gitignore
.goreleaser.yaml
Makefile

Adds a new make target `make changelog` to generate a changelog in the root of the repo. Additionally adds this changelog to the GitHub Releases page on release in the form of a draft.
Closes #159

Add changelog generation

---

syft/presenter/cyclonedx/presenter.go
syft/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxDirsPresenter.golden
syft/presenter/cyclonedx/test-fixtures/snapshot/TestCycloneDxImgsPresenter.golden

In response to https://github.com/anchore/grype/pull/143/files#r479703994 .
Additionally noticed that there was a single space prefix for the document, which is unnecessary (thus removed).

Use xml encoder for CycloneDX presenter

---

cmd/version.go
internal/version/build.go

Fixes #122 
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

Add support for JSON version output

---

syft/lib.go

Adds the high-level execution path explanation to the root of the lib.

Add docs around the main execution path

---

test/acceptance/mac.sh

Fixes acceptance test failures by unpinning skopeo:
```
./test/acceptance/mac.sh: line 33: skopeo: command not found
+ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/75e8d7a40af77b48cc91f4bdb7d669f891a6de60/Formula/skopeo.rb
Error: Calling Installation of skopeo from a GitHub commit URL is disabled! Use 'brew extract skopeo' to stable tap on GitHub instead.
```
From https://github.com/anchore/syft/runs/1127902909?check_suite_focus=true

Unpin skopeo during mac acceptance tests

---

syft/presenter/table/presenter.go
syft/presenter/table/presenter_test.go

Prevents the summary table from showing duplicate rows.

Remove duplicate rows from the summary table

---

go.mod
go.sum

Removes the cyclic dependency between stereoscope and testutils (as well as other unused dependencies)

Remove stereoscope from testutils

---

syft/scope/scope.go

Should prevent panics on malformed input to scope:
```
grype -vv -o json --fail-on medium dir://tests/python
[0000] DEBUG Application config:
configpath: ""
presenteropt: 1
output: json
scopeopt: 1
scope: Squashed
quiet: false
log:
structured: false
levelopt: debug
level: ""
filelocation: ""
clioptions:
configpath: ""
verbosity: 2
db:
dir: /Users/alfredo/Library/Caches/grype/db
updateurl: https://toolbox-data.anchore.io/grype/databases/listing.json
autoupdate: true
dev:
profilecpu: false
checkforappupdate: true
failon: medium
failonseverity: 3
[0000] DEBUG No new grype update available
[0000]  INFO cataloging image from-lib=syft
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a1b756]
goroutine 16 …
```

Always return a cleanup function from scope

---

internal/file/zip_file_manifest.go
internal/file/zip_file_traversal.go
syft/cataloger/apkdb/parse_apk_db.go
syft/cataloger/apkdb/parse_apk_db_test.go
syft/cataloger/apkdb/test-fixtures/extra-file-attributes
syft/cataloger/common/generic_cataloger.go
syft/cataloger/java/save_archive_to_tmp.go
syft/pkg/apk_metadata.go

Fixes the errors seen from this:
```
bin syft docker:tomcat:alpine 
✔ Loaded image         
✔ Parsed image         
✔ Cataloged image      [52 packages]
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: "0:0:755:Q1JaDEHQHBbizhEzoWK1YxuraNU/4="
[0003] ERROR unexpected APK ownership field: …
```

Ignore apk xattr file checksum

---

cmd/version.go

Removes the `-v` option to match grype

Modify version command to match grype

---

.github/workflows/acceptance-test.yaml
test/acceptance/deb.sh
test/acceptance/mac.sh
test/acceptance/rpm.sh

Acceptance tests do not occur within the PR checks, which means it is possible for a passing PR to fail after being merged to main (when acceptance tests run). This PR fixes the existing failures and adds notifications to the toolbox channel when a failure is seen.

Fix acceptance tests & add notification upon failures

---

README.md

Just noted this, thought it was better to remove it now that we are no longer in a pre-release stage.

docs: update the readme to remove pre-release note

---

.github/workflows/static-unit-integration.yaml

Today we are triggering the static analysis and test workflow from push events, which forks for members of the repo, but not for PRs from a fork. This PR adds the `pull_request` trigger to the static analysis and test workflow. Note: this will cause what appears to be duplicate checks for PRs originating from members of the repo, which happens on simultaneous push and PR events. This is somewhat undesirable behavior but the refs being checked are technically different --one running against the typical git `ref` while the other is running against `refs/pull/<prnum>/merge`, as seen from the `GITHUB_REF`.

Run checks on PRs from forks

---

Makefile
syft/cataloger/apkdb/parse_apk_db.go
test/integration/regression_test.go
test/integration/test-fixtures/image-large-apk-data/Dockerfile

Increases the buffer size to 1MB to accommodate large lines (ie the tzdata package, which is what was failing for me)
Signed-off-by: Jason Williams <jasonw@jhu.edu>

Fixes #212 by increasing buffer size for scanner

---

syft/pkg/gem_metadata.go

Prevent `null` and empty gemspec fields when rendering JSON.

Allow for gemspec metadata fields to be optional

---

schema/json/schema.json

It seems that there is a cache-related problem in the PR check pipeline and main branch pipeline. The checks for https://github.com/anchore/syft/pull/218 passed, however, on main they failed. This PR updates the json schema appropriately relative to the changes in #218 .

Update json schema to account for optional gemspec fields

---

syft/cataloger/catalog.go
syft/cataloger/cataloger.go
syft/cataloger/common/generic_cataloger.go
syft/cataloger/common/generic_cataloger_test.go
syft/scope/resolver.go
syft/scope/resolvers/all_layers_resolver.go
syft/scope/resolvers/directory_resolver.go
syft/scope/resolvers/image_squash_resolver.go

Upgrades the cataloger interface from:
```golang
type Cataloger interface {
SelectFiles(scope.FileResolver) []file.Reference
Catalog(map[file.Reference]string) ([]pkg.Package, error)
}
```
to:
```golang
type Cataloger interface {
Catalog(resolver scope.Resolver) ([]pkg.Package, error)
}
```
(note: excluded `Name` function in the above snippet for clarity)
In this way the catalogers can reconcile multiple file sources as needed without requiring external interaction with the caller (the `lib.go` `Catalog()` function). In this way state for a cataloger (no matter how complicated it may become) can be constrained to the stack of the `Catalog` function on the cataloger.
A notable downside with this approach is that catalog content requests to stereoscope are no longer guaranteed to be …

Upgrade cataloger interface to use full resolver

---

.github/workflows/acceptance-test.yaml

This was missed during the migration from CircleCI to GHA, specifically, the pipeline was depending only on cache to load the `.tmp` dir instead of invoking `make bootstrap` to explicitly populate it on a cache miss.

Bootstrap cached dependencies and CI dependencies separately for acceptance tests

---

go.mod
go.sum

This pulls in the work from this PR: https://github.com/bmatcuk/doublestar/pull/47 (more info found there)

Update doublestar to include fix for open dirs issue

---

test/inline-compare/.gitignore
test/inline-compare/Makefile
test/inline-compare/compare.py
test/inline-compare/utils/format.py
test/inline-compare/utils/image.py
test/inline-compare/utils/inline.py
test/inline-compare/utils/package.py
test/inline-compare/utils/syft.py

- Adds java and npm package comparison
- Adds probable matching of extra packages syft found and missing packages that syft did not find (but inline did). This way there is a section of output that fuzzy-matches the package names to get a better sense of "real" problems (actual missing packages) vs slightly mismatched metadata during troubleshooting.
- Adds a set or probable missing packages to the report based on the probable matches (again, to aid in troubleshooting)
- Fixes image reference clean function to support references with registries
- Only shows metadata differences when the package was found by both inline and syft
- Splits the inline-compare code into more manageable pieces

Add java/npm to inline comparison

---

schema/json/schema.json
syft/cataloger/java/archive_filename.go
syft/cataloger/java/archive_parser.go
syft/cataloger/java/archive_parser_test.go
syft/cataloger/java/java_manifest.go
syft/cataloger/java/java_manifest_test.go
syft/pkg/java_metadata.go

- Adds a `virtualPath` for java archives to indicate if the archive was found within another java archive (similar to Anchore engine). e.g. `hudson.war:WEB-INF/lib/args4j-2.0.16.jar`
- Removes the `parentPackage` from the json output for java archives
- Removes optional fields from json output when empty
- Parses java manifest sections separately; Fixes #220 
- Forces lowercase of pom properties `path` variable
Partially addresses findings from https://github.com/anchore/grype/issues/182 and https://github.com/anchore/grype/issues/192 as well as helps with https://github.com/anchore/anchore-engine/issues/681

Java cataloger miscellaneous fixes

---

.github/scripts/mac-prepare-for-signing.sh
.github/scripts/mac-sign-and-notarize.sh
.github/scripts/update-version-file.sh
.github/workflows/acceptance-test.yaml
.github/workflows/release.yaml
.goreleaser.yaml
Makefile
gon.hcl
test/acceptance/mac.sh

- Adds signing and notarization to the release process to replace the Darwin `.tar.gz` asset with a `.dmg`asset
- Moves several pipeline steps from a Linux runner to a macOS runner and adapts the pipeline logic accordingly
- Makes minor improvements and adds clarifying comments to various release-related files
This implements https://github.com/anchore/project-toolbox/issues/27 for _syft_. Other released executables will need similar changes.

Resolve security warning for macOS users

---

go.mod
go.sum
syft/cataloger/rpmdb/cataloger.go
syft/cataloger/rpmdb/parse_rpmdb.go
syft/cataloger/rpmdb/parse_rpmdb_test.go
syft/pkg/rpmdb_metadata.go
syft/scope/resolvers/all_layers_resolver.go
syft/scope/resolvers/all_layers_resolver_test.go
syft/scope/resolvers/directory_resolver.go
syft/scope/resolvers/directory_resolver_test.go
syft/scope/resolvers/image_squash_resolver.go
syft/scope/resolvers/image_squash_resolver_test.go
syft/scope/scope_test.go

- Adds file information to packages from from the RPMDB Cataloger. Note: though the RPM metadata has information on packaged files, not all files are expected to be installed. Only the file paths that exist in the source are reported.
- Modifies `FileResolvers` to ignore directories.
Partially addresses https://github.com/anchore/anchore-engine/issues/682
**Note: this PR depends on https://github.com/anchore/stereoscope/pull/47 and https://github.com/anchore/go-rpmdb/pull/1 to be merged and incorporated first.**

Add RPM file info sourced from the RPM DB

---

internal/config/config.go
internal/log/log.go
internal/log/nop.go
internal/logger/logrus.go
syft/cataloger/apkdb/parse_apk_db.go
syft/cataloger/common/generic_cataloger.go
syft/cataloger/java/archive_filename.go
syft/cataloger/java/archive_parser.go
syft/cataloger/java/java_manifest.go
syft/cataloger/javascript/parse_yarn_lock.go
syft/cataloger/python/package_cataloger.go
syft/cataloger/python/package_cataloger_test.go
syft/logger/logger.go

- Adds `Error` log level helper (mirrors existing pattern of other levels)
- Adds `Warn*` log level helpers
- Replaces a few `log.Errorf` uses that should be `log.Warnf`
- Fixes https://github.com/anchore/syft/issues/259

Add warning log level

---

.github/scripts/mac-sign-and-notarize.sh
.goreleaser.yaml
gon.hcl
install.sh

- Adds "zip" as a `gon` output
- Ensures that this ZIP file is a goreleaser artifact, so it's used in the brew publish step and included as a release asset
- Removes the "flash" of a Finder window during the execution of `install.sh`
This is also intended to address https://github.com/anchore/grype/issues/203... Once this solution is confirmed, similar changes will be made to Grype.

Add signed and notarized ZIP release asset

---

.goreleaser.yaml
Makefile

- augment the macOS signing step to denote creation of the DMG file
- augment the linux signing step to remove the zip checksum, which will always be incorrect
- provide goreleaser with the artifact version via an environment variable

Fix release process

---

syft/cataloger/rpmdb/cataloger.go
syft/cataloger/rpmdb/parse_rpmdb.go
syft/cataloger/rpmdb/parse_rpmdb_test.go

Today we should be attaching the file source to the packages discovered --this PR does this for the RPMDB cataloger.

Add source to packages found by RPMdb cataloger

---

cmd/cmd.go
syft/cataloger/javascript/parse_package_json.go
syft/cataloger/javascript/parse_package_json_test.go
syft/cataloger/javascript/test-fixtures/pkg-json/package-license-object.json
syft/cataloger/javascript/test-fixtures/pkg-json/package-license-objects.json
syft/cataloger/javascript/test-fixtures/pkg-json/package-no-license.json

- Closes #253 
- Adds support for [alternative/deprecated formats for the `license` property](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license) in `package.json` (e.g. a license object, an array of license objects)
- Adds support for the absence of a `license` property
- Adds tests to cover the above scenarios

Improve package.json license parsing

---

syft/cataloger/java/archive_filename.go
syft/cataloger/java/archive_filename_test.go
syft/cataloger/java/archive_parser_test.go
syft/cataloger/java/java_manifest.go

- Closes #255 
- Reworks the regex-based recognition of package name and version from a Java archive name
- Updates test cases to include #255's scenario
- Adjusts existing tests to expect (what seems like) more correct version values
- Cleans up a bit of ancillary test logic

Improve Java version recognition

---

go.mod
go.sum

This pulls in the fix to https://github.com/anchore/stereoscope/issues/48, which was causing #264.

Update stereoscope version to fix opaque directory merge issue

---

go.mod
go.sum
syft/cataloger/cpe.go
syft/cataloger/cpe_test.go
test/integration/regression_test.go

This will help solve some of the grype false negatives for java packages highlighted in https://github.com/anchore/grype/issues/209 , where we could be guessing CPEs to search with (in the grype matching process) with parsed fields from the `GroupID` POM property. 
Specifically `org.sonatype.nexus` --> `cpe:2.3:a:sonatype:nexus:*:*:*:*:*:*:*:*`.

Include CPEs with elements from POM GroupId fields

---

go.mod
go.sum

Incorporates https://github.com/anchore/stereoscope/pull/51 , which removes an unnecessary verification check (we will replace this verification with the right one).
Closes #284

Bump stereoscope to remove tree-catalog syft check

---

syft/cataloger/cpe.go
syft/cataloger/cpe_specificity.go

- Sorts generated CPEs by specificity (measured by number of CPE fields that **aren't** set to `*`)
- Makes progress toward the implementation mentioned in @wagoodman's [comment](https://github.com/anchore/syft/issues/268#issuecomment-741829842) on #268

Sort generated CPEs by specificity

---

syft/cataloger/deb/parse_copyright.go
syft/cataloger/deb/parse_copyright_test.go
syft/cataloger/deb/test-fixtures/copyright/python

Deb package processing should only be capturing single-value licenses (not full license texts). This moves this processing in the right direction, however, the underlying data may still be mis-using the field.

Update dpkg license to only include single-word entries

---

Makefile
internal/constants.go
schema/json/schema-1.0.1.json
syft/cataloger/deb/parse_dpkg_status.go
syft/cataloger/deb/parse_dpkg_status_test.go
syft/pkg/dpkg_metadata.go
syft/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
syft/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden

Ensure that the source field for dpkg entries is just a name and any embedded version in that string is extracted into a new string

Split dpk source into name and version

---

cmd/cmd.go
cmd/root.go
go.mod
go.sum
internal/anchore/import.go
internal/anchore/import_config.go
internal/anchore/import_config_test.go
internal/anchore/import_dockerfile.go
internal/anchore/import_manifest.go
internal/anchore/import_manifest_test.go
internal/config/config.go
syft/event/parsers/parsers.go
ui/event_handlers.go

Corresponding changes from https://github.com/anchore/anchore-engine/pull/790
Additionally adds a `--overwrite-existing-image` option for upload, allowing the user to force the import/upload results to override a previously existing image.
Also adds a small enhancement to the ETUI to show the host where the SBOM info was uploaded to.

Incorporate import changes + add image overwrite option

---

syft/cataloger/python/package_cataloger.go
syft/cataloger/python/package_cataloger_test.go
syft/cataloger/python/test-fixtures/Python-2.7.egg-info

Ignores if the Python runtime is found as a package. Adds one test to verify this is the case as well as a fixture
Closes #300

catalogers: Python runtime is not a Python package itself, ignore it

---

.golangci.yaml
syft/cataloger/python/package_cataloger_test.go
syft/cataloger/python/parse_wheel_egg_metadata.go
syft/cataloger/python/parse_wheel_egg_metadata_test.go
syft/source/mock_resolver.go

- Accounts for the possibility of the parsed file's parent directory being `site-packages` itself (a possibility that was introduced in https://github.com/anchore/syft/pull/296) as opposed to an `...egg-info` directory
- Adds a new resolver: `MockResolver` — this can be used when you need a `source.Resolver` but you want to explicitly only use a set of test fixture files

Handle site packages based on which egg file is parsed

---

go.mod
go.sum
syft/cataloger/common/generic_cataloger.go
syft/cataloger/common/generic_cataloger_test.go
syft/cataloger/deb/cataloger.go
syft/cataloger/python/package_cataloger.go
syft/cataloger/rpmdb/cataloger.go
syft/distro/identify.go
syft/source/all_layers_resolver.go
syft/source/all_layers_resolver_test.go
syft/source/content_requester_test.go
syft/source/directory_resolver.go
syft/source/file_data.go
syft/source/image_squash_resolver.go
syft/source/image_squash_resolver_test.go
syft/source/location.go
syft/source/mock_resolver.go
syft/source/resolver.go
syft/source/source_test.go

Pulls in changes from https://github.com/anchore/stereoscope/pull/53

Bump stereoscope to pull in content API refactors

---

syft/cataloger/ruby/catalogers.go
test/integration/pkg_cases_test.go
test/integration/test-fixtures/image-pkg-coverage/ruby/specifications/default/unbundler.gemspec

The previous glob implementation had slightly different glob pattern rules. This PR updates the gemspec glob pattern to account for nested named directories within the `specification` installation directory.

Update gemspec glob to include named nested specification directories

---

go.mod
go.sum
syft/cataloger/common/generic_cataloger_test.go
syft/cataloger/rpmdb/parse_rpmdb.go
syft/cataloger/rpmdb/parse_rpmdb_test.go
syft/source/all_layers_resolver.go
syft/source/all_layers_resolver_test.go
syft/source/directory_resolver.go
syft/source/directory_resolver_test.go
syft/source/image_squash_resolver.go
syft/source/image_squash_resolver_test.go
syft/source/mock_resolver.go
syft/source/resolver.go

Previously path existence was determined by the existence of file.References. However, this is no longer the case. Instead we should ask the underlying filetree (or generic source) if the path exists or not. This is due to the previous link resolution fix PR.

Add HasPath() to Resolver interface for existence check

---

syft/cataloger/deb/cataloger.go
syft/presenter/cyclonedx/presenter_test.go
syft/presenter/json/presenter_test.go
syft/presenter/table/presenter_test.go
syft/presenter/text/presenter_test.go
syft/source/all_layers_resolver.go
syft/source/all_layers_resolver_test.go
syft/source/image_squash_resolver.go
syft/source/image_squash_resolver_test.go
syft/source/location.go

With the new content API + link resolution changes it is possible for a bulk request to have multiple locations share the same file.Reference. This means that stereoscope will return a single reader for multiple callers. This PR duplicates the reader as necessary so Resolver callers get individual readers for paths that match the request (not necessarily the real path from the file.Reference).

Duplicate reference readers for duplicate location resolutions

---

internal/anchore/import_package_sbom_test.go
syft/cataloger/common/generic_cataloger.go
syft/cataloger/common/generic_cataloger_test.go
syft/cataloger/deb/cataloger.go
syft/cataloger/deb/cataloger_test.go
syft/cataloger/python/package_cataloger.go
syft/cataloger/python/package_entry.go
syft/cataloger/rpmdb/cataloger.go
syft/distro/identify.go
syft/presenter/cyclonedx/presenter_test.go
syft/presenter/json/presenter_test.go
syft/source/all_layers_resolver.go
syft/source/all_layers_resolver_test.go
syft/source/content_requester_test.go
syft/source/directory_resolver.go
syft/source/directory_resolver_test.go
syft/source/image_squash_resolver.go
syft/source/image_squash_resolver_test.go
syft/source/location.go
syft/source/mock_resolver.go
syft/source/resolver.go
test/integration/document_import_test.go

Before link resolution was done for ancestors, only leaf nodes in the file tree could be links. Now it is possible for ancestors of a path to have symlinks. This PR ensures that only the "real path" representation for a result (a path with no links) is surfaced during globbing, not necessarily the path matched against the glob pattern.
Also, the `source.Location` currently used to adapt to `file.Reference` has been enhanced to act as a more accurate key for content fetch requests by adding the resulting virtual path from the glob result onto the struct (which my have ancestor paths with symlinks).

Prefer real paths over those with links for glob results

---

syft/cataloger/javascript/parse_package_json.go
syft/cataloger/javascript/parse_package_json_test.go
syft/cataloger/javascript/test-fixtures/pkg-json/package-partial.json
test/integration/regression_test.go
test/integration/test-fixtures/image-large-apk-data/Dockerfile

Closes #311 
This PR changes the parsing of `package.json` such that files that don't include the minimally required fields (currently `name` and `version`) will not be surfaced as packages. A `DEBUG` level message is logged in this case.

Omit empty packages

---

syft/cataloger/java/archive_parser.go
test/integration/java_no_main_package_test.go
test/integration/test-fixtures/image-java-no-main-package/Dockerfile
test/integration/test-fixtures/image-large-apk-data/Dockerfile

Fixes #252 (and duplicate issue #291)
(this fix was provided by @wagoodman)
Signed-off-by: Alex Goodman <alex.goodman@anchore.com>

Ensure java parent pkg ref isn't nil when looking for parent matches

---

cmd/root.go
internal/anchore/client.go
internal/anchore/client_test.go
internal/anchore/import.go

Closes #315 
This PR:
- broadens what users can specify using the `--host` / `-H` configuration value (adds support for path prefixes, e.g. `-H localhost:8000/v1`)
- ensures that, for now, our base paths for API requests end with `/v1`

Allow path prefixes

---

Makefile

Adding this entry to the `Makefile` will allow:
1. Busting the _current_ cache, which may solve build issues:
```
Error: /usr/local/bin/gtar: ../../../go/pkg/mod/dmitri.shuralyov.com/gpu/mtl@v0.0.0-20190408044501-666a987793e9/example/hellotriangle/main.go: Cannot open: No such file or directory
```
2. Allow for future cache busting, since the key for the cache is partially computed by changes to the `Makefile` itself

make: add a bootstrap cache buster

---

.github/workflows/acceptance-test.yaml
.github/workflows/release.yaml
.github/workflows/static-unit-integration.yaml

Pinning GitHub's "cache" action to avoid an error caused by the latest release: https://github.com/actions/cache/issues/527

Pin actions/cache to v2.1.3

---

syft/pkg/catalog.go
syft/pkg/ownership_by_files_relationship.go

It may be possible for DPKG evidence locations to glean info from non-unique locations (such as `/usr/share/doc/**/copyright`) leading to relationships as so:
```
"artifacts" : [
{
"id": "b7ccf459-e10b-40da-855a-55ad224885aa",
"name": "libnettle7",
"type": "deb",
"locations": [
...
{
"path": "/usr/share/doc/libnettle7/copyright",
"layerID": "sha256:bacd3af13903e13a43fe87b6944acd1ff21024132aad6e74b4452d984fb1a99a"
},
...
],
},
...
{
"id": "a2009b4f-58bd-4a37-a1b3-b7388890b08f",
"name": "libhogweed5",
"type": "deb",
"foundBy": "dpkgdb-cataloger",
"locations": [
{
"path": "/usr/share/doc/libnettle7/copyright",
"layerID": "sha256:bacd3af13903e13a43fe87b6944acd1ff21024132aad6e74b4452d984fb1a99a"
}
],
},
....
]
"artifactRelationships": [
....
{
"parent": "b7ccf459-e10b-40da-855a-55ad224885aa", …
```

Ignore ownership for shared copyright resources

---

syft/distro/identify_test.go
syft/distro/test-fixtures/os/photon/etc/os-release
syft/distro/type.go

Signed-off-by: Haim Helman <hhelman@vmware.com>

Added Photon OS to the list of distros

---

.github/workflows/release.yaml
.goreleaser.yaml
Dockerfile
Makefile

This adds a docker image build step to goreleaser (publishing to `anchore/syft`). This work does NOT replace the additional work proposed in https://github.com/anchore/syft/pull/310 but instead only delivers the docker image portion for now. 
Note: this adds docker to the mac instance in CI during release.
Closes #228

Add Docker image to release process

---

.github/workflows/release.yaml

The https://github.com/docker/login-action github action is not supported on mac, thus we need to login manually (see https://github.com/anchore/grype/runs/2179331427?check_suite_focus=true)

Manually login to docker via cli during release

---

.github/workflows/release.yaml
Makefile

- We need to auth early the in release pipeline to prevent docker rate limiting while prepping for the release
- We need to auth again later in the pipeline within the release step since the mac code signing swaps out the default keychain

Move docker login to after keychain creation

---

syft/pkg/catalog.go
syft/pkg/catalog_test.go

For packages that have the same `RealPath` and `VirtualPath` for a given `Location` the `pkg.Catalog` is inserting duplicate entries (on for each path, even though they are the same). This PR ensures that duplicate paths for the same package are not added.

Ensure pkg.Catalog path index deduplicates real vs virtual paths

---

.github/workflows/validations.yaml

PRs from forks will not be able to add a sticky comment to PRs, so this step should be allowed to run without indicating a failure if the post fails (for any reason, not just the single reason listed here).

Ignore failures on benchmark sticky comment

---

cmd/power_user_tasks.go
internal/presenter/poweruser/json_file_metadata.go
internal/presenter/poweruser/json_presenter_test.go
internal/presenter/poweruser/test-fixtures/snapshot/TestJSONPresenter.golden
schema/json/schema-1.0.4.json
syft/file/digest_cataloger.go
syft/file/digest_cataloger_test.go
syft/file/metadata_cataloger_test.go
syft/source/file_metadata.go
syft/source/file_type.go
test/cli/power_user_cmd_test.go

- Added `LinkDestination` to `source.FileMetadata`, which is shown in the json output only when there is a value
- Makes `digests` an optional field in the json output
- Adds tests for the power-user presenter
- Renames `source.FileType` strings to be capitalized (consistent with similar fields)
- Fixes a bug where there are digests with a single value which have empty `algorithm` and `value` fields.
- Fixed a bug where sorting file metadata was not stable
Related to https://github.com/anchore/syft/issues/335

Add link destination to file metadata

---

internal/presenter/packages/cyclonedx_document.go
internal/presenter/packages/table_presenter.go
syft/pkg/catalog.go

Switches use of catalog.Enumerated() to catalog.Sorted() and adds the location as a component of the sort key.
Fixes #331

Use sorted artifacts for consistent SBoM output in table, cyclonedx, and json presenters

---

go.mod
go.sum

Pulls in fix from https://github.com/anchore/stereoscope/pull/63

Ensure credentials are not HTML encoded

---

ui/event_handlers.go

Exports a value (`StatusTitleColumn`) that needs to be synchronized between Syft and Grype, for: https://github.com/anchore/grype/issues/289

Expose column index for UI handler consumers

---

internal/config/registry.go
internal/config/registry_test.go

Enforces that user and password OR a token must be present --no partial values allowed now. Sister PR to https://github.com/anchore/grype/pull/293
Closes #385

Modify registry credential verification

---

README.md
go.mod

Secrets cataloger requires crypto feature from the latest 1.16 version of go.

Bump go.mod minimum required go version to 1.16

---

.github/workflows/validations.yaml
test/acceptance/mac.sh

Today the `/tmp/image.tar` file used for mac acceptance testing is cached, however, the system used for CI is unable to untar into /tmp:
Resulting in docker pull rate limits over time:
This PR moves the image to a location which can be restore to by the cache (not in /tmp)
Additionally this PR fixes a bad image reference given to syft (`docker-archive://` vs `docker-archive:`) and now only installs skopeo on a cache miss.

Change mac acceptance test image.tar path

---

schema/json/schema-1.1.0.json
syft/pkg/apk_metadata.go
syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

Replaces the singular Checksum field with the standard `file.Digest` field, indicating a value and algorithm fields. 
Last PR for / Closes #371

Use the standard file.Digest for apk checksums

---

syft/pkg/cataloger/cpe.go
syft/pkg/cataloger/cpe_test.go

Today anchore-engine has a `nomatch_inclusion` dictionary for adding known good CPE product field candidates to the CPE generation logic. This PR adds the same functionality with the same values. In the future we can expose this via user configuration.
Closes #393

Add CPE product field swap replacements for known cases

---

Makefile

The release pipeline downloads the required go modules, however, this may modify the go.sum. The state of the sum may be equivalent to that of what is checked into git, however, to ensure this is the case `go mod tidy` must be run to get the reduced state. If the state differs, then there is a problem and the release should be halted (goreleaser does this), otherwise it is safe to continue.
```
❯ go clean --modcache
❯ git status
On branch bootstrap-go-mod-tidy
nothing to commit, working tree clean
❯ go mod download
❯ git status
On branch bootstrap-go-mod-tidy
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   go.sum
no changes added to commit (use "git add" and/or "git …
```

Ensure consistent go.sum state during release

---

internal/string_helpers.go
internal/string_helpers_test.go
syft/pkg/cataloger/cpe.go
syft/pkg/cataloger/cpe_test.go
syft/pkg/cataloger/java/archive_parser.go
syft/pkg/java_metadata.go
syft/pkg/java_metadata_test.go
test/integration/catalog_packages_cases_test.go
test/integration/catalog_packages_test.go

This adds the following features to the CPE generation logic:
- Adds `io.jenkins.plugins`, `io.jenkins-ci.plugins`, `org.jenkins.plugins`, and `org.jenkins-ci.plugins` as known jenkins plugins GroupIDs to identify a `JenkinsPlugin` package type.
- Enhances the GroupID logic to search for value prefixes instead of exact match (this covers cases such as `io.jenkins.plugin.bluesteel`)
- Adds ability to filter CPEs from the final generated list based on a filter function (which gets the CPE in question and the package it should describe). In this way there is a sanity check for known bad generated values.

Enhance CPE generation for java GroupId and filtering

---

syft/pkg/java_metadata.go
syft/pkg/java_metadata_test.go

There are several examples in the `cloudbees-mm-core` image for jenkins plugin jars that have `jenkins.plugin` or `jenkins.plugins` in the group ID, but are specifically for their org, thus, a full or prefix group id match will not work.

Add additional cases for categorizing jenkins package type by group id

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go

It was discovered that we're potentially missing java dependencies for jars that have multiple pom properties. This seems to be the case especially for shaded jars, which may have more than one pom properties (one for each packaged dependency). This PR attempts to close the gap on correctness here, only updating the parent package if there is a positive match of the parent package identity and the discovered identity from the pom properties. 
The main change made was related to how we match a parent and child package; The artifactID and parent package name must match, they cannot be subsets of one another. This may regress other cases, however, the previous code was too presumptive (see the comments). 
This came from an investigation of looking at the `cloudbees-mm-core` image and why it …

Update parent pom persistence with regard to shaded jars

---

.github/workflows/release.yaml
.github/workflows/validations.yaml

Currently the release pipeline will not complete; the job names are tied to the `name:` attribute, not the yaml section name, which means the quality gate checks need to be adjusted to match.

Align check names to release quality gate

---

internal/err_helper.go
syft/distro/identify.go
syft/file/classifier.go
syft/file/contents_cataloger.go
syft/file/digest_cataloger.go
syft/file/secrets_cataloger.go
syft/file/secrets_search_by_line_strategy.go
syft/pkg/cataloger/common/generic_cataloger.go
syft/pkg/cataloger/deb/cataloger.go
syft/pkg/cataloger/javascript/parse_package_json.go
syft/pkg/cataloger/python/package_cataloger.go
syft/pkg/cataloger/rpmdb/cataloger.go

When analyzing images with several files opened the following warning was being seen in the logs:
```
[0025]  WARN cataloger 'javascript-package-cataloger' failed to parse entries ....: failed to parse package.json file: open 
```
Where it seems that syft was exhausting all file descriptor resources on the system. The cause was from PR #339 which pulled in several impactful stereoscope changes, including how you retrieve contents from underlying images... which now returns ReadClosers, not just Readers. The caller is now responsible for explicitly calling `Close()`, though stereoscope attempts to close when an `EOF` is observed, not all cataloger parsers read till the end of every file.
This PR adds a corresponding `Close()` call for every `ReadCloser` provided by stereoscope.

Close all ReadClosers explicitly retrieved from resolvers

---

syft/pkg/metadata.go

Adds a slice that lists all package metadata types, which is useful for downstream testing in grype (now in a test you can more easily answer "have I covered all possible metadata types with this test?" ).

Add all package metadata types slice for use in downstream testing

---

go.mod
go.sum
internal/config/registry.go
internal/config/registry_test.go
test/cli/packages_cmd_test.go

Related to https://github.com/anchore/stereoscope/issues/68
Allows Syft to use registry credentials in cases where the user hasn't provided an "authority" config value

Allow registry auth config without authority value

---

cmd/packages.go
internal/anchore/import.go
internal/config/anchore.go
internal/presenter/poweruser/test-fixtures/snapshot/TestJSONPresenter.golden

Closes #419 
Adds a new CLI flag (`--import-timeout`) and backing config option (`"anchore.import-timeout"`) to Syft. This allows the user to control the timeout duration applied to the image SBOM import operation. By default, this value is set to **30 seconds**.

Add config option for import timeout

---

.github/scripts/go-mod-tidy-check.sh
Makefile
go.sum

Brings in `go mod tidy` fix from https://github.com/anchore/grype/pull/323 (with minor update)

Fix go mod tidy release problem

---

.github/ISSUE_TEMPLATE/config.yml

Fixes #423 
For why this is needed, see https://github.com/anchore/syft/issues/423#issuecomment-848738330.
Next, I'll open an equivalent PR in [Grype](https://github.com/anchore/grype).

Replace links to Slack channels with public signup link

---

go.mod
go.sum
syft/pkg/cataloger/package_url_test.go
syft/pkg/cataloger/rpmdb/parse_rpmdb.go
syft/pkg/cataloger/rpmdb/parse_rpmdb_test.go
syft/pkg/rpmdb_metadata.go
syft/pkg/rpmdb_metadata_test.go

This PR makes a few changes to how RPM versions are displayed:
- Epoch is optionally included in the `pkg.Package.Version` field, only if the epoch version is explicitly set for that package in the RPM DB (0 is not assumed)
- Release field is included in the `pkg.Package.Version` field
- for pURLs representing RPMs, the epoch is specified as a qualifier and not as part of the version
~Note: this will remain in draft until all changes to the grype matching are identified and drafted.~ (confirmed intended behavior)
Closes #408

Allow for RPM package epoch to be optionally provided in the version field

---

.github/workflows/validations.yaml

This allows us to lean on the speculative merge ref for testing in PRs (currently ignored for internal PRs).

Respond to pull_request events for internal PRs

---

cmd/event_loop.go
cmd/event_loop_test.go
internal/ui/ephemeral_terminal_ui.go
internal/ui/logger_ui.go
internal/ui/ui.go

This PR fixes the behavior in v0.18.0 where ctrl C does not appear to interrupt the application execution. When a signal interrupt is handled it is important that the UI is forcefully torn down, not waiting for any unfinished elements (e.g. spinners). This PR adds this forcing mechanism.

Force UI teardown when event is sourced from a signal interrupt

---

cmd/packages.go
cmd/power_user.go
test/cli/packages_cmd_test.go
test/cli/power_user_cmd_test.go

Now when no arguments are provided, the default help text is displayed:
```
$ syft packages
Generate a packaged-based Software Bill Of Materials (SBOM) from container images and filesystems
Usage:
packages [SOURCE] [flags]
...
an image/directory argument is required
exit status 1
```

Add help message when no arguments are provided

---

go.mod
go.sum
internal/ui/ephemeral_terminal_ui.go

https://github.com/anchore/syft/pull/448 pulled in an external lib to perform hiding/showing the cursor. However, this needs to be done relative to the right output stream (in our case, stderr), otherwise `syft | less` will continue to show the cursor.
This PR restores this functionality.

Redirect cursor hide/show to stderr

---

syft/source/directory_resolver.go
syft/source/directory_resolver_test.go

If the directory resolver indexes multiple roots (due to sym links found) then each discovered root shows up as a progress bar on the ETUI. This should not be the case --instead only the requested root should be reported.

Fix directory resolver indexer to report one progressable object

---

syft/distro/identify.go
syft/distro/identify_test.go
syft/distro/test-fixtures/partial-fields/missing-id/usr/lib/os-release
syft/distro/test-fixtures/partial-fields/missing-version/usr/lib/os-release
syft/distro/test-fixtures/partial-fields/unknown-id/usr/lib/os-release

While scanning a Debian derivative that is not mapped by `syft` I discovered that the entire `name:version:like` tuple is `nil`. The functional impact is limited as the _catalogers_ still find the DPKG files, but there's an empty `distro` object in the final JSON and the `purl` URLs aren't computed either.
This PR tries lazily to achieve that by avoiding returning `nil` early and attempting mapping again with the `ID_LIKE` value, if it was detected.
This of course means the `purl` URLs might be inaccurate and it might warrant some form of debug warning to the user, or a strict mode.
One final element to consider is that the distro _name_ (as declared in, say, `/etc/os-release`) seems to get effectively overridden by the way `syft` calls distros (the mapping result) but this is minor (it …

Minimal changes to use ID_LIKE

---

go.mod
go.sum
syft/pkg/apk_metadata_test.go

Update `packageurl-go` lib [temporarily to one](https://github.com/anchore/packageurl-go) that includes a few minor encoding fixes that have been [sitting in a PR for a while](https://github.com/package-url/packageurl-go/pull/22). And add a couple tests to validate purl generation and parsing both ways works properly.

test: add additional packageurl encoding tests for #351

---

README.md
go.mod
go.sum
internal/config/registry.go
internal/config/registry_test.go
internal/presenter/poweruser/test-fixtures/snapshot/TestJSONPresenter.golden
test/cli/packages_cmd_test.go

Adds an option to allow connection to registries over `http`. This is not a strict requirement for https://github.com/anchore/grype/issues/334 but implemented for feature parity. Related to: https://github.com/anchore/grype/pull/380
Added just a very basic test, as this is just pushing configuration to `go-containerregistry`

Add option to enable http connection to registries 

---

syft/pkg/cataloger/python/index_cataloger.go
syft/pkg/cataloger/python/parse_pipfile_lock.go
syft/pkg/cataloger/python/parse_pipfile_lock_test.go
syft/pkg/cataloger/python/test-fixtures/pipfile-lock/Pipfile.lock

Signed-off-by: Nikita <33390074+Zilborg@users.noreply.github.com>
Issue: #242

Added parser for Pipfile.lock to cataloger

---

.github/workflows/release.yaml
.goreleaser.yaml

Currently cannot install docker onto the mac runners in GHA, which we need for signing. The workaround is to disable docker releases for the short-term until we have a fix in place (but we cannot block binary releases on this)
Example infinite loop:
https://github.com/anchore/syft/actions/runs/1199137004

Disable docker releases

---

cmd/packages.go
cmd/power_user.go
cmd/power_user_tasks.go
internal/err_helper.go
syft/file/classification_cataloger_test.go
syft/file/contents_cataloger.go
syft/file/digest_cataloger.go
syft/file/secrets_cataloger.go
syft/lib.go
syft/source/directory_resolver.go
syft/source/directory_resolver_test.go
syft/source/location.go
syft/source/source.go
syft/source/source_test.go
test/cli/power_user_cmd_test.go
test/integration/utils_test.go

Hi guys.
My first contribution here, sorry if i am missing something.
Add support of using directory type sources on the **power-user** command.
**Following support have been addressed**
- Digest, contents and secret catalogers require `read` permissions, encountering  a permission error fails the catalogers.
**Fix**: Log the error (debug) instead of failing, skip ahead.
- Digest and metadata cataloger will fail saying all files sent do not exists in resolver  - cataloger fails.
**Reason**: `directoryResolver.AllLocations`, `directoryResolver.FilesByGlob` returns locations that is not connected to the directory resolver file references.
**PR**: Return locations that are connected to directory resolver file references.
**Test**
- Added cli test `test/cli/power_user_cmd_test.go`, …

Power user dir

---

.github/workflows/release.yaml
.goreleaser.yaml

Reverts anchore/syft#493
Testing the docker install process on a fork shows that this issue has been resolved. There is the larger issue of this occurring again in the future --it would be ideal to solve this by removing the dependency on `docker-practice/actions-setup-docker@v1` and docker desktop for mac in general. (Migrating to builds via podman + qemu?)

Revert "Disable docker releases"

---

go.mod
go.sum

This is a follow up to https://github.com/anchore/go-rpmdb/pull/5

Update go-rpmdb and restruct gomod references

---

internal/logger/logrus.go

Removes permissive file creation and sets default to 0644

lower log file permissions to 0644

---

.bouncer.yaml
go.mod
go.sum
internal/spdxlicense/generate_license_list.go
syft/pkg/apk_metadata.go
syft/pkg/apk_metadata_test.go
syft/pkg/cataloger/package_url.go
syft/pkg/dpkg_metadata.go
syft/pkg/java_metadata.go
syft/pkg/rpmdb_metadata.go
syft/pkg/type.go

As [discussed in the community Slack](https://anchorecommunity.slack.com/archives/C0190NF9TSM/p1632315222000900), using a `replace` directive in a module's `go.mod` means that projects like Syft will build differently themselves than when imported by consumers and then built. This could mean that consumers of Syft experience unexpected behavior, or even potentially broken builds, since they're using a state different than we're testing in Syft.
This PR follows up https://github.com/anchore/packageurl-go/pull/2 by removing the `replace` directive from Syft's `go.mod`, thereby pivoting Syft to rely more directly on Anchore's fork.

Use Anchore fork of packageurl lib without replace directive

---

syft/pkg/cataloger/common/cpe/field_candidate.go
syft/pkg/cataloger/common/cpe/field_candidate_test.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go

Any CPE generated should never be `*` or an empty string, as these value represent "any" value during the matching process in grype.

Filter out CPE product candidates that are asterisks

---

syft/pkg/cataloger/common/cpe/field_candidate.go
syft/pkg/cataloger/common/cpe/field_candidate_filter.go
syft/pkg/cataloger/common/cpe/field_candidate_test.go
syft/pkg/cataloger/common/cpe/filter.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/java.go

This is the second half of the solution to https://github.com/anchore/grype/issues/417 (the first half being https://github.com/anchore/grype/pull/425).
This PR prevents CPEs from being generated where the product or vendor field contains URL-like strings (e.g. `http://jcp_org/en/jsr/detail?id=173`), or more generically, invalid string values.
This PR takes the approach of considering any field value that contains a colon (`:`) to be invalid, since colons are the delimiter of CPE fields, and this covers the case of URLs that contain substrings like `http://`.

Prevent invalid CPE field values

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
syft/pkg/cataloger/common/cpe/candidate_by_package_type_test.go
syft/pkg/cataloger/common/cpe/field_candidate.go
syft/pkg/cataloger/common/cpe/field_candidate_test.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/java.go
syft/pkg/cataloger/common/cpe/java_test.go

This PR at a minimum adds vendor + product CPE field generation cases found in `docker.io/kaazing-gateway:latest`, `docker.io/cassandra:latest`, and `docker.io/nuxeo:latest`.
Additionally this PR:
- refactors the mechanism used to specify and find CPE field additions for vendor and product
- removes OSGI directives from Java group ID fields
- removes double quotes from any CPE field generated

Add vendor + product known good CPE field values

---

syft/distro/identify_test.go
syft/distro/test-fixtures/os/mariner/etc/os-release
syft/distro/type.go

This PR adds [Mariner](https://github.com/microsoft/CBL-Mariner) to the list of distro types that syft recognizes.

Add mariner to distro types

---

cmd/packages.go
syft/pkg/cataloger/common/cpe/sort_by_specificity.go
syft/pkg/cataloger/common/cpe/sort_by_specificity_test.go

To see the current issue you can:
```
syft -o json alpine:latest > /tmp/alpine.json:latest
syft -o json alpine:latest > /tmp/alpine.json:latest:2 
diff -u /tmp/alpine.json:2 /tmp/alpine.json:latest
```
This will produce a diff where the `cpes` field for some packages is sorted differently from run to run.
In the case where `countFieldLength` is equal for two sequential CPE in a given list of CPE, then our sort function would return a non deterministic order for cases as seen below:
```
cpe:2.3:a:alpine-keys:alpine_keys:2.3-r1:*:*:*:*:*:*:*
cpe:2.3:a:alpine-keys:alpine-keys:2.3-r1:*:*:*:*:*:*:*
cpe:2.3:a:alpine_keys:alpine_keys:2.3-r1:*:*:*:*:*:*:*
cpe:2.3:a:alpine_keys:alpine-keys:2.3-r1:*:*:*:*:*:*:*
cpe:2.3:a:alpine:alpine_keys:2.3-r1:*:*:*:*:*:*:* …
```

497 stable sorted CPE array (JSON and SPDX)

---

internal/presenter/packages/spdx_json_presenter.go
internal/presenter/packages/spdx_json_presenter_test.go
internal/presenter/packages/test-fixtures/snapshot/TestSPDXJSONDirectoryPresenter.golden

Fixes: #495 
In the case where an input directory is `.` or `./` the name is stripped and a `uuidv4` becomes the namespace identifier.
When a URL is an input here is an example of the format output:
```
"documentNamespace": "https:/anchore.com/syft/image/gcr.io/distroless/nodejs-debian10-6d671418-314c-480b-a620-c86d985d5441",
```
Since `.` is unreserved I believe we can get away with keeping the baseURL for image inputs in the path:
https://datatracker.ietf.org/doc/html/rfc3986#section-2.3

(#495) Update `documentNamespace` uniqueness for spdx-json output

---

cmd/event_loop.go
cmd/event_loop_test.go
cmd/packages.go
cmd/power_user.go
cmd/report_writer.go
cmd/root.go
internal/config/application.go
internal/presenter/poweruser/test-fixtures/snapshot/TestJSONPresenter.golden
internal/ui/ephemeral_terminal_ui.go
internal/ui/event_handlers.go
internal/ui/logger_ui.go
internal/ui/select.go

This PR adds a new `--file` option that writes the report bytes out to the given file path. Note: since the same functionality will be ported to grype it was decided that `-f` will not be used since that option is already taken in grype.

Add option to output SBOM report to a file

---

README.md

As a follow up to https://github.com/anchore/syft/pull/530, adds the config docs to the README.

Add --file option to README

---

syft/file/classification_cataloger.go
syft/pkg/apk_metadata.go
syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

File digest information on alpine metadata is optional (since dir entries are valid), leading to entries that look like this:
```json
{
"originPackage": "busybox",
...
"files": [
{
"path": "/usr",
"digest": {
"algorithm": "",
"value": ""
}
},
...
```
This makes the digest field optional in the alpine datastructure, in which case it won't be included in the JSON output when there are no values.

Allow file digests instances to be optional for alpine metadata

---

internal/input.go

This is the sister PR to github.com/anchore/grype/pull/484, however, since syft currently does not accept input directly there are no further changes needed. See the code comment for more details on the nature of the change.

Use named pipe bit when checking for piped input

---

syft/pkg/cataloger/golang/bin_cataloger.go
syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/parse_go_bin_test.go
syft/source/all_layers_resolver.go
syft/source/all_layers_resolver_test.go
syft/source/image_squash_resolver.go
syft/source/image_squash_resolver_test.go
syft/source/location.go

Add more context to the parse function. Rather than only pass `realPath` we pass Location so `layerID` information could be populated.
This additionally fixes the image-based `source.FileResolver`s to always include layer information in `Location` references returned.
Closes #619

Add layer information for go-module-binary-cataloger

---

cmd/packages.go
internal/anchore/import.go
internal/anchore/import_package_sbom.go
internal/anchore/import_package_sbom_test.go

Migrates the `import` code to use the new `sbom.SBOM` data structure.
This is a follow up from a PR comment here: https://github.com/anchore/syft/pull/606#discussion_r743688889

Use SBOM data structure in ImportConfig

---

schema/json/vnd.syft+json

WIP: Ideally we can discuss this in the afternoon and have a submission by the end of the day

document current draft for iana submission

---

syft/source/source.go

Add a second call to `GetImageFromSource` if a prefix was aggressively parsed causing an image name to be shortened into an invalid image.
Docker image cases now covered:
- docker:20.10.0-rc2-git
- docker:docker:20.10.0-rc2-git
#287 (Can't link the issue for some reason)
Had to break things into smaller components because of the linter.

287 - Add retry for image fetch using user's input

---

.bouncer.yaml
Makefile
cmd/packages.go
cmd/power_user.go
go.mod
go.sum
syft/distro/identify.go
syft/source/source.go
syft/source/source_test.go
syft/source/test-fixtures/generate-tar-fixture-from-source-dir.sh

This PR adds support for cataloging the contents of a given archive:
```
❯ syft file:./hike-gem.tar.gz
...
NAME                               VERSION                         TYPE
hike                               1.2.3                           gem
❯ syft ./hike-gem.zip
...
NAME                               VERSION                         TYPE
hike                               1.2.3                           gem
❯ syft ~/oci-images/ubi8.tar
...
NAME                                    VERSION                          TYPE
PyGObject                               3.28.3                           python
PySocks                                 1.6.8                            python
acl                                     2.2.53-1.el8                     rpm
audit-libs …
```

Catalog archive contents for single-file input

---

cmd/power_user.go

Discussion on a separate PR was made around how we populate relationships.
This pr removes a level of concurrency and returns a slice. If we're good with this we can apply it to the `packages` command.
Previous discussion: https://github.com/anchore/syft/pull/636#discussion_r752440947

Update concurrency primitives for relationships

---

cmd/event_loop.go

There is no need to log bus unsubscribe errors (e.g. "unable to find subscription to unsubscribe" errors) as this is not actionable.

Ignore partybus unsubscribe errors

---

go.mod
go.sum

jotframe had been allocating a 300MB event buffer, bumping the dependency will drop this by a few orders of magnitude.

Use a smaller jotframe event buffer

---

syft/source/directory_resolver.go
syft/source/directory_resolver_test.go

The directory resolver `FileContentsByLocation` method currently does not rely on `file.Reference` to fetch content, which may lead to empty responses when infact there is content available.

Fix content access for directory resolver

---

internal/formats/common/spdxhelpers/document_name.go
internal/formats/common/spdxhelpers/document_name_test.go
internal/formats/common/spdxhelpers/document_namespace.go
internal/formats/common/spdxhelpers/document_namespace_test.go
internal/formats/cyclonedx12xml/to_format_model.go
internal/formats/spdx22json/encoder.go
internal/formats/spdx22json/test-fixtures/snapshot/TestSPDXJSONDirectoryPresenter.golden
internal/formats/spdx22json/test-fixtures/snapshot/TestSPDXJSONImagePresenter.golden
internal/formats/spdx22json/to_format_model.go
internal/formats/spdx22tagvalue/encoder.go
internal/formats/spdx22tagvalue/encoder_test.go
internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryPresenter.golden
internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXTagValueImagePresenter.golden
internal/formats/spdx22tagvalue/to_format_model.go
internal/formats/syftjson/to_format_model.go
internal/formats/syftjson/to_format_model_test.go
internal/formats/syftjson/to_syft_model.go
internal/formats/syftjson/to_syft_model_test.go
internal/formats/text/encoder.go
syft/source/scheme.go

The current SPDX namespace values being produced by syft look like:
```
https:/anchore.com/syft/...
```
This PR fixes this behavior, moves name and namespace related helpers to the `spdxhelpers` package, and adds assertion around testing to ensure that `source.Scheme`s are fully tested (while writing tests for this it was noticed that cases for `FileScheme` were missing).
Additionally closes #622

Fix SPDX namespace value

---

syft/pkg/cataloger/catalog.go

Remove the log warning for `WARN unable to find location which a package claims ownership of: ...`. See code comment for details.
<details>
<summary>Click for an example...</summary>
```
$ syft  ubuntu:latest -vv
[0000] DEBUG application config:
output: table
file: ""
quiet: false
check-for-app-update: true
anchore:
host: ""
path: ""
dockerfile: ""
overwrite-existing-image: false
import-timeout: 30
dev:
profile-cpu: false
profile-mem: false
log:
structured: false
level: debug
file: ""
package:
cataloger:
enabled: true
scope: Squashed
file-metadata:
cataloger:
enabled: false
scope: Squashed
digests:
- sha256
file-classification:
cataloger:
enabled: false
scope: Squashed
file-contents:
cataloger:
enabled: false
scope: Squashed
skip-files-above-size: 1048576
globs: []
secrets:
cataloger: …
```

Remove warning regarding missing file when crafting relationships

---

go.mod
go.sum

Incorporates https://github.com/anchore/stereoscope/pull/90 to remediate known GHSAs

Bump containerd and image-spec

---

syft/pkg/cataloger/deb/cataloger.go

Fixes behavior seen in https://github.com/anchore/grype/issues/523

Fix panic from reading nonexistent debian config file

---

internal/constants.go
internal/formats/common/testutils/utils.go
internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryPresenter.golden
internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
internal/formats/syftjson/test-fixtures/snapshot/TestImagePresenter.golden
schema/json/generate.go
schema/json/schema-2.0.1.json
syft/pkg/cataloger/golang/exe.go
syft/pkg/cataloger/golang/exe_test.go
syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/parse_go_bin_test.go
syft/pkg/golang_bin_metadata.go

Adds the ability to catalog [Macho multiarchitecture binaries](https://en.wikipedia.org/wiki/Fat_binary) that are built by the go compiler.
Additionally this PR:
- raises up the architecture for a given package within a binary in the package metadata section
- adds the go binary metadata struct to the JSON schema
This relates to https://github.com/goreleaser/goreleaser/pull/2648#discussion_r765129074

Add cataloging of macho multi-architecture binaries

---

syft/pkg/cataloger/golang/binary_cataloger.go
syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/parse_go_bin_test.go
test/cli/packages_cmd_test.go
test/cli/test-fixtures/image-bad-binaries/Dockerfile
test/cli/test-fixtures/image-bad-binaries/sources.list
test/cli/utils_test.go

Addresses anchore/grype#526
When processing malformed binaries the stdlib does not take into consideration several edge cases, resulting in a panic instead of returning an error. When this happens grype (or syft) will exit with an error. 
This PR attempts to recover from any panics from this specific execution path until these cases can be dealt with within the stdlib. This allows for syft/grype to continue cataloging paths that didn't have problems and still produce a report instead of exiting early.

Recover from panics from the stdlib when cataloging malformed binaries

---

syft/pkg/cataloger/java/parse_java_manifest.go
syft/pkg/cataloger/java/parse_java_manifest_test.go

The issue is the MANIFEST for the `tomcat-jdbc.jar` only included a `Bundle-Version`, so we can fall back to this as a last resort.
```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.16
Created-By: 11.0.13+8 (Eclipse Adoptium)
Export-Package: org.apache.tomcat.jdbc.naming;uses:="javax.naming,org.
apache.juli.logging,javax.naming.spi";version="10.0.14",org.apache.to
mcat.jdbc.pool;uses:="org.apache.juli.logging,javax.sql,org.apache.to
mcat.jdbc.pool.jmx,javax.management,javax.naming,javax.naming.spi,org
.apache.tomcat.jdbc.pool.interceptor";version="10.0.14",org.apache.to
mcat.jdbc.pool.interceptor;uses:="org.apache.tomcat.jdbc.pool,org.apa
che.juli.logging,javax.management.openmbean,javax.management";version
="10.0.14",org.apache.tomcat.jdbc.pool.jmx;uses:="org.apache.tomcat.j …
```

Catalog java bundle-version if nothing else found

---

syft/pkg/cataloger/java/parse_java_manifest.go
syft/pkg/cataloger/java/parse_java_manifest_test.go
syft/pkg/cataloger/java/test-fixtures/manifest/extra-empty-lines

For https://github.com/anchore/grype/issues/538

Handle extra empty lines in Java manifest parsing

---

syft/pkg/cataloger/java/parse_java_manifest.go
syft/pkg/cataloger/java/parse_java_manifest_test.go
syft/pkg/cataloger/java/test-fixtures/manifest/extra-empty-lines

When originally developing the java manifest parsing it was heavy in returning errors over returning partial results. This PR adjusts the behavior of the parser to be "best-effort" and return results when possible (even if partial).

Prefer warning over erroring out when parsing java manifests

---

README.md
cmd/packages.go
cmd/power_user.go
internal/config/application.go
syft/lib.go
syft/source/directory_resolver.go
syft/source/excluding_file_resolver.go
syft/source/excluding_file_resolver_test.go
syft/source/source.go
syft/source/source_test.go

This adds the `--exclude` flag to exclude paths from directory, archive, and image scans. This addresses #221
TODO:

Add --exclude flag

---

cmd/packages.go
go.mod
go.sum
syft/source/source.go

This fixes #701, ~although this is likely to revert the fix applied for #287 in the PR #626~ (**EDIT**: This is no longer true, we can preserve the retry functionality used in #626 with some minor tweaks 🎉 ).
Due to the complexity of the call graph for determining and processing an image source, it's probably best if user input is processed only one way if a scheme is specified, to avoid even more potential execution paths. What was happening that led to the misleading error message in #701 was that a second attempt of interpreting user input caused the error message from the first attempt to be swallowed (an error message which would've helped the user figure out the issue more quickly).
~This PR is intended to be dependent on https://github.com/anchore/stereoscope/pull/92, so I'll start …

Fix unhelpful error message for oci-archive scheme

---

internal/constants.go
internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryPresenter.golden
internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
internal/formats/syftjson/test-fixtures/snapshot/TestImagePresenter.golden
schema/json/schema-2.0.2.json

Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
This updates the schema to reflect the changes introduced by #708 
```bash
diff schema/json/schema-2.0.1.json schema/json/schema-2.0.2.json
745a746,763
>     "PythonDirectURLOriginInfo": {
>       "required": [
>         "url"
>       ],
>       "properties": {
>         "url": {
>           "type": "string"
>         },
>         "commitId": {
>           "type": "string"
>         },
>         "vcs": {
>           "type": "string"
>         }
>       },
>       "additionalProperties": true,
>       "type": "object"
>     },
824a843,846
>         },
>         "directUrlOrigin": {
>           "$schema": "http://json-schema.org/draft-04/schema#",
>           "$ref": "#/definitions/PythonDirectURLOriginInfo"
```

Bump syft JSON schema and add v2.0.2

---

.github/scripts/goreleaser-install.sh
Makefile

The new goreleaser releases have SBOMs attached, so we need to make certain the checksum validation keeps that in mind when looking for the right asset.

Bump goreleaser to v1.2

---

test/cli/packages_cmd_test.go

I haven't been able to reproduce locally yet, but in CI this has proven to be unstable.
For the same commit:
- pass: https://github.com/anchore/syft/runs/4611344142?check_suite_focus=true
- fail: https://github.com/anchore/syft/runs/4611343586?check_suite_focus=true
For the meantime this test will be commented out, but should be added back in as soon as possible.

Remove unstable CLI test (bad binaries)

---

cmd/root.go

Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
Fixes #700 
Output -
```bash
go run main.go --version
syft [not provided]
```
When a version is set - 
```bash
syft-dev --version
syft 0.34.0
```
```
go run main.go --help
Generate a packaged-based Software Bill Of Materials (SBOM) from container images and filesystems
Usage:
[flags]
[command]
Examples:
syft packages alpine:latest                a summary of discovered packages
syft packages alpine:latest -o json        show all possible cataloging details
syft packages alpine:latest -o cyclonedx   show a CycloneDX formatted SBOM
syft packages alpine:latest -o spdx        show a SPDX 2.2 tag-value formatted SBOM
syft packages alpine:latest -o spdx-json   show a SPDX 2.2 JSON formatted SBOM
syft packages alpine:latest -vv …
```

Add a version flag

---

.github/scripts/goreleaser-install.sh
Makefile

The latest release did not properly update the checksums for all of the darwin-related assets. This appears to be due to the specific goreleaser configuration we have, however, testing changes to this is non-obvious since it overlaps with behavior in the signing section (which is notoriously hard to test). 
We need to get the mac signing process into a state where we can confidently test process changes without needing production secrets or testing on a real release. I can follow up with details in a future PR, however, for the meantime we should fallback to the old release of goreleaser until we have made the proper configuration updates.

Revert "Bump goreleaser to v1.2"

---

install.sh

Although arm64 images were made available as a release, the install script would not pull them in automatically.

Add arm64 support to install script

---

syft/pkg/cataloger/java/archive_filename.go
syft/pkg/cataloger/java/archive_filename_test.go
syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/cataloger.go

Support .par format for #728.  This succesfully detects log4j in the sample .par file at https://github.com/palantir/log4j-sniffer/blob/develop/examples/inside_a_par/wrapped_in_a_par.par.
Signed-off-by: Weston Steimel <weston.steimel@gmail.com>

support .par for java ecosystems

---

internal/formats/common/spdxhelpers/external_refs.go
internal/formats/common/spdxhelpers/external_refs_test.go
internal/formats/syftjson/to_format_model.go
syft/pkg/cataloger/common/cpe/filter.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/sort_by_specificity.go
syft/pkg/cpe.go
syft/pkg/cpe_test.go
syft/pkg/test-fixtures/cpe-data.json
test/integration/encode_decode_cycle_test.go

Fixes #712 
Fixes #426 
Currently syft seems to generate invalid CPEs which do not
conform with the official CPE spec. This is because the underlying
nvdtools library is not a completely spec compliant implementation
and has some interesting bugs/issues.
The following are the list of issues I have encountered with nvdtools:
1. It parses strings which are not CPEs incorrectly as valid CPEs. This
messes up our filter function which is supposed to filter out any
incorrect CPEs we generate. In order to fix this, I have introduced
a new regex in the NewCPE function which follows the upstream spec and
filters out any incorrect CPEs.
2. Introduce wfn.WFNize for any cpe attributes we infer from packages.
This ensures that we are escaping and quoting any special characters
before putting them into …

Fix CPE encode/decode when it contains special chars

---

internal/file/zip_file_manifest_test.go
internal/file/zip_file_traversal_test.go
internal/file/zip_read_closer_test.go
internal/formats/common/testutils/utils.go
syft/source/directory_resolver.go
syft/source/directory_resolver_test.go
syft/source/directory_resolver_test_windows.go
syft/source/directory_resolver_windows_test.go
syft/source/file_metadata_test.go
syft/source/source_test.go

- Add function that converts windows to posix functionality
- Add function that converts posix to windows
- Add build tags to remove windows developer environment errors
- redact carriage return specific windows issues
When scanning on windows using the `dir` directive the current directory resolver implementation cannot lookup file nodes that match glob patterns in the `filetree.` By converting Windows filepaths on the way in so that their locations match the `posix` standard, we allow for syft to match on directory resolver matching criteria.
Paths are then translated back into windows paths on the way out so the presentation layer shows users the correct on disk details for the given SBOM items.
- Exclude functionality needs to be updated in a separate PR
- Location data regarding …

683 windows filepath

---

go.mod
go.sum

Bumps stereoscope which resolves dependency for:  https://github.com/containerd/containerd/security/advisories/GHSA-mvff-h3cj-wj9c

bump stereoscope version to remove old containerd

---

.goreleaser.yaml

Run `make snapeshot` on this branch. Under `snapshot` there should be a file called `syft_0.35.0-SNAPSHOT-5e5312c_checksums.txt`
Below is the output for that file.
```
0059dc697bca9c0368b676a0feafe98367da762e463e88f89cb740d4cb3bc4a5  syft_0.35.0-SNAPSHOT-b308f74_darwin_amd64.zip
3a72bf458ff4684dc761a825045d1e688f3729ff6e4e29140a0343eacef3f2a5  syft_0.35.0-SNAPSHOT-b308f74_linux_arm64.rpm
4295acf62ae1cd3675bdc1321a045d2b2039e017ecbf229707d1ae92e6f2dfb9  syft_0.35.0-SNAPSHOT-b308f74_darwin_amd64.tar.gz
5277b46093d67ee310fcbbc0e6fc059abe4dfa4799ac6797e58997fec6482a2a  syft_0.35.0-SNAPSHOT-b308f74_darwin_arm64.zip
744b967ef6b15f0e222fdf483b8b852002a493b09837ae14cb426bc32040d872  syft_0.35.0-SNAPSHOT-b308f74_Linux_amd64.tar.gz
82bb6dd3ac03673fa4abd4b027f6969ee4eccc675fd9295c77ce19b79cac97dd …
```

update goreleaser with windows checksums

---

internal/formats/common/spdxhelpers/originator_test.go
internal/formats/common/spdxhelpers/origintor.go
internal/formats/spdx22json/model/element.go
internal/formats/spdx22json/to_format_model.go

This aligns the SPDX output more correctly with the SPDX 2.2 spec.
These changes are required for Syft's generated SPDX to import properly using the [spdx/tools-golang jsonloader](https://github.com/spdx/tools-golang/blob/main/jsonloader/jsonloader.go#L15)
Links to some pertinent resources:
* https://spdx.github.io/spdx-spec/package-information
* https://github.com/spdx/spdx-spec/blob/master/schemas/spdx-schema.json

Align SPDX export more with SPDX 2.2 specification

---

DEVELOPING.md

Adds developer documentation around getting started in the repo and testing levels. I've also added an outline for the architecture section as a starter for future PRs.

Start developer documentation

---

internal/formats/syftjson/model/source.go
internal/formats/syftjson/model/source_test.go

This fixes the root cause of https://github.com/anchore/grype/issues/592.
Syft's "syftjson" format had not accounted for the `"file"` type of `Source` during unmarshaling. This PR:
- adds `"file"` as an expected `Source` type
- creates tests for `Source` unmarshaling, including a new test case to catch this `"file"` case
To address the Grype bug, **a follow-up PR will be needed in Grype** to use a version of Syft that has this fix.
---
Lingering thoughts for the future:
1. It'd be nice to also assert in tests that all possible `Source.Type` values are being tested, similar to how we test the completeness of the test suite itself in other areas of the code.
2. Using a source of truth like [`AllSchemes`](https://github.com/anchore/syft/blob/main/syft/source/scheme.go#L26-L30) might be the …

Add support for "file" source type in syftjson unmarshaling

---

internal/formats/syftjson/model/package.go
schema/json/generate.go
schema/json/schema-3.0.1.json
syft/pkg/cataloger/php/parse_composer_lock.go
syft/pkg/cataloger/php/parse_composer_lock_test.go
syft/pkg/cataloger/php/parse_installed_json.go
syft/pkg/cataloger/php/parse_installed_json_test.go
syft/pkg/metadata.go
syft/pkg/php_composer_json_metadata.go
syft/pkg/php_composer_json_metadata_test.go

Adds additional PHP metadata as a follow up to https://github.com/anchore/syft/pull/609 and https://github.com/anchore/syft/pull/643 . This additionally adds better pURL support for composer packages derived from the new metadata (related to https://github.com/anchore/grype/issues/395).

Add additional PHP metadata

---

README.md

This morning I needed a fresh `.syft.yaml` configuration and copied it from the README. On run I had to make edits on my local in order for it to run. These updates make it so that on first copy from the documentation syft runs successfully.
```
failed to load application config:
unable to parse config: 1 error(s) decoding:
* 'registry.auth[1]' expected a map, got 'string'
```
```
✔ Loaded image
✔ Parsed image
✔ Cataloged packages      [92 packages]
⠏ Cataloging secrets       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  [0 secrets]^C
✔ Cataloged file digests
✔ Cataloged file metadata
```

update config to correctly work with syft first try

---

syft/pkg/apk_metadata.go
syft/pkg/apk_metadata_test.go
syft/pkg/dpkg_metadata.go
syft/pkg/dpkg_metadata_test.go
syft/pkg/python_package_metadata.go
syft/pkg/rpmdb_metadata.go
syft/pkg/rpmdb_metadata_test.go
syft/pkg/url.go

This adds an additional `upstream` qualifier to the pURLs that we generate for OS-related packages to indicate source package information.
The pURL spec does not strictly support this qualifier, however, it does seem like the best current option for encoding source-package information for a package.
Related to anchore/grype#395
cc: @kzantow

Encode upstream qualifier on OS package pURLs

---

internal/formats/common/cyclonedxhelpers/component.go
internal/formats/common/cyclonedxhelpers/group.go
internal/formats/common/cyclonedxhelpers/group_test.go
internal/formats/common/cyclonedxhelpers/properties.go
syft/pkg/java_metadata.go

Signed-off-by: Peter Balogh <p.balogh.sa@gmail.com>
related: #685 , #710 
In the case of java add artifactID and groupID pomProperties to the cycloneDX properties.
- support adding lower level struct to the properties.
- add `groupID` as a `group` to the CDX component in the case of Java

[CycloneDX] Add artifactID and groupID to the cycloneDX properties (support lower level struct as properties)

---

syft/pkg/cargo_package_metadata.go
syft/pkg/cataloger/javascript/parse_package_json.go
syft/pkg/cataloger/javascript/parse_package_json_test.go
syft/pkg/java_metadata.go
syft/pkg/language.go
syft/pkg/language_test.go
syft/pkg/npm_package_json_metadata.go
syft/pkg/type.go
syft/pkg/type_test.go
syft/pkg/url.go

This PR paves the way to use pURLs as a way to indicate package language and package type, two attributes that are not easily encoded into in-spec properties for CycloneDX and SPDX. This will be useful when decoding SBOM documents that did not necessarily originate from Syft, but do have pURL information available.
Possible future SPDX decode function:
```golang
func toSyftPackage(p model.Package) pkg.Package {
purl := spdxhelpers.ExtractPURL(p.ExternalRefs)
sP := pkg.Package{
Type:     pkg.TypeFromPURL(purl), //  <---- new function 
Name:     p.Name,
Version:  p.VersionInfo,
Licenses: spdxhelpers.ParseLicense(p.LicenseDeclared),
CPEs:     spdxhelpers.ExtractCPEs(p.ExternalRefs),
PURL:     purl,
Language: pkg.LanguageFromPURL(purl),  //  <---- new function 
}
sP.SetID()
return sP
}
``` …

Extract language and package type from pURLs on SBOM decode

---

.github/scripts/apple-signing/utils.sh

To account for the failure here: https://github.com/anchore/syft/runs/5070522994?check_suite_focus=true
```
⨯ release failed after 176.55s error=sign: ./.github/scripts/apple-signing/run.sh failed: exit status 2: tput: No value for $TERM and no -T specified
```

Tput requires explicit terminal type in CI

---

.github/scripts/apple-signing/notarize.sh

To prevent: https://github.com/anchore/syft/runs/5070963673?check_suite_focus=true
```
Task: notarizing binaries found in the release archive
zip error: Internal logic error (empty name without -j or -r)
error: cannot find payload for notarization: /Users/runner/work/syft/syft/dist/syft_0.37.1_darwin_amd64.zip
```

Fix repackaging of release archive for notarization

---

.github/scripts/apple-signing/notarize.sh

Failure: https://github.com/anchore/syft/runs/5071442335?check_suite_focus=true
```
<string>ERROR ITMS-4064: "File extension of file 'syft_0.37.2_darwin_arm64.tar.gz' is invalid for this software; use 'zip,pkg,dmg' instead." at SoftwareAssets/EnigmaSoftwareAsset</string>
```

Fix notarization: use repackaged archive, not original archive

---

.github/scripts/apple-signing/setup-prod.sh
Makefile

Accounts for: https://github.com/anchore/syft/actions/runs/1797291966https://github.com/anchore/syft/actions/runs/1797291966
Now that we setup the keychain later, we must move the docker auth step as well. Otherwise we load the docker credentials into a keychain that gets replaced.

Docker auth must occur after setting up prod keychain

---

test/cli/packages_cmd_test.go

CLI tests may run considerably slower (several minutes) on the registry auth tests when there is a non-registry service running on port 5000 (the same port that the registry tests reference). Turning off the offending service solves the problem, however, 5000 tends to be a commonly used port. Swapping to a port that is (probably) not in use speeds up the tests from minutes to seconds (~2 seconds). The test now references the extremely useful [QOTD port](https://en.wikipedia.org/wiki/QOTD) in the hopes to glean occasional wisdom.

Fix intermittent slow CLI tests

---

.github/scripts/apple-signing/setup.sh
.github/scripts/apple-signing/sign.sh
Makefile
test/install/test_harness.sh

There are multiple instance of:
1. OOM during snapshot builds (https://github.com/anchore/syft/actions/runs/1799784721/attempts/2)
2. install.sh tests failing periodically due to http server not being ready (https://github.com/anchore/syft/runs/5078759447?check_suite_focus=true)
This PR ~reduces the build parallelism~ fixes the signing bash script logging to not hang in CI and increases the wait time after setting up the http server for install.sh testing (which ideally would be event driven and not a sleep --happy to take suggestions here).

Stabilize CI behavior

---

.goreleaser.yaml

Solves: https://github.com/anchore/syft/runs/5096001393?check_suite_focus=true
```
...
• uploading to release      file=dist/syft_0.37.6_darwin_arm64.tar.gz name=syft_0.37.6_darwin_arm64.tar.gz
• uploading to release      file=dist/syft_0.37.6_darwin_arm64.tar.gz name=syft_0.37.6_darwin_arm64.tar.gz
...
• failed to upload artifact, will retry artifact=syft_0.37.6_darwin_arm64.tar.gz error=POST https://uploads.github.com/repos/anchore/syft/releases/58910722/assets?name=syft_0.37.6_darwin_arm64.tar.gz: 404 Not Found [] try=1
• uploading to release      file=dist/syft_0.37.6_darwin_arm64.tar.gz name=syft_0.37.6_darwin_arm64.tar.gz
```

Remove duplicate signing artifact

---

.github/scripts/apple-signing/notarize.sh
.github/scripts/apple-signing/sign.sh
.goreleaser.yaml
Makefile

The goreleaser signs step will not work for us as expected since:
1) we are releasing archives and not binaries, so we need to repackage the archive that contains the release binary
2) the signs step expects a signature file as output --replacing an existing asset will result in duplicate assets.

Migrate mac binary signing as post-build step

---

Makefile

As far as I can tell from https://github.com/anchore/syft/runs/5100741150?check_suite_focus=true it seems that the notarization succeeds for one asset and fails for another asset. Notarization is supported for all architectures and the archive being submitted is prepared by the same script in either case. This PR restricts the release process to have no parallelism, which should result in a single notarization occurring at a time.

Serialize notarization steps

---

go.mod
go.sum
syft/source/source.go

closes #764
Brings in https://github.com/anchore/stereoscope/pull/100 -- fixing a bug where UI hangs due to wrong image metadata.

Ensure completion of UI progress bar

---

README.md

Added install details for nix
I'd also like to say I'm also happy to help out with the nix cataloger (#462) if you push it to a draft PR

Add nix install details

---

internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
internal/formats/spdx22tagvalue/to_format_model.go

Currently package IDs within SPDX tag-value documents allow for duplicate IDs, this PR includes the `pkg.Package.ID()` within the SPDX Element ID to account for this.

Deduplicate SPDX tag-value package IDs

---

go.mod
go.sum

Resolves:
https://security.archlinux.org/CVE-2021-43565
`20210921155107-089bfa567519` < `v0.0.0-20211202192323-5770296d904e`
Bump to `2022xxx`

update golang crypto library dependency

---

go.mod
go.sum
internal/formats/syftjson/decoder_test.go
internal/formats/syftjson/to_format_model.go
internal/formats/syftjson/to_format_model_test.go
syft/source/source.go

Pulls in https://github.com/anchore/stereoscope/pull/103 . There is no functional difference or additional features, only a difference in the API expression.

Bump stereoscope version to use functional options-based API

---

.github/workflows/release.yaml
install.sh
test/install/Makefile

The sbom-action installation failed in the latest release run: https://github.com/anchore/syft/runs/5204811566?check_suite_focus=true
```
[info] checking github for release tag='v0.33.0' 
[debug] http_download(url=[anchore/syft/releases/v0.33.0)](https://github.com/anchore/syft/releases/v0.33.0)) 
[info] using release tag='v0.33.0' version='0.33.0' os='darwin' arch='amd64' 
[debug] downloading files into /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.97tmb50y 
[debug] http_download(url=[v0.33.0 syft_0.33.0_checksums.txt) (download)](https://github.com/anchore/syft/releases/download/v0.33.0/syft_0.33.0_checksums.txt)) 
Error:  could not find release asset for os='darwin' arch='amd64' format='tar.gz'  
Error:  failed to install syft 
Error: ENOENT: no such file or directory, stat …
```

Upgrade install.sh to support installations for previous versions

---

syft/file/contents_cataloger.go

Content cataloger does not close the base64 encoder.
Last 4 byte block is dropped in content written to output.

Base64 encoder closing

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
syft/pkg/cataloger/common/cpe/generate_test.go

This PR accounts for an edge case for a java package that wraps a javascript node module. Within `cloudbees/cloudbees-core-mm:2.319.3.4` the `handlebars@3.0.8` package does not have enough packaging metadata to uncover the vendor of the wrapped package (which is `handlebarsjs`). Here we add an exception to additionally add a vendor of `handlebarsjs` for any java package with a name of `handlebars`. 
Regression tests have been added for this and for a `active-directory` case that requires no action.

Add exception for handlebars java package to generate nodejs CPE

---

.goreleaser.yaml
Makefile

In an attempt to troubleshoot the release failure I'm bumping the goreleaser timeout:
```
• building binaries
• building                  binary=/Users/runner/work/syft/syft/dist/linux-build_linux_amd64/syft
• building                  binary=/Users/runner/work/syft/syft/dist/linux-build_linux_arm64/syft
• building                  binary=/Users/runner/work/syft/syft/dist/darwin-build_darwin_amd64/syft
• running hook              hook=./.github/scripts/apple-signing/sign.sh "/Users/runner/work/syft/syft/dist/darwin-build_darwin_amd64/syft" "false" "darwin_amd64"
⨯ release failed after 1800.10s error=context deadline exceeded
Task: setting up production certificate material
1 identity imported.
keychain: "/Users/runner/Library/Keychains/ci-ephemeral-keychain-db"
version: 512
class: …
```

Bump release timeout

---

.github/scripts/apple-signing/cleanup.sh
.github/scripts/apple-signing/setup-dev.sh
.github/scripts/apple-signing/setup-import-cert.sh
.github/scripts/apple-signing/setup-prod.sh
.github/scripts/apple-signing/setup.sh
.github/scripts/apple-signing/sign.sh
.github/workflows/validations.yaml
.gitignore
.goreleaser/Makefile
.goreleaser/docker.yaml
.goreleaser/env-default.yaml
.goreleaser/env-skip-signing.yaml
.goreleaser/main.yaml
.goreleaser/snapshot.yaml
Makefile
goreleaser.yaml

This refactor shares as many procedures between dev and prod in terms of importing the code signing certificate done during the release (to help with testing).
Changes made:
- removing the use of `security add-trusted-cert` and using `-t cert` on `security import`
- the goreleaser timeout has been restored to 30 minutes
- the goreleaser config is now assembled from within the `.goreleaser` dir (was needed for the signing check in the pipeline)
I've added code that is commented out for now that creates a snapshot build with signing in the pipeline to ensure that this process works in CI without hanging (since this is to troubleshoot the release). Here is the run where signing in the pipeline worked just fine https://github.com/anchore/syft/runs/5339672887?check_suite_focus=true

Share import mac code signing certificate steps for release

---

internal/formats/common/cyclonedxhelpers/component.go
internal/formats/common/cyclonedxhelpers/component_test.go
internal/formats/common/cyclonedxhelpers/cpe.go
internal/formats/common/cyclonedxhelpers/cpe_test.go
internal/formats/common/cyclonedxhelpers/format.go
internal/formats/common/cyclonedxhelpers/properties.go
internal/formats/common/property_encoder.go
internal/formats/common/property_encoder_test.go
internal/formats/cyclonedx13json/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
internal/formats/cyclonedx13json/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
internal/formats/cyclonedx13xml/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
internal/formats/cyclonedx13xml/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
syft/source/location.go
test/integration/encode_decode_cycle_test.go

This fixes: #818 and #842 and will complete the encoder/decoder work for https://github.com/anchore/grype/issues/481

Update CycloneDX to use syft namespace and output multiple CPEs

---

.github/workflows/codeql-analysis.yml
.github/workflows/validations.yaml
test/install/test_harness.sh

- Adds polling check for install tests to ensure the snapshot server is up
- Elevates CodeQL to only run on main (not on PRs)
- De-duplicates checks as best as possible; CI checks only run on PRs and pushes to main. Pushes to feature branches will no longer trigger CI.

Reduce PR check failures

---

README.md
cmd/packages.go
cmd/power_user.go

add podman scheme to doc examples

---

internal/formats/spdx22json/to_format_model.go
internal/formats/spdx22json/to_format_model_test.go

Reported as https://github.com/anchore/grype/issues/655 with file metadata cataloger enabled, Syft is generating invalid SPDX documents

Correct SPDX-JSON checksum algorithm

---

cmd/attest.go
cmd/output_writer.go
cmd/packages.go
cmd/power_user.go
internal/config/application.go
internal/config/application_test.go
internal/config/attest.go
internal/config/logging.go
syft/sbom/multi_writer.go
syft/sbom/multi_writer_test.go
test/cli/packages_cmd_test.go
test/cli/trait_assertions_test.go

This PR makes a few fixes:
- only closes the `sbom.Writer` when there are errors opening files (I missed an `if` statement on the port)
- perform tilde-expansion for any user-provided paths in the application config
- add CLI tests that assert the content for files created with `-o` and `--file` options 
Closes #874

Fix file creation for output options

---

internal/constants.go
internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
schema/json/schema-3.1.0.json
syft/pkg/rpmdb_metadata.go

Today the jsonschema denotes that epoch is not optional --this is not correct. An epoch of 0 does not necessarily mean the same thing as no epoch, which is why the RPM Metadata carefully tracks `*int` for this field. This PR adjusts the json schema to match reality, allowing nullable values for the `epoch` field within the `RpmdbMetadata` definition. This has some questions on historical data access so the `revision` was bumped over the `addition` field.
Additionally, since last this schema was generated NPM package JSON now additionally captures name and version, however, since additional values are allowed this is not a breaking change.
Diff from the old schema to the new schema provided here for review convenience:
```diff
546a547,548
>         "name",
>         "version",
553a556,561 …
```

RPM Epoch should be optional in the json schema

---

go.mod
go.sum

We want to keep our indirect dependencies in line with current releases so we can be sure syft is not showing up on vulnerability reports.
This bump from `v1.3.1` => `v1.4.1` gets us in line with the latest vault release.

Upgrade vault api from v1.3.1 to v1.4.1

---

.github/scripts/apple-signing/notarize.sh

Release is failing due to invalid brew formula. Instead, directly install `gon`.

Brew install gon failed

---

syft/pkg/cataloger/common/cpe/java.go

We have a number of packages which don't have a pom included in them, but where it can be determined from the MANIFEST logic. However, the groupId in this case starts from the top-level domain "be".
Therefore, proposal to extend the list of domains with the "be" domain.
Or maybe some more extensive list with local top-level domains?

Support of the be (Belgium) top-level domain for the Java Packager

---

go.mod
go.sum
syft/pkg/dpkg_metadata_test.go
syft/pkg/npm_package_json_metadata_test.go
syft/pkg/python_package_metadata_test.go
syft/pkg/url.go

Signed-off-by: houdini91 <mdstrauss91@gmail.com>
Seems that when running on a directory target the NPM purls does not split the namespace correctly.
For example a npm package `@aws-sdk/credential-provider-ini` version 3.41.0
**Dir target:**
PURL = pkg:npm/@aws-sdk%2Fcredential-provider-ini@3.41.0
**Image target**
PURL = pkg:npm/@aws-sdk/credential-provider-ini@3.41.0
Ps: i also think the `@` included in namespace or name be encoded (%40) if i am not mistaken.

Npm purl namespace decode error on dir target

---

internal/formats/common/cyclonedxhelpers/decoder.go
internal/formats/common/cyclonedxhelpers/decoder_test.go

There is a case where a community member is merging Syft-generated CycloneDX SBOMs using `cyclonedx-cli`, which results in a missing `metadata.component`, causing a panic.

Fix panic when CycloneDX BOM missing metadata.component

---

internal/formats/common/cyclonedxhelpers/decoder_test.go
internal/formats/common/cyclonedxhelpers/licenses.go

Working through more CycloneDX decoding issues, another nil pointer dereference was identified.

Fix CycloneDX license decoding

---

internal/formats/syftjson/model/package.go
internal/formats/syftjson/model/package_test.go

Add case where `pkg.GolangBinMetadataType` can be accounted for during `syftjson` model package unmarshal. See screenshot before after where a warning was firing because this case was not accounted for:
After shows the fix:
Before:
After:
TODO:

add case to decode BinMetadata

---

internal/formats/syftjson/model/package.go
internal/formats/syftjson/model/package_test.go
internal/formats/syftjson/to_syft_model.go
internal/formats/syftjson/to_syft_model_test.go

During Syft JSON decoding, an ID is not being set by calling `pkg.SetID()`, however this may differ from the ID in the file. To fix this, we use the same semantics to call `SetID` but also track aliases where these IDs have changed in order to properly decode relationships.
This corrects the issue where users importing Syft JSON see warnings such as:
```
WARN found package with empty ID while adding to the catalog: Pkg(name="Django" version="3.2.12" type="python" id="") from-lib=syft
WARN found package with empty ID while adding to the catalog: Pkg(name="HikariCP" version="2.5.1" type="java-archive" id="") from-lib=syft
...
```

Correct ID handling during syftjson decoding

---

go.mod
go.sum

Fixes a panic when cleaning up a `nil` image (see https://github.com/anchore/stereoscope/pull/113 for more details)

Fix image cleanup when there is an error

---

go.mod
go.sum

Today when fetching images from the docker daemon, we rely on the default behavior from the API client and some extra behavior implemented in stereoscope. With https://github.com/anchore/stereoscope/pull/114 now stereoscope attempts to use the docker config as a starting point for creating the docker API client used for interacting with the docker daemon. This means that now syft can respond to the current docker context configured, among other functionalities that the docker config provides. This PR bumps stereoscope to pull in this enhancement.

Improve docker config support

---

syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/scan_bin.go

Less verbose logging in Golang Cataloger

---

go.mod
go.sum

Rolls back https://github.com/anchore/stereoscope/pull/114 (via https://github.com/anchore/stereoscope/pull/117). See the stereoscope PR for details.

Rollback referencing docker config items

---

go.mod
go.sum

Pull in fix from https://github.com/scylladb/go-set/commit/cc7b2070d91ebf40d233207b633e28f5bd8f03a5 to prevent compile issues on 32 bit architectures:
```bash
$ GOOS=linux GOARCH=386 go build  ...
../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/scylladb/go-set@v1.0.2/strset/strset.go:248:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
../../.gvm/pkgsets/go1.18/global/pkg/mod/github.com/scylladb/go-set@v1.0.2/strset/strset.go:255:16: math.MaxInt64 (untyped int constant 9223372036854775807) overflows int
$ go get -d github.com/scylladb/go-set@master
go: downloading github.com/scylladb/go-set v1.0.3-0.20200225121959-cc7b2070d91e
go: upgraded github.com/scylladb/go-set v1.0.2 => v1.0.3-0.20200225121959-cc7b2070d91e
$ …
```

bump strset version to fix 386 builds

---

internal/formats/common/spdxhelpers/to_syft_model.go
syft/formats_test.go
syft/sbom/format.go

In this PR:
1. I added a failing test that loops through all `formats` used by the `syft` package to ensure that no formats panic when trying to decode or validate an empty SBOM.
2. I fixed the failing test by adding a `nil` check to the SPDX document processing logic.
Additionally, for convenience, I implemented `fmt.Stringer` on the `format.ID` type for use in string descriptions of format operations. This can be undone if needed!
This prevents the panic shown in https://github.com/anchore/grype/issues/693, but a separate Grype PR will catch the "empty SBOM" case even earlier to provide a more direct error message to the user. So this PR isn't strictly necessary with regard to https://github.com/anchore/grype/issues/693, but it still fixes a panic case for the Syft library.

Fix panic on empty sbom

---

README.md

Fixes #913 by highlighting list of supported ecosystems in a new dedicated section.
Makes other various improvements to README:
- Removes references to `syft packages` per the impending deprecation of the `packages` subcommand
- Fixes extra/missing punctuation and whitespaces
- Adjusts a few explanations in attempt to clarify meaning

Fixups and clarifications in README

---

syft/source/directory_resolver.go
syft/source/directory_resolver_test.go

This PR:
- Fixes #872 by checking for a `nil` value before dereferencing an instance of `os.FileInfo`
- Writes a test to prove the panic is fixed
- Moves the check for a pre-existing path index earlier in execution per a discussion w/ @wagoodman 
**Thought for the future:** It'd be nice to see the `directoryResolver` depend on an `io.FS`-style abstraction of the filesystem, rather than directly on queries directly about the local filesystem via the standard library's `os` package. This would make it easier to write certain kinds of tests, specifically when there's a unique scenario like abnormal file permissions. This would also open the door to more exhaustive testing with fuzzing down the road.

Fix nil pointer dereference in directory resolver's `indexPath` method

---

go.mod
go.sum

Bumps stereoscope to pull in the recent fix from https://github.com/anchore/stereoscope/pull/120

Pull from DockerHub fails for public images when using SSO

---

syft/pkg/cataloger/java/save_archive_to_tmp.go

`path.Base()` returns the entire input path if operating system is Windows.
this is resolved by using `filepath.Base()` instead.
using `path.Base()` produces multiple instances of "Path could not be found", due to the fact that the temporary directory:
`archivePath := filepath.Join(tempDir, "archive-"+name)`
is faulty, `name` contains the entire path of the input archive instead of the base name.
switching to using `filepath.Base()` resolves this issue by return the correct base name for the package.
An issue with symlinks still remains however.
It also seems like `path.Base()` and other functions from `path` are bein used in multiple places.
I unfortunately don't know enough about Go to know if these also should be changed in favor of `filepath`.

use filepath.Base() instead of path.Base() for temp files

---

.goreleaser.yaml

Allows for users to be able to `docker pull ghcr.io/anchore/syft:latest`.

Additionally publish docker images to GHCR

---

go.mod
go.sum

Fixes #936 
See https://github.com/anchore/stereoscope/pull/122 for the specific fix in stereoscope

Retry auth URL lookup without docker credentialhelper workaround

---

.github/scripts/apple-signing/setup-prod.sh
.github/workflows/release.yaml

The last release failed with:
```
⨯ release failed after 1192.75s error=docker images: failed to publish artifacts: failed to push ghcr.io/anchore/syft:latest: exit status 1: The push refers to repository [ghcr.io/anchore/syft]
```
This PR addresses the gap by:
- adding GHCR creds specifically for release
- explicitly running `docker login` for ghcr.io
- enabling package write permissions for the release job

Update write permissions and log into ghcr.io for release

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

The Official CPE dictionary currently contains entries for springframework with three different vendors: `springsource`, `pivotal_software`, and `vmware`.  This appears to be because ownership has changed over time.

add additional vendors for springframework

---

internal/formats/spdx22json/to_format_model.go

When doing validation against SPDXJSON2.2 an error would be thrown saying `sha1` was not a valid algorithm.
This change updates the encoding for `spdx22json` so that algorithm is now uppercased according to the specification.
https://spdx.dev/wp-content/uploads/sites/41/2020/08/SPDX-specification-2-2.pdf
See page 35 Package checksum 3.10.4

Update spdx22json to only take uppercase checksum algorithm

---

README.md

There have been some recent changes such that the preferred names for the respective formats are `cyclonedx-xml` and `spdx-tag-value`, which matches what is displayed in `syft --help`. Also CycloneDX has been updated to 1.4.

Minor readme update to correct format information

---

.github/workflows/update-stereoscope-release.yml

This PR adds a nightly check for updates to stereoscope and automatically creates a PR if there has been something merged to main that has not been updated in Syft.

Add workflow for automatic PR for new stereoscope updates

---

internal/formats/common/spdxhelpers/spdxid.go
internal/formats/common/spdxhelpers/spdxid_test.go
internal/formats/spdx22json/model/element_id.go
internal/formats/spdx22tagvalue/encoder_test.go
internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXJSONSPDXIDs.golden
internal/formats/spdx22tagvalue/to_format_model.go

SPDXIDs were being generated with in valid characters. According to the spec, these must be the format:
> "SPDXRef-"[idstring] where [idstring] is a unique string containing letters, numbers, ., and/or -
However, other characters were being included like underscores and forward slashes, this replaces them all with a dash. This should be safe to do without conflicts because our package IDs include the unique hash at the end.
This fixes: #949 and #952

Ensure SPDXIDs are valid

---

internal/formats/github/encoder.go
internal/formats/github/encoder_test.go
internal/formats/github/github_dependency_api.go

The GitHub dependency snapshot format has a couple updates encompassed here: changing the `purl` field to `package_url`, `detector.name` is required (but we are already providing that as `syft`), and `job.name` has been deprecated in favor of `job.correlator`. The latter will be filled out by the `sbom-action`, as it requires action run information.

Update GitHub format package_url and correlator

---

internal/formats/syftjson/to_syft_model.go
syft/pkg/package.go

Today we derive package IDs from the contents of the package itself after cataloging packages. The same has historically applied to IDs from decoded SBOMs, where we recreate the ID from the contents of all of the package info. This PR changes this behavior, allowing the decode path to set an ID on a package, thus honoring the ID from the original SBOM document, allowing external references to still remain valid for downstream processing (e.g. in grype, so the SBOM IDs will always match the package IDs in grype output).
Implementation note: I've left the ID aliasing logic in since it does not affect the correctness of the answer and there is a change this mechanism may be useful in the future if we want this behavior to be configurable (TBD).

Preserve syft IDs on SBOM decode

---

cmd/syft/cli/attest.go
cmd/syft/cli/commands.go

Add back version info to `INFO` level logs and remove double call to config debug in attest

add version info and remove double config call

---

internal/config/application.go
syft/source/directory_resolver.go

This PR dials down the severity of log entries that tend to be hit during common scanning scenarios.
For example, during any project (directory) scans on my macOS machine, I see these log entries every time:
```console
[0008]  WARN directory resolver unable to evaluate symlink for path="/etc/os-release" : lstat /Users/dan/Source/grype-vscode/etc: no such file or directory
[0008]  WARN directory resolver unable to evaluate symlink for path="/usr/lib/os-release" : lstat /Users/dan/Source/grype-vscode/usr: no such file or directory
[0008]  WARN directory resolver unable to evaluate symlink for path="/etc/system-release-cpe" : lstat /Users/dan/Source/grype-vscode/etc: no such file or directory
[0008]  WARN directory resolver unable to evaluate symlink for path="/etc/redhat-release" : lstat …
```

reduce noise of log output

---

syft/pkg/cataloger/golang/scan_bin.go

This is intended to be a temporary fix to the problem of excessive `WARN` logging when the Go binary cataloger encounters a non-Go binary.
Examples of noisy logging:
```console
[0011]  WARN golang cataloger: failed to read buildinfo (file="/usr/lib/python3.9/site-packages/orjson.libs/libgcc_s-eedded4b.so.1"): EOF
```
```console
[0012]  WARN golang cataloger: failed to read buildinfo (file=".vscode-test/vscode-1.48.1/Visual Studio Code.app/Contents/Resources/app/out/vs/platform/files/node/watcher/win32/CodeHelper.exe"): unrecognized file format
```
It should be noted that this change reduces the prominence of legitimate issues parsing real Go binaries. But from my experience, those cases seem to be in the minority, and what's been happening more often is that we're hitting non-Go binaries …

reduce logging severity for non-Go binaries

---

README.md
syft/formats.go
syft/formats_test.go

This PR fixes the following problem in Syft 0.44.1:
```
$ syft packages . -o github-json
1 error occurred:
* bad output format: 'github-json'
```

Fix `github-json` output option

---

syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/parse_go_bin_test.go

https://github.com/anchore/syft/pull/981 overwrites the main version, which doesn't follow Syft's design philosophy of reading data fields as they are. It just so happens that we know the version and it is a constant.
This PR fixes that behavior by reading the main module version as provided by go's BuildInfo.
Signed-off-by: Jonas Xavier <jonasx@anchore.com>

golang cataloger - main module version as is

---

cmd/syft/cli/attest/attest.go
cmd/syft/cli/packages/packages.go
cmd/syft/cli/poweruser/poweruser.go
test/cli/power_user_cmd_test.go
test/cli/trait_assertions_test.go
test/cli/utils_test.go

I hastily merged #989 to try to work around a test timeout issue we've been seeing, but it did not seem to entirely solve the problem - only somewhat reduce it. This PR reverts those changes (which you could [compare to d2d532f](https://github.com/anchore/syft/compare/d2d532f4a852067c9ccba2329a8105ac5479e2ae...kzantow-anchore:root-cause-analysis-of-test-timeouts#diff-d71da09dda3dcb00b18044c8915e29aefc4ef51518792b7ce084924940e0f6cb) to see a more "accurate" diff of this PR) and instead adds a timeout that calls `cmd.Process.Signal(syscall.SIGABRT)`, which kills the process but ALSO includes a stack trace, so it is possible to determine where a CLI call is actually hung. It also adds a retry for these failed calls, which adds `-vv` to attempt to get more information. It was also identified …

Fix potential race condition during event subscription

---

internal/formats/common/cyclonedxhelpers/external_references.go
test/cli/cyclonedx_valid_test.go
test/cli/utils_test.go

Syft currently has a way to validate generated SBOM against the CycloneDX v1.4 schema. This functionality can be found at `syft/schema/cyclonedx`. This check is manual at the moment and runs against `ubuntu:latest`. The image `ubuntu:latest` does not exercise the whole CycloneDX schema for validation. 
This PR adds a test that is run during the CLI checks that leverages [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli) to validate results. 

add integration tests for validating CycloneDX output using cyclonedx-cli

---

syft/pkg/cataloger/javascript/parse_package_json.go
syft/pkg/cataloger/javascript/parse_package_json_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-malformed-license.json

PR includes small fix to the npm cataloger -
**Bug**: Packages with unstandard `licenses` field are dropped.
**Root**: Package json structure unmarshaling error.
```
if err := dec.Decode(&p); err == io.EOF {
break
} else if err != nil {
return nil, nil, fmt.Errorf("failed to parse package.json file: %w", err)
}
```
**Suggestion**: Unmarshal `licences` field in raw bytes and unmarshal it sepritly so that the package still gets added to the resulted sbom.
Signed-off-by: houdini91 <mdstrauss91@gmail.com>

Malformed licenses field in package json warn not skip

---

syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/go.go
syft/pkg/cataloger/common/cpe/go_test.go

This PR changes how CPEs are generated for golang modules, now their full path is used, and this is useful to avoid false positives as it happened with: https://github.com/anchore/grype/issues/676
Testing this change in grype, and using grype to analyze itself, the new report is:
```
$ go mod edit -replace github.com/anchore/syft=../syft
$ go run . (which grype) -v
NAME                        INSTALLED  FIXED-IN  TYPE       VULNERABILITY   SEVERITY
google.golang.org/protobuf  v1.28.0              go-module  CVE-2015-5237   High
google.golang.org/protobuf  v1.28.0              go-module  CVE-2021-22570  High
```
As compared with Grype's code from [April 21](https://github.com/anchore/grype/commit/523f5ce9c0b7362fbb0891ed5749d172285e4220):
```
NAME                            INSTALLED …
```

Longer CPEs for golang modules to avoid false positives

---

internal/formats/common/cyclonedxhelpers/decoder.go
internal/formats/common/cyclonedxhelpers/decoder_test.go

Add check for empty components in `toSyftFormat` method to catch potential panic
fixes https://github.com/anchore/syft/issues/1014

fix: add component list to prevent cyclone-dx panic

---

.goreleaser.yaml

In cases where a draft is released and not published, users will encounter brew install issues along with other friction regarding the new release.
Bumping this to just cut a release with note/artifact edits being done after the fact will reduce this friction.

change draft to false for release process

---

internal/constants.go
internal/formats/spdx22tagvalue/test-fixtures/snapshot/TestSPDXJSONSPDXIDs.golden
internal/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
internal/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
internal/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
schema/json/schema-3.2.4.json
syft/pkg/cataloger/golang/parse_go_bin.go
syft/pkg/cataloger/golang/parse_go_bin_test.go
syft/pkg/golang_bin_metadata.go

This PR adds `mainModule` to Go binary metadata implementing [Dan's suggestion](https://github.com/anchore/syft/issues/908): all golang packages will get a `mainModule`, including the main module itself (where `name` == `metadata.mainModule`).
JSON output schema was updated to `3.2.4`. Minor version bump because of new field added to golang's metadata.
Closes: https://github.com/anchore/syft/issues/908
Signed-off-by: Jonas Xavier <jonasx@anchore.com>

add main module field to go bin metadata

---

syft/pkg/cataloger/deb/cataloger_test.go
syft/pkg/cataloger/deb/parse_dpkg_status_test.go
syft/pkg/dpkg_metadata.go

There are a number of fields that might appear in the status file for a Debian package. This PR adds the `Description` field to the set of fields parsed when cataloging Debian operating systems. This change does not include the addition of this field in any of the SBOM output formats (as far as I can tell), and is initially meant for consumption via library users taking advantage of Syft's package cataloging features. I'm not sure whether it makes sense to include it in SBOM output in the future. I don't specifically have a need for it, but I would like to see it parsed and returned within the `sbom.SBOM` object.

Read Description from dpkg status files

---

syft/pkg/language.go
syft/pkg/language_test.go

Getting a syft Language struct by string name wasn't working as expected for rust, ruby, or dart, so this fixes that and adds unit tests for the `LanguageByName` function.

improve LanguageByName and add unit tests

---

.github/workflows/issues.yaml
.github/workflows/pr.yaml

Add new workflow files that add PR and Issues automatically on open to the OSS anchore project.
Uses: https://github.com/actions/add-to-project 

add workflows to test new project automation

---

internal/file/test-fixtures/generate-zip-fixture-from-source-dir.sh
internal/file/zip_file_helpers_test.go
internal/file/zip_file_manifest_test.go
internal/file/zip_file_traversal_test.go
internal/file/zip_read_closer.go

Syft currently throws a warning when scanning [`zip64`](https://www.artpol-software.com/ZipArchive/KB/0610051629.aspx) files.
This update adds new patches sourced from the golang standard library. 
When v1.19 launches in August the syft project should be able to remove most of this code and use the newly added prefix support seen in this CL.
https://go-review.googlesource.com/c/go/+/387976/3/src/archive/zip/reader.go#544
With the new update you can see the warning is no longer thrown:

update zip_read_closer to incorporate zip64 support

---

go.mod
go.sum

Resolves: [CVE-2022-31030](https://github.com/advisories/GHSA-5ffw-gxpp-mxpf)

update stereoscope to latest version

---

syft/pkg/cataloger/rpmdb/cataloger.go
syft/pkg/cataloger/rpmdb/parse_rpmdb.go
syft/pkg/cataloger/rpmdb/parse_rpmmanifest.go
syft/pkg/cataloger/rpmdb/parse_rpmmanifest_test.go
syft/pkg/cataloger/rpmdb/test-fixtures/container-manifest-2
syft/pkg/cataloger/rpmdb/test-fixtures/generate-fixture.sh
syft/pkg/rpmdb_metadata.go
test/integration/mariner_distroless_test.go
test/integration/test-fixtures/image-mariner-distroless/Dockerfile

Fixes https://github.com/anchore/syft/issues/1044
Mariner distroless images don't contain an RPM database, but contain a file containing the
output of an `rpm --query --all ...` command: https://github.com/microsoft/CBL-Mariner/blob/main/toolkit/docs/how_it_works/5_misc.md#rpm-manifest-file
This PR adds support to syft for detecting that file and extracting package information from it. This is not as much information as syft extracts from a normal RPM database (a couple of examples being file information and signing algorithm) but it is enough information for subsequent CVE analysis.

Add support for CBL-Mariner distroless images

---

syft/lib.go
syft/pkg/cataloger/cataloger.go

Add a new switch `--use-all-catalogers` that allows for the use of both image and file catalogers to run on the subject. This is useful when scanning an image built to use as a build environment, where artifacts may be installed using the files present soon.
Closes https://github.com/anchore/syft/issues/1049

feat: add use-all-catalogers flag

---

syft/pkg/cataloger/cataloger.go

Add's the php catalogers to be used in the case of scanning a file or using all catalogers.
Closes: https://github.com/anchore/syft/issues/1064

fix: add php catalogers to all catalogers

---

syft/pkg/language.go
syft/pkg/language_test.go

In the complete list of all cpes ever found, `node.js` and `nodejs` appear as target software. I'm working on making a PR to Grype which checks if a target_sw is supported by Syft, so I'd like to add these so they map to Javascript as the supported base

fix: add new languages found in cpes

---

cmd/syft/cli/options/writer.go
cmd/syft/cli/options/writer_test.go

Updates the `-o` option for packages to list all the possible options when failing and formats the error response to be in sync with Grype.
Closes https://github.com/anchore/syft/issues/1101

fix: -o output option to include formats

---

go.mod
go.sum

This PR bumps go-rustaudit to support rust-audit 0.2.0.
Context:
The addition of a Rust-audit cataloger in https://github.com/anchore/syft/pull/1116 triggered some updates to rust-audit itself, geared around making it easier for users to produce binaries with dependency information in. As part of that, the section name was changed to be consistent across platforms, so this bump is required to support rust-audit 0.2.0. Apologies for the churn.
cc @spiffcs

Bump go-rustaudit to support rustaudit 0.2.0

---

.github/workflows/release.yaml

Looks like only v1 conforms to having a prefixed v.
```
Getting action download info
Error: Unable to resolve action `docker-practice/actions-setup-docker@v1.0.8`, unable to find version `v1.0.8`
```

remove prefixed v from tag to match release

---

.goreleaser_docker.yaml

Removes the error `error=missing GITHUB_TOKEN, GITLAB_TOKEN and GITEA_TOKEN`
Since we're not using the release object for the second docker publish we need to explicitly disable that feature or goreleaser will fail expecting this environment variable to be present.
https://github.com/goreleaser/goreleaser/issues/669

disable release for docker assets

---

.github/workflows/release.yaml
go.mod
go.sum

This PR updates to the latest stereoscope, which no longer requires the replace directive to use the `sylabs` fork of `squashfs`.

Update stereoscope to get rid of the replace directive

---

README.md
syft/lib.go
syft/pkg/cataloger/rust/audit_binary_cataloger.go
syft/pkg/cataloger/rust/cataloger.go
test/cli/packages_cmd_test.go
test/integration/catalog_packages_test.go
test/integration/convert_test.go
test/integration/distro_test.go
test/integration/encode_decode_cycle_test.go
test/integration/mariner_distroless_test.go
test/integration/package_deduplication_test.go
test/integration/package_ownership_relationship_test.go
test/integration/regression_apk_scanner_buffer_size_test.go
test/integration/regression_go_bin_scanner_arch_test.go
test/integration/regression_java_no_main_package_test.go
test/integration/rust_audit_binary_test.go
test/integration/sqlite_rpmdb_test.go
test/integration/utils_test.go

If the user specifies catalogers via configuration, then use the
requested catalogers regardless of source type.
This makes it possible to enable an off-by-default cataloger on an image or directory without
using "--all" catalogers.
Signed-off-by: Tom Fay <tomfay@microsoft.com>
Fixes https://github.com/anchore/syft/issues/1141

cataloger configuration is respected regardless of source

---

internal/formats/syftjson/model/package.go
internal/formats/syftjson/model/package_test.go

When decoding an SBOM that has a package entry with no metadata type a warning is given:
```
[0000]  WARN unknown package metadata type="" for packageID="fc0265ef2c7b8e50" from-lib=syft
```
This is not correct since there are multiple package types that may not have metadata. This PR changes the behavior to ignore this case explicitly.

Empty metadata while decoding should be allowed

---

internal/formats/spdx22json/to_format_model.go
internal/formats/spdx22json/to_format_model_test.go

Heya :wave: Have been playing around with Syft recently, and came across some odd behavior! It looks like the `hasFiles` field isn't populating correctly, despite the relationships being in-place as expected, and there being logic to extract for this field.
Previously, extracting relationships between packages and files was not completing correctly, as SPDXRef- ElementIDs were being compared to raw IDs, and so never matched. This PR fixes this behavior, by ensuring that we always compare
ElementIDs.
I think the original behavior was introduced in https://github.com/anchore/syft/pull/634, and while the unit tests pass, I can't find any integration tests that check the behavior - but would be happy to add one, if you have any pointers on where might be the best place! :tada:
Let me know if …

Correctly populate hasFiles field for spdx-json output

---

syft/pkg/cataloger/catalog.go

As symlinks are traversed as part of file resolution, a scenario in which a package owns a file and its respective symlinks, causes multiple relationships to be created between the package and the file (as the symlinks do not appear in the list of files in the output). This seems to have been introduced in #782.
For example, see the following scan of an alpine image that contains the `libz` package:
```json
...
{
"SPDXID": "SPDXRef-5baca92b12b31c62",
"name": "zlib",
"licenseConcluded": "Zlib",
"description": "A compression/decompression Library",
"downloadLocation": "https://zlib.net/",
"externalRefs": [
{
"referenceCategory": "SECURITY",
"referenceLocator": "cpe:2.3:a:zlib:zlib:1.2.12-r3:*:*:*:*:*:*:*",
"referenceType": "cpe23Type"
},
{
"referenceCategory": "PACKAGE_MANAGER", …
```

Prevent symlinks causing duplicate package-file relationships

---

syft/pkg/cataloger/javascript/cataloger.go
syft/pkg/cataloger/javascript/parse_pnpm_lock.go
syft/pkg/cataloger/javascript/parse_pnpm_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pnpm/pnpm-lock.yaml

Adds support for `pnpm` lockfiles
Closes https://github.com/anchore/syft/issues/1165

feat: add support for pnpm

---

cmd/syft/cli/options/packages.go
internal/config/application.go
internal/config/datasources.go
syft/pkg/cataloger/alpm/cataloger.go
syft/pkg/cataloger/cataloger.go
syft/pkg/cataloger/cataloger_test.go
syft/pkg/cataloger/common/generic_cataloger.go
syft/pkg/cataloger/config.go
syft/pkg/cataloger/deb/cataloger.go
syft/pkg/cataloger/golang/binary_cataloger.go
syft/pkg/cataloger/portage/cataloger.go
syft/pkg/cataloger/python/package_cataloger.go
syft/pkg/cataloger/rpmdb/cataloger.go
syft/pkg/cataloger/rust/audit_binary_cataloger.go

The use of external sources is new to Syft, and they must be managed thoughtfully (i.e. configurability, clear to users what has been used and how). This PR proposes a way to do so. It is motivated by https://github.com/anchore/syft/issues/1159 and https://github.com/anchore/syft/issues/1115. 
It adds a new external sources configuration, an additional function that catalogers must implement, and a cli flag to shut off the use of external sources. This approach assumes that external sources will only come into Syft through catalogers. 
When catalogers are implemented that use external sources, they must add their own configuration options to the application-wide external sources configuration created here.

External sources configuration

---

syft/pkg/cataloger/javascript/cataloger.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/parse_package_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/package-lock-2.json

Adds support for licenses discovery for `package-lock.json` v2 files
Closes https://github.com/anchore/syft/issues/1153

feat: add support for licenses in package-lock json v2

---

.github/workflows/update-bootstrap-tools.yml
Makefile

workflow to create automated PRs to update bootstrap tools

---

syft/pkg/cataloger/java/archive_filename.go
syft/pkg/cataloger/java/archive_filename_test.go

This PR adds support for different JAR naming conventions -- specifically `<name>.<version>` and `<name>_<version>`.
Closes #466

Find version numbers from jars with different naming conventions

---

internal/formats/common/spdxhelpers/to_syft_model.go
syft/pkg/cataloger/rpmdb/parse_rpmdb.go
syft/pkg/cataloger/rpmdb/parse_rpmdb_test.go

This PR corrects handling of licenses with RPM DB parsing by including licenses in the `Package.Licenses`.
Fixes #660

Fix RPM DB license handling

---

README.md
cmd/syft/cli/eventloop/tasks.go
internal/config/application.go
internal/config/rekor_cataloger.go
internal/formats/spdx22json/to_format_model.go
syft/file/rekor_cataloger.go
syft/pkg/cataloger/cataloger.go
syft/rekor/query.go
syft/rekor/rekor.go
syft/rekor/utils.go
syft/rekor/utils_test.go
syft/rekor/verify.go
test/integration/rekor_cataloger_test.go
test/integration/utils_test.go

This PR, to `kubecon-draft`, addresses many of the comments from the original PR for [SBOM discovery with Rekor](https://github.com/anchore/syft/pull/1157). 
One of the bigger changes is returning a `subject` and `sbomEntry` from `parseAndValidateAttestation` instead of a `InTotoAttestation`. This is to reduce the amount of validations that are needed in the code. 
Another change is adding a configuration for `rekor-cataloger`. As the cataloger is off-by-default, the following must be specified in a configuration file:
```yaml
rekor-cataloger:
cataloger:
enabled: true
``` 
To avoid this, a CLI flag specifically for the rekor-cataloger could be added. Alternatively, a more general CLI flag that filters the file catalogers or the non-package catalogers could be implemented, similar to the …

improvements to rekor cataloger code

---

internal/formats/syftjson/to_format_model.go
syft/pkg/catalog.go
syft/pkg/relationships_by_file_ownership.go

There are numerous places within syft where a map is iterated over to create a list. Since map iteration is non-deterministic, the order of items within the list is also non-deterministic. While this doesn't impact the semantic meaning of the output, it makes it harder to compare the output of two independent runs of syft.
```sh
syft ghcr.io/jenkins-x/jx-scm -o syft-json > a.json
syft ghcr.io/jenkins-x/jx-scm -o syft-json > b.json
diff a.json b.json
```
Without this PR there is a diff, with this PR the diff is empty.
This PR is a band-aid to address the most common sources of drift. There are certainly other sources that are not addressed.
Related #331 #292
Signed-off-by: Scott Andrews <andrewssc@vmware.com>

Normalize syft-json output

---

syft/pkg/cataloger/rpm/parse_rpmdb.go

Today if there are any issues when parsing an RPM DB entry the cataloging process halts. This is not consistent with other catalogers which instead log warnings when there are parsing errors and cataloging continues. This PR removes the error paths during execution and adds warnings instead.

Warn on errors from RPM DB parsing

---

.golangci.yaml
cmd/syft/cli/packages/packages.go
syft/file/classifier.go
syft/file/secrets_cataloger.go
syft/file/secrets_search_by_line_strategy.go
syft/pkg/cataloger/golang/internal/xcoff/file.go
syft/pkg/cataloger/golang/internal/xcoff/xcoff.go
syft/pkg/cataloger/java/save_archive_to_tmp.go
syft/pkg/cataloger/python/package_cataloger.go
syft/pkg/cataloger/rpm/parse_rpmdb.go
syft/pkg/cataloger/swift/parse_podfile_lock.go

Syft's `DEVELOPING.md` instructs the user to boostrap tools and run `make`
The default make step has a couple of errors when running out of the box.
The first is `make lint`:
These errors are correct by changing the directives at the top of these files to the newer `nolint:all`
The second is where `io/util` is considered deprecated in the latest Golang release. These instances have been updated to their latest `os` or `io` equivlants.
Abandoned linters have also been disabled per the warnings from the `golangci` tool:
- remove deprecated linters that have been abandoned
- replace usage of ioutil => io/os upgrades
- update std library copied files to new lint directive
- updating developer.md with better flow diagrams, explanation of what default  `make` does, and shorter introduction …

refactor: replace ioutil=>io; update linter

---

DEVELOPING.md
Makefile

- update Makefile variable organization
- make DEFAULT_GOAL:=help for Makefile
- update Makefile self-documentation
- update DEVELOPING.md instruction

refactor: update Makefile organization; update DEVELOPING.md instructions

---

cmd/syft/cli/attest/attest.go
test/cli/attest_cmd_test.go

Closes #1210 
Given a user could provide a typo value for their desired output, the `format` value in attest had a chance to be `nil`.
This PR adds a guard against `FormatByName` returning nil by adding a default format attestation path as `syft-json`.
Another option is we could error out and inform the user that their format is unrecognized rather than providing a default. I'm open to either approach but chose to try and provide a successful command rather than error case in this instance.
A CLI test has been added to cover this typo case.

bug: remove chance for panic; provide default attestation path

---

syft/source/source.go
syft/source/source_test.go
syft/source/source_win_test.go

This PR fixes `--exclude` patterns on Windows along with adding some additional testing. However, since we are not utilizing any Windows runners, the test will not run as part of CI currently, so there is an approximation of it that runs on Linux.
Fixes #1024

Support exclude patterns on Windows

---

syft/pkg/cataloger/rpm/file_cataloger.go
syft/pkg/cataloger/rpm/file_cataloger_test.go
syft/pkg/cataloger/rpm/test-fixtures/bad/bad.rpm

This PR allows cataloging to continue if a file with `.rpm` extension is found but unable to be parsed as an RPM file.
Fixes: #1231

Do not fail if unable to parse `.rpm` file

---

syft/pkg/cataloger/cpp/parse_conanlock.go
syft/pkg/cataloger/cpp/test-fixtures/conan.lock

Incorrect data type being used for requires. Was string ==> now slice of string.
`BuildRequires` was also not a part of the conan.lock spec anymore so removing

update requires to use list; remove field

---

syft/source/all_layers_resolver.go
test/integration/all_layers_squashed_comparison_test.go
test/integration/test-fixtures/image-suse-all-layers/Dockerfile

This PR modifies the behavior when using `all-layers` scope such that symlinks from prior layers work properly.
There was an issue reported where a SUSE RPM database was changed but the change was not identified because the symlink did not change and the SUSE location did not match the recognized location for the RPM database. Now, regardless of the layer a symlink is introduced in, it should work as expected to match globs.
Precursor for https://github.com/anchore/grype/issues/894

Follow symlinks when searching for globs in all-layers scope

---

syft/rekor/utils.go
syft/rekor/utils_test.go

For the SBOM discovered via rekor cataloger, it was assumed that the file is SPDX Tag-Value. Added support for SPDX JSON.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Add rekor-cataloger parsing JSON SPDX document

---

cmd/syft/cli/attest/attest.go
go.mod

Add support for `syft attest` with Singularity images. Re-factor the attestation code to separate the steps to generate and publish the signed attestation.
To test, I'm generating a test image with [Singularity](https://github.com/sylabs/singularity), for example:
```sh
$ singularity build alpine.sif docker://alpine
...
```
Then generating a signed attestation with Syft (requires the changes in this PR):
```sh
$ syft attest --output syft-json --key cosign.key singularity:alpine.sif > attestation.json
✔ Parsed image            
✔ Cataloged packages      [14 packages]
```
And finally, to verify the attestation and scan the SBOM with Grype:
```sh
$ grype attestation.json --key cosign.pub
✔ Vulnerability DB        [no update available]
✔ Attestation verified    
✔ Scanned image           [0 …
```

feat: attest support for Singularity images

---

go.mod
syft/source/source.go
syft/source/source_test.go

Allow source.Source struct to set reproducible id for the following scheme:
- DirectoryScheme
- FileScheme
- ImageScheme
- UnknownScheme 
This ID is calculated in the following ways: 
- a digest from the given directory path
- the digest of the file contents or file path 
- the digest of the image manifest 
- if this cannot be found it is calculated as a ChainID: https://github.com/opencontainers/image-spec/blob/main/config.md#layer-chainid
- If the scheme is unknown then the ID is calculated as a Hash of the source struct.
Followups coming in separate smaller PR:

feat: add identifiable field to source object

---

syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

The apkdb checksum digest algorithm is currently misleading. Today we always list `sha1`, however, the apk-tools indicates that two values are possible: `md5` and `sha1`. In the case where the checksum is a `sha1` a `Q1` value is prepended to the base64 representation of the checksum value.
This PR adds the md5 algorithm indication when found and additionally adds more annotations to the `sha1` case to indicate  the value has additional processing.

Fix apkdb checksum representation

---

syft/pkg/catalog.go
syft/pkg/catalog_test.go

The current map access pattern for the catalog returned a package by copy and not by ref.
This PR updates the catalog map after merge so that merged values can be included back into the core catalog.
A test with CPE's has been added to display this behavior pre/post change.

fix: reset merged package into map; 

---

cmd/syft/cli/attest/attest.go
cmd/syft/cli/completion.go
go.mod
go.sum

This addresses Issue #1268
As noted in https://github.com/in-toto/attestation/issues/82#issuecomment-1280759933 it is not clear what the predicate value should really be but this change leaves that question to in-toto and ensures alignment with other tools such as cosign.
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

Use in-toto CycloneDX predicate to be compatible with cosign

---

syft/pkg/apk_metadata.go
syft/pkg/cataloger/apkdb/cataloger.go
syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/package_test.go
syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go
syft/pkg/url_test.go

Follow up to #1281 , porting the APK cataloger to the new `generic.Cataloger`

Port apk cataloger to new generic cataloger pattern

---

syft/pkg/cataloger/dart/cataloger.go
syft/pkg/cataloger/dart/package.go
syft/pkg/cataloger/dart/parse_pubspec_lock.go
syft/pkg/cataloger/dart/parse_pubspec_lock_test.go
syft/pkg/dart_pub_metadata.go
syft/pkg/url_test.go

Follow up to #1281 , porting the Dart cataloger to the new `generic.Cataloger`
~(note: base branch will chain to main once https://github.com/anchore/syft/pull/1284 merges and this is rebased)~

Port dart cataloger to new generic cataloger pattern

---

syft/pkg/cataloger/dotnet/cataloger.go
syft/pkg/cataloger/dotnet/package.go
syft/pkg/cataloger/dotnet/parse_dotnet_deps.go
syft/pkg/cataloger/dotnet/parse_dotnet_deps_test.go
syft/pkg/cataloger/internal/pkgtest/assert_packages_equal.go
syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
syft/pkg/dotnet_deps_metadata.go
syft/pkg/url_test.go

Follow up to #1281 , porting the APK cataloger to the new `generic.Cataloger`
This additionally brings in a new `internal/pkgtest` helper functions to aid in making tests easier to make (if you're using the generic cataloger). I was finding I was making the exact same changes to tests everywhere, and the code was very boilerplate... thus a helper test function makes sense here. I also found that the comparison function I was using wasn't considering all fields of the elements under test, which means there may be issues that are not raised during testing. 
If accepted, I'll head back to the catalogers I just updated and move the pattern forward there as well.

Port dotnet cataloger to new generic cataloger pattern

---

syft/pkg/cataloger/alpm/parse_alpm_db_test.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go
syft/pkg/cataloger/cpp/parse_conanfile_test.go
syft/pkg/cataloger/cpp/parse_conanlock_test.go
syft/pkg/cataloger/dart/parse_pubspec_lock_test.go
syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go

This is a follow up to #1286 to use the new `internal/pkgtest` utils for testing. For consistency I'm also updating `deep` comparison references with `cmp` equivalents. 
_Note: this can't be merged until it is rebased with main_

Update cataloger tests to use pkgtest utils

---

syft/pkg/cataloger/haskell/cataloger.go
syft/pkg/cataloger/haskell/package.go
syft/pkg/cataloger/haskell/parse_cabal_freeze.go
syft/pkg/cataloger/haskell/parse_cabal_freeze_test.go
syft/pkg/cataloger/haskell/parse_stack_lock.go
syft/pkg/cataloger/haskell/parse_stack_lock_test.go
syft/pkg/cataloger/haskell/parse_stack_yaml.go
syft/pkg/cataloger/haskell/parse_stack_yaml_test.go
syft/pkg/hackage_metadata.go
syft/pkg/url_test.go

Follow up to #1281 , porting the hackage (haskell) cataloger to the new `generic.Cataloger`.

Update haskell cataloger to use updated generic cataloger

---

syft/pkg/cataloger/python/package_cataloger.go
syft/pkg/cataloger/python/package_cataloger_test.go
syft/pkg/cataloger/python/parse_wheel_egg_record.go
syft/pkg/cataloger/python/parse_wheel_egg_record_test.go
syft/pkg/cataloger/python/test-fixtures/malformed-record/dist-info/METADATA
syft/pkg/cataloger/python/test-fixtures/malformed-record/dist-info/RECORD

This PR adjusts the python RECORD file processing so it continues parsing for invalid lines and prints warnings instead of failing to parse altogether.
Fixes #1012

fix: Continue parsing Python RECORD files when bad lines encountered

---

README.md

…based on cosign v1.13.1 and syft 0.59.0 usage
I've found that `cosign verify-attestation` defaults to `custom` type; the only pairing of syft and cosign I've found works for me is to use SPDX JSON

docs: update attestation directions with new cosign changes

---

go.mod
go.sum

This fixes an issue which occurred when parsing rpm installed packages when there were multiple `\x00` in the byte slice: https://github.com/knqyf263/go-rpmdb/pull/30

update go-rpmdb to improve parsing of installed files

---

Makefile
syft/pkg/binary_metadata.go

Our old apple signing architecture was still present in some of the Makefile release scripts.
This PR allows the CI flow to not block on the presence of log files that no longer exist.
Users should be able to run `make make snapshot-with-signing` with status code 0 and the build artifacts located in `snaoshot`
For more context on the error and the lines removed to fix this error see this build log:
https://github.com/anchore/syft/actions/runs/3363098999/jobs/5576370179

fix: update Makefile to remove old signing arch

---

Makefile

I checked the idea using the snapshot command
Here is a screenshot of it failing and printing the logs after calling interrupt with dumb redacted values:

fix: verbose quill build failures

---

.github/workflows/release.yaml

This PR updates the release workflow token permissions for goreleaser to be able to publish.

chore: update github token permissions for goreleaser

---

syft/formats/syftjson/model/package.go
syft/formats/syftjson/model/package_test.go

This PR fixes an issue where Syft is not decoding binary metadata properly or retaining future metadata types without updating to the corresponding Syft release.

Decode binary and unknown metadata

---

.github/workflows/release.yaml
.goreleaser.yaml

This PR _should_ correct the brew publishing failure in the new workflow.

chore: update goreleaser brew token

---

.github/workflows/release.yaml

Fixes regression introduced in #1280 , now the release workflow should be able to upload to S3 to update the version file.

Add s3 credentials to release

---

syft/pkg/cataloger/catalog.go

Purl Generation has changed a bit between v0.59.x and v0.60.x
A good example of this can be demonstrated by the following values for alpine:
```
PRE v0.60.x
pkg:alpine/busybox@1.31.1-r19?arch=x86_64&upstream=busybox&distro=alpine-3.12.5
Included in v0.60.x
pkg:alpine/busybox@1.31.1-r19
```
There are two places within syft that can generate two different values for PURL given a certain package type:
Let’s look at the above alpine case:
Here is the first section where a PURL can be set:
https://github.com/anchore/syft/blob/e0acfa98c7ba1e34a0acdbc4b1af69328c310531/syft/pkg/cataloger/apkdb/package.go#L29-L57
This can be found when the "apkdb-cataloger" is running and parsing the apk DB.
Syft gets a second pass at PURL generation here in catalog.go for all packages …

fix: only generate PURL on empty string

---

syft/pkg/cataloger/generic/classifier.go
syft/pkg/cataloger/generic/classifier_test.go
syft/pkg/cataloger/generic/test-fixtures/version.txt

This PR corrects an issue where the node binary cataloger was outputting a CPE without version information.
Before:
```json
"cpes": [
"cpe:2.3:a:nodejs:node.js:*:*:*:*:*:*:*:*",
"cpe:2.3:a:node:node:19.0.0:*:*:*:*:*:*:*",
"cpe:2.3:a:*:node:19.0.0:*:*:*:*:*:*:*"
],
```
After:
```json
"cpes": [
"cpe:2.3:a:nodejs:node.js:19.0.0:*:*:*:*:*:*:*",
"cpe:2.3:a:node:node:19.0.0:*:*:*:*:*:*:*",
"cpe:2.3:a:*:node:19.0.0:*:*:*:*:*:*:*"
],
```

Fix: Include version information in binary cataloger CPEs

---

syft/pkg/cataloger/javascript/parse_node_binary.go

The JavaScript indexer now contains a node binary indexer, but this triggers a nil pointer dereference in my case:
```
github.com/anchore/syft/syft/pkg.(*Package).SetID(0x0)
/home/runner/work/syft/syft/syft/pkg/package.go:42 +0x36
github.com/anchore/syft/syft/pkg/cataloger/javascript.parseNodeBinary({0xc000c78760?, 0xc019612710?}, 0x10?, {{{{0xc001909810, 0xd}, {0xc0069602d0, 0x47}}, {0xc001909810, 0xd}, {0xb1b2, ...}}, ...})
/home/runner/work/syft/syft/syft/pkg/cataloger/javascript/parse_node_binary.go:41 +0x186
github.com/anchore/syft/syft/pkg/cataloger/generic.(*Cataloger).Catalog(0xc01162b6e0, {0x2804a40, 0xc000e800a0})
/home/runner/work/syft/syft/syft/pkg/cataloger/generic/cataloger.go:127 +0x70e
github.com/anchore/syft/syft/pkg/cataloger.Catalog({0x2804a40?, 0xc000e800a0}, 0x8?, …
```

javascript cataloger: node binary: nil pointer dereference

---

syft/pkg/cataloger/php/cataloger.go
syft/pkg/cataloger/php/package.go
syft/pkg/cataloger/php/package_test.go
syft/pkg/cataloger/php/parse_composer_lock.go
syft/pkg/cataloger/php/parse_composer_lock_test.go
syft/pkg/cataloger/php/parse_installed_json.go
syft/pkg/cataloger/php/parse_installed_json_test.go
syft/pkg/url_test.go

Follow up to https://github.com/anchore/syft/pull/1281 , porting the php cataloger to the new generic.Cataloger.

Port php cataloger to new generic cataloger pattern

---

internal/constants.go
schema/json/schema-5.0.0.json
syft/formats/syftjson/format.go
syft/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
syft/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
syft/pkg/cataloger/portage/cataloger.go
syft/pkg/cataloger/portage/cataloger_test.go
syft/pkg/cataloger/portage/purl.go
syft/pkg/cataloger/portage/purl_test.go
syft/pkg/cataloger/portage/test-fixtures/image-portage/Dockerfile
syft/pkg/portage_metadata.go

Follow up to https://github.com/anchore/syft/pull/1281 , porting the php cataloger to the new generic.Cataloger.
I've also removed two unused fields from the portage metadata struct, leading to a json schema change.

Update portage cataloger to new generic cataloger

---

syft/pkg/cataloger/ruby/catalogers.go
syft/pkg/cataloger/ruby/package.go
syft/pkg/cataloger/ruby/package_test.go
syft/pkg/cataloger/ruby/parse_gemfile_lock.go
syft/pkg/cataloger/ruby/parse_gemfile_lock_test.go
syft/pkg/cataloger/ruby/parse_gemspec.go
syft/pkg/cataloger/ruby/parse_gemspec_test.go
syft/pkg/url_test.go

Follow up to https://github.com/anchore/syft/pull/1281 , porting the ruby cataloger to the new generic.Cataloger.

Port ruby cataloger to new generic cataloger pattern

---

internal/constants.go
schema/json/generate.go
schema/json/schema-5.0.1.json
syft/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
syft/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
syft/pkg/cataloger/swift/cataloger.go
syft/pkg/cataloger/swift/package.go
syft/pkg/cataloger/swift/package_test.go
syft/pkg/cataloger/swift/parse_podfile_lock.go
syft/pkg/cataloger/swift/parse_podfile_lock_test.go
syft/pkg/cocoapods_metadata.go
syft/pkg/url_test.go

Follow up to https://github.com/anchore/syft/pull/1281 , porting the swift cataloger to the new generic.Cataloger.
Additionally adds the cocopods metadata to the json schema.

Update swift cataloger to generic cataloger

---

syft/pkg/cataloger/alpm/parse_alpm_db.go
syft/pkg/cataloger/alpm/parse_alpm_db_test.go

Small fix to normalize the `md5digest` references to simply `md5` like with other catalogers that raise up digests with algorithm references.

Normalize alpm md5 refs

---

cmd/syft/cli/attest/attest.go
cmd/syft/cli/options/packages.go
cmd/syft/cli/packages/packages.go
cmd/syft/cli/poweruser/poweruser.go
internal/config/application.go
syft/formats/common/cyclonedxhelpers/format.go
syft/formats/common/spdxhelpers/document_name.go
syft/source/metadata.go
syft/source/source.go
syft/source/source_test.go

A small pain point for me when generating SBOMs is that I want to have fine-grained control over the output, and specifically attempt to cleanup the recorded source from which the SBOM was produced. For example, I might mount a container filesystem to `/mnt` and then scan it - or I might unpack it into the current directory and perform a scan - or I might scan it as part of a build step (and then push an image later to a different production location). For my use case, I'd like that to remain an implementation detail, and not be exposed to the end user - a detail as to where the original path was on my machine isn't relevant to my user, so ideally I'd like to be able to hide those details.
As a (very) naive attempt, I've added a new `--name` flag to the CLI, which is propagated through to …

Add `--name` option to override name in output

---

syft/formats/common/cyclonedxhelpers/format.go
syft/formats/common/cyclonedxhelpers/format_test.go

This PR fixes an issue where invalid CPEs may be output in the CycloneDX OS component.
Fixes: #1337

Output only valid CPEs for CycloneDX OS components

---

syft/linux/identify_release_test.go
syft/linux/test-fixtures/os/wolfi/etc/os-release

Adds a release identification unit test for [Wolfi OS](https://github.com/wolfi-dev/)

chore: add unit test for wolfi os release identification

---

syft/formats/common/cyclonedxhelpers/component_test.go
syft/formats/common/property_encoder.go
syft/formats/syftjson/model/package.go
syft/formats/syftjson/model/package_test.go

This PR corrects an issue where a Syft JSON with a known `metadataType` but missing `metadata` would fail.
Fixes: #1334

Unmarshal Syft JSON with missing metadata

---

syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/parse_package_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/package-lock-3.json

This PR adds support for npm lockfile version 3, which drops the "dependencies" key and uses "packages" instead. I've refactored the lockfile parser to make the distinction between the versions explicit rather than the implicit behaviour before. It _might_ be worth splitting into separate files at some point, but the logic is so minimal that I haven't done it.
Some open questions;
- Does the code look vaguely correct? I don't know Go well at all
- I can't find good documentation around the presence of the "license" key under the "packages" entries. It seems to be present in the v2 fixture, but I couldn't recreate that locally.
- Are there other places that I need to add / update tests?
Fixes #1203

feat: Add support for npm lockfile version 3

---

syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_format_model_test.go
syft/formats/spdxtagvalue/decoder_test.go
syft/formats/spdxtagvalue/test-fixtures/tag-value.spdx

SPDX expects a `ToUpper` checksum algorithm for all package syntax. Previously java would not behave this way and returned `sha1` lowercase causing downstream consumer issues.
- add ToUpper for java packages being converted
- add additional coverage for Golang and niche test cases
- add decoder smoke test with the future notes for developers on e2e conversion coverage

fix: spdx java checksum correctness

---

syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/parse_package_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/alias-package-lock-1.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/alias-package-lock-2.json

Fixes #1314 
This _only_ addresses npm/`package-lock.json` aliases.
Addresses package-lock.json version 1-3. 
the `package.json` that the `package-lock.json`s examples were derived from:
https://gist.github.com/Mikcl/aef4d180f4275b66252dca32b6668375#file-package-json

npm-aliases: handle aliases for package-lock.json

---

syft/formats/formats.go
syft/formats/spdxtagvalue/decoder.go

This PR adds debug logging for decode errors. If a file fails to decode, at least a user is now able to run `syft -vv` to see why all the formats failed, like this:
```
[0000] DEBUG format syft-6-json returned err: unable to decode: invalid character 'S' looking for beginning of value
[0000] DEBUG format cyclonedx-1-xml returned err: EOF
[0000] DEBUG format cyclonedx-1-json returned err: invalid character 'S' looking for beginning of value
[0000] DEBUG format spdx-2-tag-value returned err: unable to decode spdx-tag-value: got unknown checksum type sha256
[0000] DEBUG format spdx-2-json returned err: unable to decode spdx-json: invalid character 'S' looking for beginning of value
2022/11/19 09:34:55 error during command execution: failed to decode SBOM: unable to identify format
``` …

chore: add debug logging for decode errors

---

syft/pkg/cataloger/haskell/parse_cabal_freeze.go
syft/pkg/cataloger/haskell/test-fixtures/cabal.project.freeze

Fixes #1362 
cabal.project.freeze does not generate trailing comma for final packages under `constraints`
This would lead to a `-1` value for `endPkgEncoding` causing a panic when attempting to parse portions of the package `line`
This PR adds protections to set endPkgEncoding to the end of the `line` if -1 is encountered, while also adding a guard against other potential incorrect line parsing states

fix: remove cabal.project.freeze panic on last pkg

---

syft/pkg/cataloger/alpm/parse_alpm_db.go

Attempts to address #1094 - syft would continue to try and resolve file contents when no locations were found for `FilesByPath` causing a panic when trying to access position 0 of an empty slice.
Error message just before panic on windows:
```
DEBUG directory resolver unable to evaluate symlink for 
path="C:\msys64\var\lib\pacman\local\libp11-kit-0.24.1-4\mtree" : 
CreateFile C:\C:: The filename, directory name, or volume label syntax is incorrect.
```
This fix removes the possibility of panic by checking the locations found before `FilesBypath` is called.
It does not address the fact that `C:\msys64\var\lib\pacman\local\libp11-kit-0.24.1-4\mtree` is a valid path that should be able to be parsed. 
Also note: this error will eventually surface to: …

fix: guard for locations < 1 in alpmdb parse

---

syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

This PR is a suggested solution to #1354. An alternative implementation could have been to increase the scanner buffer size even further, but the chosen implementation avoids the need to find a perfect buffer size since whole entries no longer need to fit within the buffer. Consequently, it also removes the custom configuration applied to the scanner.
This PR also updates existing tests that were testing `parseApkDBEntry` to test `parseApkDB` instead, since `parseApkDBEntry` no longer exists in the suggested implementation.
**Caveat:** The test fixture used to demonstrate the failure and prove the fix is `syft/pkg/cataloger/apkdb/test-fixtures/very-large-entries`. This is the APK installed DB taken from the image where the failure was first noticed. **This file is large (~4.6 MB)!** Let …

Fix parsing of apk databases with large entries

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/node

The node binary cataloger erroneously change the name of the node binary package to `node.js`. This corrects it to just `node`.

fix: Update node binary package name

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
syft/pkg/cataloger/common/cpe/candidate_by_package_type_test.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go

Not a great solution, but it at least removes these false flagging events and matches the current practices of manual vendor/product additions by adding support for manual vendor/product removals
Closes https://github.com/anchore/syft/issues/1066
Closes https://github.com/anchore/grype/issues/800
Closes https://github.com/anchore/grype/issues/491

fix: add manual vendor/product removal to fix false flags

---

go.mod
go.sum
syft/formats/common/cyclonedxhelpers/decoder.go
syft/formats/common/cyclonedxhelpers/decoder_test.go
syft/formats/common/cyclonedxhelpers/format.go

Blocked until changes incorporated into grype

chore: update latest cyclonedx library

---

README.md

The file classifier has been refactored to the binary cataloger, and is no longer cataloged separately, this change just removes obsolete docs.

docs: remove file classifier

---

syft/formats/common/cyclonedxhelpers/component.go
syft/formats/common/cyclonedxhelpers/component_test.go

Adds some logic to output `binary` packages as CycloneDX `application` type.
Fixes #1402

fix: cyclonedx component type for binaries

---

syft/pkg/cataloger/python/parse_requirements.go
syft/pkg/cataloger/python/parse_setup.go
syft/pkg/cataloger/python/parse_setup_test.go
syft/pkg/cataloger/python/test-fixtures/requires/requirements.txt
syft/pkg/cataloger/python/test-fixtures/setup/dynamic-setup.py

This PR fixes a couple of bugs:
- When there are formatting directives in `setup.py` package names (for dynamically crafted require lines, such as `%s` or `{}`) we should skip these lines
- When there are empty name or version fields for `requirements.txt` files (such as `==1.2.3`) we should skip these lines

Clean package names found in python catalogers

---

syft/pkg/cataloger/golang/scan_binary.go

This PR fixes excessive Go binary parse errors, e.g.:
```
[0000]  INFO syft version: 0.62.3
[0011]  INFO identified distro: Red Hat Enterprise Linux 8.7 (Ootpa)
[0011]  INFO cataloging image
[0017]  WARN unable to read golang buildinfo error=not a Go executable file=/usr/bin/bash
[0017]  WARN golang cataloger: bin parsing: number of builds and readers doesn't match
[0017]  WARN unable to read golang buildinfo error=not a Go executable file=/usr/bin/brotli
[0017]  WARN golang cataloger: bin parsing: number of builds and readers doesn't match
[0017]  WARN unable to read golang buildinfo error=not a Go executable file=/usr/bin/busctl
[0017]  WARN golang cataloger: bin parsing: number of builds and readers doesn't match
<snip ... another 2000 lines of the same 2 warnings for various files> …
```

fix: excessive go binary warnings

---

syft/pkg/cataloger/golang/parse_go_binary.go

:arrow_up: Follow-up to https://github.com/anchore/syft/pull/1424.
:bug: Fixes https://github.com/anchore/syft/issues/1403.
The original fix b125ea83baa30dc981e82f4ddd384602f778f090 didn't catch all the excessive warnings, it seems like getArches can also be called on binaries that aren't necessarily go binaries, so the messages from this should also be Trace instead of Warn

fix: additional excessive go binary warnings

---

syft/source/directory_resolver.go

Fixes `gret` :arrow_right: `get`.

fix: typo in os.Getwd error message

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go

I noticed that purls were empty for binary matched packages
```
{
"id": "42128c6f2809fa6c",
"name": "go",
"version": "1.19.4",
"type": "binary",
"foundBy": "binary-cataloger",
...
"purl": "",
...
},
```
And after 
```
{
"id": "42128c6f2809fa6c",
"name": "go",
"version": "1.19.4",
"type": "binary",
"foundBy": "binary-cataloger",
...
"purl": "pkg:generic/go@1.19.4",
...
},
```
Reference: [purl-spec generic type](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#generic)
cc: @kzantow

Add purls for binary classifiers

---

go.mod
go.sum
syft/formats/common/cyclonedxhelpers/decoder_test.go
syft/formats/common/spdxhelpers/to_syft_model_test.go
syft/formats/spdxjson/test-fixtures/spdx/alpine-3.10.syft.spdx.json
syft/formats/spdxtagvalue/test-fixtures/tag-value.spdx
syft/formats/test-fixtures/alpine-syft.json
syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/package_test.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go
syft/pkg/cataloger/sbom/cataloger_test.go
syft/pkg/cataloger/sbom/test-fixtures/alpine/syft-json/sbom.syft.json
syft/pkg/type.go
syft/pkg/type_test.go

apk is now in the purl spec: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#apk
Requires https://github.com/anchore/packageurl-go/pull/9 to be merged, and then I will update deps in this PR.

Add alpine type to purl

---

syft/source/source.go
syft/source/source_test.go
syft/source/test-fixtures/path-detected-2/.vimrc

When extracting `.tar` files, it's possible to have multiple entries with the same path. Using standard `tar` tools, the end result is the last file at a location is the one that remains after unarchiving. This PR adjusts Syft's unarchiving behavior of tar. files to match.
NOTE: prior to this change, Syft would print a `WARN` message when a duplicate path was encountered, it would also stop processing the archive further. This change allows unarchiving to continue but Syft is unable to get any information about duplicate files and no longer prints a warning.
Fixes #1400

fix: duplicate file in tar archive causes read to fail

---

README.md
cmd/syft/cli/options/packages.go
internal/config/application.go
syft/lib.go
syft/pkg/cataloger/catalog.go
syft/pkg/cataloger/config.go
test/cli/packages_cmd_test.go
test/integration/catalog_packages_test.go

Closes #1353 
This introduces a new option `SYFT_PARALLELISM=N` environement variable and syft config file value. Which will use at most `N` workers to process the package catalogers in parallel. The default will be 1.
- uses the `sync` library to create a wait group, waiting for all package catalogers to finish before proceeding.
- effectively has no real change in behaviour to users calling `syft` today, as the default is to create one worker.
----
> Open to recommendations on performance benchmarking but early results on laptop seem promising:
[Created](https://gist.github.com/Mikcl/3c171b074c65a77288788f4fb86cef0c) an exmple directory with `venv` and `node_modules`
```
➜  syft git:(mikcl/concurrent-catalog) SYFT_PARALLELISM=1 time go run cmd/syft/main.go packages  --file ../dump …
```

Parallel package catalog processing

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/httpd-2.4.54/httpd
test/integration/package_deduplication_test.go

This PR adds a binary cataloger for httpd
- As it will be detected as package, I did not add file name - apache2 (ubuntu OS package)
- To pass `make integration`, I updated package_deduplication_test.go. But sorry, this may not be proper.
fixes #1440

feat: add httpd classifier

---

internal/constants.go
schema/json/generate.go
schema/json/schema-6.1.0.json
syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden

The `GolangBinMetadata` was renamed to `GolangMetadata`, this PR updates the schama with this change.

chore: update schema

---

.github/workflows/update-bootstrap-tools.yml

Since cosign is no longer a direct dependency of syft, no need to bump it in the go.mod file as part of the bootstrap tools auto-update workflow

chore: remove bumping cosign in go.mod when updating bootstrap tools

---

syft/pkg/cataloger/java/graalvm_native_image_cataloger.go

This PR corrects a panic in the graalvm cataloger due to differences in 32/64-bit binaries.
Fixes #1453

fix: update graalvm cataloger to fix panic

---

.golangci.yaml
schema/spdx-json/spdx-schema-2.3.json
syft/formats/syftjson/to_syft_model.go
syft/pkg/cataloger/deb/package.go
syft/pkg/cataloger/erlang/parse_rebar_lock.go
syft/pkg/cataloger/java/archive_parser.go
ui/event_handlers.go

This PR adds a linter to enforce that type assertions are always checked, removing the risk of panics due to unhandled type assertions.

Add linter for type assertion checks

---

syft/pkg/cataloger/binary/cataloger.go
syft/pkg/cataloger/binary/cataloger_test.go
test/cli/spdx_tooling_validation_test.go
test/cli/test-fixtures/image-java-spdx-tools/Dockerfile

This PR adjusts the binary cataloger to compartmentalize errors to individual classifiers and continue to the next classifier when an error occurs.
This prevents errors from being fatal, such as:
```
[0001] TRACE cataloging complete cataloger=portage-cataloger
[0001] TRACE cataloging started cataloger=sbom-cataloger
[0001] DEBUG discovered 0 packages cataloger=sbom-cataloger
[0001] TRACE cataloging complete cataloger=sbom-cataloger
[0001] TRACE cataloging started cataloger=binary-cataloger
[0001]  WARN error while cataloging cataloger=binary-cataloger
No packages discovered
2023/01/19 13:12:27 error during command execution: 1 error occurred:
* failed to resolve files by glob (**/python*): cycle during symlink resolution
```

Relax error conditions for catalogers

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go

Today there are several instances of package IDs not being set by the time they reach the package catalog. This isn't good since it's the package catalogers role to do this. This PR adjusts the java package cataloger to call `SetID()` on all packages before returning the results (since the packages may be mutated after creation, this is the safest option).

Always set the package ID for java packages

---

syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/parse_package_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/array-license-package-lock.json

Fixes https://github.com/anchore/syft/issues/1479
Introduces new decoding behaviour for the `license` field in `package-lock.json` packages. To accept a string and array as the datatype. 
Previously: only a string was an expected value. This would mean the decoding step would fail in the event of an array being present, and all the remaining dependencies in the package-lock.json would not be cataloged.
This PR:
1. Accepts either a string or an array.
2. If its neither string or array and unable to parse the license field. Sets license to nil and does not error to allow us to capture the remaining package dependencies (at the expense of perhaps an unexpected license field not being captured).
- Have created the new  `packageLockLicense` type with overriden `UnMarshallJSON` behaviour to …

npm: package-lock license decoding to accept string or array

---

syft/pkg/cataloger/generic/cataloger.go
syft/pkg/cataloger/golang/scan_binary.go
syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
syft/source/directory_resolver.go

There are a few log statements that are expected to continually show what appears to be possible issues even though there is nothing wrong. These statements are useful when trying to troubleshoot issues, however, are fairly verbose even for the `debug` log level:
```
[0000] DEBUG checking if a new version of syft is available
[0000]  INFO new version of syft is available: 0.66.2 (current version is 0.66.0)
[0000] DEBUG image: source=DockerDaemon location=alpine:latest from-lib=stereoscope
[0000] DEBUG image metadata: digest=sha256:042a816809aac8d0f7d7cacac7965782ee2ecac3f21bcf9f24b1de1a7387b769 mediaType=application/vnd.docker.distribution.manifest.v2+json tags=[alpine:latest] from-lib=stereoscope
[0000] DEBUG layer metadata: index=0 …
```

Push noisy log statements to trace-level

---

syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

A bug was introduced in https://github.com/anchore/syft/pull/1063 where Syft would panic if a package listed in the installed DB doesn't "provide" anything.
This PR ~reworks the logic so that Syft allows for empty "provides" values~ (edit: no longer part of this PR, see https://github.com/anchore/syft/pull/1494#issuecomment-1398096945). It also adjusts the `stripVersionSpecifier` helper function to remove the possibility of panicking (index out of range).

Fix panic in APK version specifier handling 

---

syft/formats/syftjson/encoder_test.go
syft/formats/table/encoder_test.go

Fixes calls to AssertEncoderAgainstGoldenSnapshot to not hardcode the `updateSnapshot` parameter and to instead use the conditional CLI flag when running tests.

Fix AssertEncoderAgainstGoldenSnapshot calls to conditionally update

---

cmd/syft/cli/attest.go
cmd/syft/cli/attest/attest.go
cmd/syft/cli/commands.go
cmd/syft/cli/options/attest.go
internal/config/application.go
internal/config/attest.go
ui/event_handlers.go

Closes #1465 
Users can now add a --key <KEY_PATH> option to the syft attest command. This option will be passed to the shell out command introduced https://github.com/anchore/syft/pull/1442
Users can set the password for the key by using the environment variable `SYFT_ATTEST_PASSWORD`
Previous versions of syft offered an interactive TUI for typing the password. Because of the nature of the shellout command this option is no longer available
`cosign generate-key-pair`
` go run ./cmd/syft/main.go attest --key cosign.key <IMAGE_WITH_WRITE_ACCESS>`

1465 attestation with private key

---

cmd/syft/cli/convert/convert.go
test/cli/all_formats_convertible_test.go

This PR corrects an issue where `syft convert <sbom> -o template --template <file>` was not working.
Fixes #1409

fix: allow template for syft convert

---

.github/actions/bootstrap/action.yaml
.github/scripts/go-mod-tidy-check.sh
.github/scripts/json-schema-drift-check.sh
.github/workflows/release.yaml
.github/workflows/update-bootstrap-tools.yml
.github/workflows/update-stereoscope-release.yml
CONTRIBUTING.md
Makefile
go.mod

Go 1.18 will become EOL with the upcoming release of Go 1.20

feat: update golang to 1.19

---

internal/config/attest.go
test/cli/packages_cmd_test.go

Affects syft versions >= v0.69.0

fix: update config struct to not decode password/key

---

syft/source/directory_resolver.go
syft/source/directory_resolver_test.go

:arrow_up: Follow up to #1485 
When base is set, it should appear identically to when we scan the root filesystem - and as a result, the path should begin with the path separator.
E.g. when scanning the root `./target/` with the same base, `target/bin/busybox` should appear in the output as `/bin/busybox`, not as previously as `bin/busybox`.
Signed-off-by: Justin Chadwell <me@jedevc.com>

source: when base is set, responsePath should be absolute

---

test/integration/test-fixtures/image-vertical-package-dups/Dockerfile

To stable test
- Fix installed versions in Dockerfile used in `make intedration`
- In this time, installed httpd version will be changed
- As-Is : `2.4.6-98.el7.centos.6` (latest version)
- To-Be : `2.4.6-97.el7.centos.5`
related : https://github.com/anchore/syft/pull/1536

Fix installed versions in Dockerfile used in make integration

---

.github/scripts/ci-check.sh
.github/workflows/release.yaml
Makefile
RELEASE.md

Follow up to #1501 , a small adjustment to change the `trigger-release` with the `release` target. Additionally adjusts the release documentation to prioritize the procedures and pushes the background information to the end of the release process docs.

Replace the trigger-release target with the release target

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

Accurate CPE generation is important for getting accurate matches for alpine packages since it uses the NVD data to match and the alpine fix feed to deselect matches accordingly.  This ensures we generate expected CPE's for `python3` and `python`.

fix: python CPE generation for alpine

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

This PR adjusts some node identifications to properly pick up APK vulnerabilities.
Fixes https://github.com/anchore/grype/issues/1043

fix: missing APK node vulnerabilities

---

.github/workflows/validations.yaml

A temporary workaround to account for failing acceptance tests due to a false cache miss on mac runners in CI. See https://github.com/actions/cache/issues/1110 for more details.

Add workaround for macos github actions cache issue

---

syft/pkg/cataloger/cataloger.go
syft/pkg/cataloger/cataloger_test.go

Today the cataloger selection allows for partial name matches, so input such as `go` will select all go catalogers:
- **go**-mod-file-cataloger
- **go**-module-binary-cataloger
Unfortunately the current implementation takes a simplistic approach (a simple substring check) which causes additional false selections across ecosystems, which would most likely be unintentional. For instance, the same `go` search would additionally select:
- rust-car**go**-lock-cataloger
- car**go**-auditable-binary-cataloger
This PR applies a workaround to make this behavior a little better before https://github.com/anchore/syft/pull/1383 lands in a release (which fixes this behavior entirely).
The new behavior restricts the substring check to only allow for full words, separated by `-`. This still allows for …

Fix cataloger selection to be more specific

---

syft/formats/formats.go
syft/formats/formats_test.go

While working on PR #1583 I noticed there was an edge-case matching minor versions, for example if Syft JSON format has version `7.0.0`, requesting `json@7.0` would not match.

fix: issue when matching format versions

---

.github/workflows/validations.yaml

Reverts anchore/syft#1584 since it has been fixed upstream in https://github.com/actions/cache/issues/1110

Revert "Add workaround for macos github actions cache issue"

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

The correct CPE for curl is `cpe:2.3:a:haxx:curl:*:*:*:*:*:*:*:*`

fix: improve CPE generation for curl APK

---

syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/package_test.go

Determines better upstream package name for version-stream apk packages:
Examples:
- postgresql-13 -> postgresql
- postgresql15 -> postgresql
- go-1.19 -> go
- perl100.55 -> perl

fix: determine upstream for apk version streams

---

syft/pkg/apk_metadata.go
syft/pkg/apk_metadata_test.go

If APK Metadata JSON contains a `"pullDependencies": null`, this will cause Syft to fail to parse the entire SBOM with an error `invalid type for string array: <nil>`. This PR corrects the issue.

fix: decoding null apk metadata pullDependencies

---

syft/pkg/apk_metadata.go
syft/pkg/apk_metadata_test.go
syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/package_test.go

Export the logic for parsing upstream APK package names so it can be accessed from apk metadata objects directly.
This also tightens the upstream regex pattern as several edge cases were being missed.

refactor: move apk upstream logic to apk metadata

---

syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/package_test.go

The apk purl spec allows for vendor-specific namespace.  I noticed in the embedded SBOMs from wolfi that the purls are of the form `pkg:apk/wolfi/curl@7.83.0-r0?arch=x86`, but the current logic in syft actually prevents purl generation entirely if the distro isn't alpine, so this corrects that behaviour.

fix: correct apk purls for other distros

---

cmd/syft/cli/attest/attest.go

In #1533, I wanted to remove the hardcoded "custom" predicate type passed to Cosign. This seemed to fix some of the issues I was seeing, though to be honest at this point I don't know exactly why 😅 
However, what I did not anticipate is that there's still no way to manually set a predicate type. Generally, I think it makes sense to set the predicate type on the type we are passing as predicate to Cosign.
Thus, here my attempt at this. 
Please mind, this is untested so far. Wanted to get general feedback on this first (or if someone can quickly test this and verify the attestation, that'd be cool).
Also, if someone can tell me how I can properly reference the output type in the switch statement rather than just using string comparison based on the user input here without major refactoring, …

feat: set cosign attest predicate type based on Syft output type

---

Makefile

A recent release of go-releaser deprecated the `--rm-dist` flag - this pr upgrades the release command to use the new `--clean` flag

chore: update deprecated release flag

---

syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

If there is at least a path declared, construct a main module from that and retain all of the other information we can, build flags, etc rather than dropping them entirely from the sbom

feat: retain go package info when no module declared

---

cmd/syft/cli/eventloop/tasks.go
syft/lib.go
syft/pkg/cataloger/catalog.go
syft/pkg/cataloger/catalog_test.go

This PR handles any panics that occur within individual catalogers, allowing cataloging to continue and an SBOM to be generated.
Fixes #1624

fix: handle individual cataloger panics

---

syft/pkg/cataloger/erlang/erlang_parser.go
syft/pkg/cataloger/erlang/erlang_parser_test.go
syft/pkg/cataloger/erlang/parse_rebar_lock.go
syft/pkg/cataloger/erlang/parse_rebar_lock_test.go
syft/pkg/cataloger/erlang/test-fixtures/rebar-2.lock

`rebar.lock` files with git entries caused a panic when parsing. This PR corrects the issue and makes the parser more robust without relying on regexes.
Fixes #1621

fix: rebar lock file decoding panic

---

syft/pkg/cataloger/apkdb/cataloger_test.go
syft/pkg/cataloger/apkdb/parse_apk_db.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go

fixes #1572 
Sort of
The way apkdb works now, if it cannot find an `/etc/os-release` (or similar files on a fixed list), and if the ID is not `"alpine"`, it still reports on the package, but no purl is provided.
This has several problems.
* not everything will have an `etc/os-release`. This especially runs true when you are looking at a filesystem with multiple containers, or perhaps you have modified the `os-release` because your OS isn't alpine, but the packages in the embedded container are.
* there are multiple potential sources for packages; `os-release` is not necessarily the best place to find out where it came from.
* packages can come from multiple parallel locations, i.e. `/etc/apk/repositories` can have alpinelinux.org but also other places
* the version used for the packages …

read relative etc/apk/repositories for alpine version when no OS provided

---

syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/javascript.go
syft/pkg/cataloger/common/cpe/ruby.go
syft/pkg/cataloger/common/cpe/vendors_from_url.go
syft/pkg/cataloger/common/cpe/vendors_from_url_test.go

Currently, syft is still generating `*` for the vendor for Ruby and javascript, but this seems unnecessary and is as source of many reported false positives in Grype.  I have added the URL -> vendor candidates parsing logic for both as well.  Both ecosystems are already well-covered by GitHub Security Advisories anyways, so CPE's are becoming increasingly irrelevant to both.  Also we've already disabled wildcard vendors for java and that was the ecosystem where we were most likely to be catching something unknown (though still also catching enormous numbers of false positives)

feat: disable cpe vendor wildcards to reduce false positives

---

syft/pkg/cataloger/dotnet/package.go
syft/pkg/cataloger/dotnet/parse_dotnet_deps_test.go

Syft generates PURLs with `dotnet` type, but this is invalid. This PR changes these to be `nuget`, which is the closest type to what the dotnet cataloger is scanning.
Fixes: https://github.com/anchore/syft/issues/1622 
Related to: https://github.com/anchore/packageurl-go/pull/14

fix: dotnet PURL types are invalid

---

syft/formats/common/spdxhelpers/license.go
syft/formats/common/spdxhelpers/license_test.go
syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_format_model_test.go

Some SPDX LicenseRefs may be output incorrectly with invalid characters or whitespace, this PR sanitizes licenseRefs to adhere to the spec.
Fixes: #1651

fix: sanitize SPDX LicenseRefs

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/Makefile
syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/ruby-1.9.3p551/ruby

This PR adds a binary cataloger for ruby
- 2.x and 3.x
- use sharedLibraryLookup and fileContentsVersionMatcher
- test files are under dinamic/ created by Makefile
- since linked path/file is symbolic, two files (symbolic and true file) are copied in Makefile
- 1.x 
- use fileContentsVersionMatcher
- test file is under positive/ with past method
Fixes #1650

feat: add ruby classifier

---

syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/common/cpe/javascript.go

Syft was generating CPEs for javascript packages and including author information, but these were just splitting by `@`, assuming the author may have been an email address. However, the author is the form `Name <email> (url)`, e.g. `George Costanza <george@costanza.net> (https://costanza.net)`, which could result in a CPE similar to:
```
cpe:2.3:a:george-costanza-<george:package:6.14.6:*:*:*:*:*:*:*
```
This PR simply removes using the author, as there were not any identified cases that this was useful.

fix: remove author contributing to javascript CPEs

---

syft/source/source.go

On another project - https://github.com/defenseunicorns/zarf , I kept receiving the following error on our Windows build:
```
The process cannot access the file because it is being used by another process.
```
This error was thrown attempting to remove files that had been referenced by `source.NewFromFile`.
I believe the root cause is the dangling file reference in `SetID`. Linux/Mac are able to overcome this and can still remove the file, but Windows cannot.

Defer closing the opened file when using FileScheme

---

test/cli/spdx_tooling_validation_test.go

Update directory construction for test to reduce potential flake

feat: add shared dir for easier cleanup

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/Makefile

This PR fixes binary cataloger for ruby
- Support Double-digit version like 2.6.10
Fixes #1677

fix: ruby classifier

---

syft/pkg/cataloger/deb/parse_dpkg_db.go

When scanning DPKG with invalid lines, we should DEBUG log these vs. WARN.

fix: reduce logging for bad dpkg lines

---

README.md
cmd/syft/cli/packages.go

- Syft is now outputing SPDX 2.3 by default
- Give syntax to get SPDX 2.2
Fixes #1679

Update documentation: SPDX 2.2 vs 2.3

---

.github/workflows/release.yaml
.github/workflows/update-bootstrap-tools.yml
.github/workflows/update-stereoscope-release.yml

This PR just updates a couple things with workflows:
* use conventional commit messages for automated PRs
* output a correct link to a release in the Slack message

chore: tweak some workflow text

---

cmd/syft/cli/commands.go

Attempts a fix for #962. 
All credit to @cschug - see [this comment](https://github.com/anchore/syft/issues/962#issuecomment-1477771492)
As pointed out in that comment, the spf13/cobra library writes out the shell completion script using a `fmt.Sprintf` [here](https://github.com/spf13/cobra/blob/v1.6.1/bash_completionsV2.go#L37-L365). 
The `%[1]s` in that string seem to be replaced with the first command in the `Use:` field of the `cobra.Command` struct. Currently this field is ***not*** set so the `%[1]s` expand to an empty string resulting in a broken shell completion script. 
Adding the field (following the same method used by grype - [here](https://github.com/anchore/grype/blob/main/cmd/root.go#L63)) gives the `spf13/cobra` library the info it needs to correctly generate the shell …

Fix shell completion by adding missing usage message required by spf13/cobra

---

syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_format_model_test.go

This PR fixes an issue where SPDX other licenses are not sorted consistently, causing flaky test failures.

chore: fix flaky license sorting

---

schema/json/generate.go
syft/file/classifier.go
syft/pkg/cataloger/cataloger.go
syft/pkg/cataloger/nixstore/cataloger.go
syft/pkg/cataloger/nixstore/parse_nix.go
syft/pkg/metadata.go
syft/pkg/nix_store_metadata.go
syft/pkg/type.go

Add Basic Nix Cataloger

---

README.md
cmd/syft/cli/attest/attest.go
cmd/syft/cli/packages/packages.go
cmd/syft/cli/poweruser/poweruser.go
internal/config/application.go
syft/source/source.go
syft/source/source_test.go
test/integration/catalog_packages_test.go
test/integration/utils_test.go

Syft is consumed by upstream tools for generating SBOM. These SBOM can be generated from a variety of sources including local and OCI registry images. 
https://github.com/anchore/grype/issues/1204 surfaces the need for allowing a user to express a preference over the default source to be used when building an SBOM for an image (and then subsequently generating a vulnerability scan).
This first step adds a config option into syft and changes the library behavior so this preference can be injected into the SBOM generation process. A follow up PR will be made for grype to adapt to this new ability.
local Docker Daemon

feat: Add config option to allow user to select the default image source location

---

.github/workflows/benchmark-testing.yaml
.github/workflows/update-stereoscope-release.yml

Update deprecated `::set-output` calls

chore: update deprecated set-output calls

---

test/cli/spdx_tooling_validation_test.go
test/cli/test-fixtures/image-java-spdx-tools/Makefile

We've seen several failures of the SPDX tooling test, but haven't been able to determine exactly why:
I have a couple educated guesses and made some targeted refactors, but have no conclusive evidence if this will fix the underlying issue (seems to only happen in CI every once in a while).
I've also made a couple of improvements:
- uses the existing test fixture facilities, as to leverage any preloaded CI cache without requiring a re build of the image.
- uses a temp dir per test Run() call instead of sharing directories.
- passes the explicit file for syft to write to and passes this file path to the verification tool

Refactor spdx tooling test to reduce intermittent failures

---

README.md
syft/pkg/cataloger/java/archive_filename.go
syft/pkg/cataloger/java/archive_filename_test.go
syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/cataloger_test.go
syft/pkg/cataloger/java/test-fixtures/glob-paths/java-archives/example.nar

Add support for nar files.
- Update README.md to show that nar is now supported.
- Created a java-archives/example.nar so that the tests wouldn't break.
- Add nar glob and as an option for pkgType.
Closes #1701

Add support for java "nar" files

---

.github/workflows/validations.yaml
Makefile
syft/pkg/cataloger/kernel/cataloger_test.go
syft/pkg/cataloger/kernel/test-fixtures/Makefile
syft/pkg/cataloger/kernel/test-fixtures/image-kernel-and-modules/Dockerfile
test/integration/catalog_packages_cases_test.go
test/integration/test-fixtures/image-pkg-coverage/Dockerfile

This PR does a few things:
- pins the kernel test fixtures to a specific version that is not in the updates fedora channel (I needed to swap out the module under test since we couldn't pin the module being currently used)
- caches test images in CI between runs

Fix kernel cataloger test fixtures

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/Makefile

Create consul binary classifier
Closes #1590

Create consul binary classifier

---

syft/pkg/alpm_metadata.go

Add ALPM Metadata to CYCLONEDX and SPDX output formats
Closes #1037
As mentioned in #1037 by @kzantow  it seemed most items may not map to SPDX. I am also unfamiliar with SPDX but didn't seem to find fields that mapped properly to the items needed.

Add ALPM Metadata to CYCLONEDX and SPDX output formats

---

.github/workflows/validations.yaml
syft/pkg/cataloger/java/test-fixtures/java-builds/Makefile

Revert changes from https://github.com/anchore/syft/pull/1748.
We only want to cache the final package test fixtures builds.
We do want to calculate based on a few more files being changed so those have been added for the CI check by `find build*` rather than `build-`

fix: only cache java packages and not source content

---

syft/pkg/cataloger/javascript/parse_pnpm_lock.go
syft/pkg/cataloger/javascript/parse_pnpm_lock_test.go

Improve pnpm support
- Parse packages section from pnpm-lock.yaml to get transitive dependencies.
- Should add support for getting dependencies from pnpm-lock.yaml files that use workspaces.
- This is due to the fact all dependencies should get listed under the packages section.
Closes #1535

Improve pnpm support

---

syft/formats/common/cyclonedxhelpers/decoder.go
syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_format_model_test.go
syft/formats/common/spdxhelpers/to_syft_model.go
syft/formats/github/encoder_test.go
syft/formats/internal/testutils/utils.go
syft/formats/spdxtagvalue/encoder_test.go
syft/formats/syftjson/encoder_test.go
syft/formats/syftjson/to_format_model.go
syft/formats/syftjson/to_syft_model.go
syft/lib.go
syft/pkg/catalog.go
syft/pkg/catalog_test.go
syft/pkg/cataloger/catalog.go
syft/pkg/deprecated.go
syft/pkg/relationships.go
syft/pkg/relationships_by_file_ownership.go
syft/pkg/relationships_by_file_ownership_test.go
syft/pkg/relationships_evident_by.go
syft/pkg/relationships_evident_by_test.go
syft/sbom/sbom.go
test/integration/catalog_packages_test.go

As part of the work under #558  (from https://github.com/anchore/syft/issues/558#issuecomment-1081846913) renames the pkg.Catalog to pkg.Collection. The existing pkg.Catalog type and constructor is still in the codebase as a type alias and deprecation notice. The type aliases will be removed in syft 1.0.

Rename pkg.Catalog to pkg.Collection

---

syft/formats/internal/testutils/utils.go

This reverts format testing to the previous behavior to where golden files are written not redacted.

chore: update test redactor ordering

---

syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_format_model_test.go
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXJSONSPDXIDs.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden

This PR adjusts how Syft outputs SPDX IDs for files to include some information about the file name in the ID (up to 40 characters). This helps with SPDX Tag Value stability, as the `spdx/tools-golang` library is re-sorting files based on the SPDX ID. The sorting is an issue because layer hashes contribute to the file hashes themselves, so rebuilding a container and re-scanning results in significantly different ordering of the files without this change. This also helps to make relationships more clear when just looking at the SPDX relationship elements, these now include `File-<some-path>`, e.g.:
```
Relationship: SPDXRef-Package-apk-scanelf-e903138d19e85b80 OTHER SPDXRef-File-lib-apk-db-installed-3f4e74b9e4beb504
```

chore: add more detail on SPDX file IDs

---

syft/formats/github/format.go

`sbom-action` issue https://github.com/anchore/sbom-action/issues/414 indicates that there is an issue with GitHub accepting PURLs that contain backslashes (even if they are valid JSON escape sequences). This PR adjust the GitHub output to _not_ HTML escape.

chore: do not HTML escape PackageURLs

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
syft/pkg/cataloger/common/cpe/generate_test.go

This commit update the CPE generation to include vmware:spring_security in the CPE name which is what NVD uses for spring security vulnerabilities such as https://nvd.nist.gov/vuln/detail/CVE-2023-20862

Update the CPE generation for spring-security-core

---

test/cli/trait_assertions_test.go

The tests in test/cli/packages_cmd_test.go are hard to debug when different packages are found in different environments. For example, CI runs and M1 macs have been observed to have different package counts. Therefore, if the test is about to fail, log a sorted list of the packages that were found, so that it is easy to compare failures of these tests.
Example of new output (extra logs only happen on failure):
```
=== RUN   TestPackagesCmdFlags/squashed-scope-flag-hidden-packages
packages_cmd_test.go:251: expected package count of 163, but found 167
packages_cmd_test.go:251: package 1: PyGObject:3.22.0
packages_cmd_test.go:251: package 2: acl:2.2.51-15.el7
packages_cmd_test.go:251: package 3: audit-libs:2.8.5-4.el7
packages_cmd_test.go:251: package 4: basesystem:10.0-7.el7.centos …
```

Print package list when extra packages found

---

syft/formats/syftjson/to_syft_model.go
syft/formats/syftjson/to_syft_model_test.go

An unknown relationship type doesn't mean things are incorrect; it probably means that the version of syft that generated the SBOM is ahead of the version of syft that's parsing it.
Addresses https://github.com/anchore/grype/issues/1244, but won't fix it until the version of syft that's imported by grype is updated, at https://github.com/anchore/grype/blob/75e7ef43cd03baba4c76af3751274c7aa7452f36/go.mod#L56.

Reduce log spam on unknown relationship type

---

syft/formats/common/cyclonedxhelpers/decoder.go
syft/formats/common/cyclonedxhelpers/decoder_test.go

When reading CycloneDX boms, the relationships defined in the "dependencies" sections are translated into "artifact.Relationship" objects. Previously, relationships were inverted by this process. That is, a CycloneDx dependency "a depends on b" was being read as "a dependency of b". This caused downstream processing to write out the dependency relationship incorrectly. This commit fixes the issue by inverting the relationship during decoding and adding a regression test.
Fixes anchore/syft#1815

fix: cyclonedx depends-on relationship inverted

---

syft/pkg/cataloger/apkdb/package.go
syft/pkg/cataloger/apkdb/parse_apk_db_test.go
syft/pkg/cataloger/apkdb/test-fixtures/multiple

Fixes: #1817 
Bug fix for Alpine cataloger to check for valid expressions on the parsed entry before splitting the licenses into individual entities.

fix: update cataloger to check for expressions before split

---

syft/pkg/cataloger/javascript/parse_pnpm_lock.go
syft/pkg/cataloger/javascript/parse_pnpm_lock_test.go
syft/pkg/cataloger/javascript/test-fixtures/pnpm-v6/pnpm-lock.yaml

When #1752 was merged, it was overlooked that it could create duplicate packages. This PR prevents duplicate packages from being added and also adds support for PNPM lock file version 6.
Fixes #1762

fix: duplicate packages, support pnpm lockfile v6

---

syft/source/source.go

This PR is meant to solve an issue we've got when syft failed to print the "right" error upon fetch failure.
For example, i'm trying to scan an arm64 image with an amd64 syft CLI and i'm getting the following error:
```
$ syft docker:idanfrim/multi-arch:only-arm64
⠸ Pulling image
2023/05/09 10:29:44 error during command execution: 1 error occurred:
* failed to construct source from user input "docker:idanfrim/multi-arch:only-arm64": could not fetch image "idanfrim/multi-arch:only-arm64": unable to determine image source to select platform
```
The error is not clear, `unable to determine image source` is wrong since i've provided `docker` scheme.
When running the same command with debug I can see the correct failure.
```
$ syft -v docker:idanfrim/multi-arch:only-arm64
[0000]  INFO syft …
```

Return both failures when failed to retrive an image with a scheme

---

syft/license/license.go
syft/pkg/license.go

Closes #1837 
With this fix we can release v0.81.1 as a patch which will defer the panic caused by the call to `ValidateLicenses`
Tested against the example in the issue using `syft` from this branch and `grype v0.62.0`
```bash
go run cmd/syft/main.go -o json lscr.io/linuxserver/webtop:alpine-openbox | grype
```

fix: add panic recovery for license parse

---

syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

syft's workaround for the go binary `(devel)` issue is [here](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/golang/parse_go_binary.go#L85-L120).
It looks at `ldflags` and, if it cannot find a valid `main.version` (or similar), it tries to calculate the go pseudo-version, which needs vcs info.
The current design does not check `ldflags` unless it finds vcs info _first_. Of course, if it finds `ldflags` info, it doesn't actually need the `vcs` info.
This PR changes it around so that it first tries to read `ldflags` and only after it fails to do so, does it try vcs.
I also added tests for this specific case, as well as adding tests for `main.version` and `main.Version`.

accept main.version ldflags even without vcs

---

syft/internal/fileresolver/directory_indexer.go

Fixes #1860 
Ensures that if a symlink in a directory points to something that does not exist, it logs a debug message and continues, rather than adding a new root which does not exist, which would cause a fatal error.

in directory indexer, handle outside symlinks

---

syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/parse_pom_xml_test.go

I noticed when fixing https://github.com/anchore/grype/issues/985 that Grype has a field in the metadata for Artifact ID but it was an empty string and wasn't being set by Syft.

fix: pom properties not setting artifact id

---

syft/artifact/id.go
syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden

Otherwise the hash can sometimes be short if it results in a low uint64.
This seems to be the cause of this failure: https://github.com/anchore/sbom-action/actions/runs/5270697648/jobs/9530548662?pr=418#step:6:2913
We think that padding these makes sense. Once syft hits 1.0, we'd like them to be stable, so if we want to introduce padding we want to do it while we're pre 1.0.
This was discovered while working on https://github.com/anchore/sbom-action/issues/419, because it caused snapshot failures on https://github.com/anchore/sbom-action/pull/418
There doesn't seem to be a great way to get a unit test around this format string, and I doubt it will ever change once committed, so performed a small experiment (in addition to updating the snapshot test) to prove this does what we want. …

Pad artifact IDs

---

.chronicle.yaml

Track a chronicle config file that causes chronicle to bump minor version instead of major version in response to the "breaking-change" label for pre-1.0 releases.

Create chronicle config

---

README.md

Add some explanation around why there are different default sets of catalogers for image scans versus directory scans. Hopefully clarify questions related to #1776.
Signed-off-by: Timothy Gerla <tim@gerla.net>

docs: clarify reasoning of default catalogers for images or directories

---

syft/formats/common/cyclonedxhelpers/component_test.go
syft/formats/common/cyclonedxhelpers/licenses.go
syft/formats/common/cyclonedxhelpers/licenses_test.go

CycloneDX was potentially outputting invalid licenses, e.g. `"license": [{}]` (note the lack of required `expression`, `license`.`id`/`name` parameters). This PR ensures required parameters are output for CycloneDX licenses.
Fixes #1877

fix: only output valid cyclonedx license choices

---

syft/pkg/cataloger/java/archive_filename.go
syft/pkg/cataloger/java/archive_filename_test.go

There was a bug, caused by someone who shall remain nameless, where parsing the package name and version from a Java archive filename treated any strings that began with "build" as versions.
This leads to a large number of **false positives in Grype** because it feeds invalid versions into Grype's version comparison logic.
I believe the original intent was to ensure build numbers were treated as version components, which is valid, but when the package name included "build" with no number directly following (such as in `gradle-build-cache-8.1.1`), the "build" was automatically starting the version data, not continuing the package name data.
This has been addressed by changing `*` to `+` in a regex. 😆

Fix version detection in Java archive name parsing

---

syft/pkg/cataloger/dart/parse_pubspec_lock.go
syft/pkg/cataloger/dart/parse_pubspec_lock_test.go
syft/pkg/cataloger/dart/test-fixtures/pubspec.lock

SDK package dependencies such as Flutter cause yaml parsing errors. Update the parser so that lockfiles including these packages can be evaluated.

fix: add support for Dart SDK package dependencies

---

syft/pkg/cataloger/deb/cataloger_test.go
syft/pkg/cataloger/deb/package.go
syft/pkg/cataloger/deb/test-fixtures/image-distroless-deb/Dockerfile
syft/pkg/cataloger/deb/test-fixtures/image-distroless-deb/usr/share/doc/libsqlite3-0/copyright
syft/pkg/cataloger/deb/test-fixtures/image-distroless-deb/var/lib/dpkg/status.d/libsqlite3-0
syft/pkg/cataloger/deb/test-fixtures/image-distroless-deb/var/lib/dpkg/status.d/libsqlite3-0.md5sums

For distroless images the md5sum files are under `/var/lib/dpkg/status.d/` rather than `/var/lib/dpkg/info/`
Fixes #1900

fix: discover deb file relationships in distroless images

---

README.md

Hi,
I noticed that among the windows package managers, Scoop was not listed, which does support syft. So I added it to the readme. If anything is missing in the pr please tell me.

README: add installation section with Scoop

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

Per discussion w/ @wagoodman: filter out CPEs known to be incorrect, specifically as CPEs that match non-Maven components to Maven vulnerabilities.
Also adds one case for counting a "Gradle Enterprise" plugin as Gradle Enterprise itself.

Remove erroneous Java CPEs from generation

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go

Matches using CPEs `redis:redis` and `grpc:grpc` for **_Ruby Gems_** will always be incorrect.

Don't use the actual redis or grpc CPEs for gems

---

syft/formats/common/cyclonedxhelpers/decoder.go

This resolves https://github.com/anchore/grype/issues/1005
The cyclonedx-go library returns Nil when presented with:
```xml
<components></components>
```
But returns an empty slice when presented with:
```json
"components": []
```
The fix is to check if the format is XML, then inspect the XMLNS field and for other formats inspect the Components field

fix: allow valid cyclonedx input with no components

---

cmd/syft/cli/ui/handle_attestation.go
cmd/syft/cli/ui/handle_attestation_test.go
cmd/syft/cli/ui/util_test.go

Add individual WG to background reader to track/block on buffer being read for snapshot tests
This should fix the race condition in CI rather than bumping iterations n number of times like we had in the past

fix: background reader apart from global handler for testing

---

DEVELOPING.md

docs: capture artifactory dev settings from 1895

---

cmd/syft/cli/packages/packages.go
cmd/syft/cli/ui/handle_pull_docker_image.go
cmd/syft/internal/ui/ui.go

When pulling a docker image and there is an issue, there is a panic when attempting to close the source:
```
❯ go run ./cmd/syft python:slim -o json
⠼ Pulling image
panic: value method github.com/anchore/syft/syft/source.StereoscopeImageSource.Close called using nil *StereoscopeImageSource pointer
goroutine 9 [running]:
github.com/anchore/syft/syft/source.(*StereoscopeImageSource).Close(0xc00011c3e0?)
<autogenerated>:1 +0x86
github.com/anchore/syft/cmd/syft/cli/packages.execWorker.func1()
/Users/wagoodman/code/syft/cmd/syft/cli/packages/packages.go:109 +0x92a
created by github.com/anchore/syft/cmd/syft/cli/packages.execWorker
/Users/wagoodman/code/syft/cmd/syft/cli/packages/packages.go:57 +0xf7
exit status 2
```
When fixing the panic, it was noticed that the UI was hung (but no more …

Fix panic condition on docker pull failure

---

go.mod
go.sum

This bumps syft to the latest version of the `spdx/tools-golang` library which has a fix for decoding issues surrounding the `originator` field in spdx json
Follow up on an issue reported over in grype https://github.com/anchore/grype/issues/1306
I can bump this to an official release when it comes out, but wanted to get this fix in if we're looking to cut a new release this PM.

chore: update to latest commit in tools-golang

---

syft/pkg/cataloger/common/cpe/generate_test.go

There is an issue with some of the existing tests for CPE generation where we will assert that a subset of the actual CPEs are generated. This is due to to not all test fixtures having the metadata-type specified (which, when there is data in the metadata field, should always be specified). When fixed the CPE geneneration tests begin to fail:
```
=== RUN   TestGeneratePackageCPEs/cloudbees_jenkins_package_identified_via_groupId
generate_test.go:716: found extra CPEs:
generate_test.go:718:    "cpe:2.3:a:cloudbees:name:3.2:*:*:*:*:*:*:*",
=== RUN   TestGeneratePackageCPEs/jenkins.io_package_identified_via_groupId_prefix
generate_test.go:716: found extra CPEs:
generate_test.go:718:    "cpe:2.3:a:jenkins:name:3.2:*:*:*:*:*:*:*",
generate_test.go:718: …
```

Add metadata types to all CPE test fixtures

---

syft/pkg/rpm_metadata.go

See the below link:
https://fedoraproject.org/wiki/Changes/RelocateRPMToUsr
Photon does not soft link the old location of `var/lib` to the newer location like other distros. We should account for this in our RpmDBGlob search by including a search for the newer path
Note the second run of syft is the latest version. The first run has the current branches code

fix: update glob to use newer usr/lib/sysimage path

---

syft/pkg/cataloger/java/parse_gradle_lockfile.go
syft/pkg/cataloger/java/parse_gradle_lockfile_test.go
syft/pkg/cataloger/java/test-fixtures/gradle/gradle.lockfile

This PR corrects an issue where the Gradle lockfile parser was neither taking into account the `groupId` nor creating a `JavaMetadata` object, despite indicating the `MetadataType` was java metadata. This resulted in, among other things, CPEs being generated incorrectly for the entries in the lockfile.
Fixes: #1957

fix: gradle lockfile parser groupId handling

---

syft/formats/common/spdxhelpers/license.go
syft/formats/common/spdxhelpers/license_test.go
syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/common/spdxhelpers/to_syft_model.go
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXJSONSPDXIDs.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
test/cli/spdx_tooling_validation_test.go
test/cli/test-fixtures/image-java-spdx-tools/Dockerfile
test/cli/utils_test.go

I noticed that we are using parts of the `LicenseRef-` ID for the other license value, which has had unsupported SPDXID characters swapped to dashes. This PR corrects that issue as well as an omitted PackageDownloadLocation, which was producing invalid SPDX documents. Additionally, this enables the SPDX tool validator failures to fail CLI tests.

fix: SPDX license values and download location

---

syft/formats/common/spdxhelpers/to_syft_model.go
syft/formats/common/spdxhelpers/to_syft_model_test.go
syft/formats/spdxtagvalue/decoder_test.go

This PR corrects an issue that when decoding SPDX tag-value direct package files are omitted.
Fixes #2013

fix: read direct package files when decoding SPDX tag-value

---

syft/lib.go
syft/lib_test.go

This PR corrects an issue where binary packages removed by ownership-by-file-overlap relationships were inconsistently removing entries.
Fixes: #2035

fix: inconsistent removal of binaries by file overlap

---

cmd/syft/internal/ui/__snapshots__/post_ui_event_writer_test.snap
cmd/syft/internal/ui/post_ui_event_writer.go
cmd/syft/internal/ui/post_ui_event_writer_test.go

Just like in https://github.com/anchore/grype/pull/1445 , Currently when running grype and there is a new version available the version is shown with no other context. This PR addresses this by filling in the notice text.

New version notice only showing the version and no text

---

syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/default_classifiers.go
syft/pkg/cataloger/binary/test-fixtures/classifiers/positive/bash-5.2.15/bash

This PR adds a binary cataloger for bash
- As I can not judge version of alpha/beta (alpha1 or alpha2) in version information, alpha/beta/rc is not desplayed
Fixes #1963

feat: add bash classifier

---

syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/parse_pom_xml_test.go

This reflect code occasionally throws an obscure panic, but not enough information is logged before the panic to know why it panicked. Log enough to tell what property and package are being analyzed when the panic occurs.
Test command:
``` sh
go run cmd/syft/main.go -vvvv ./test/integration/test-fixtures/image-pkg-coverage/pkgs/java/example-java-app-maven-0.1.0.jar
```
Example of new logging:
``` log
...
[0000] TRACE parsing file contents path=/example-java-app-maven-0.1.0.jar
[0000] TRACE parsing pom.xml artifactID=example-java-app-maven name= path=META-INF/maven/org.anchore/example-java-app-maven/pom.xml projectURL=
[0000] TRACE resolving property existingPropertyValue=org.anchore propertyName=groupId
[0000] TRACE resolving property existingPropertyValue=0.1.0 propertyName=version …
```

chore: Trace log pom property reflect usage

---

syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/parse_pom_xml_test.go

A recent update to gopom changed many fields to be omitted when empty, resulting in a number of nil pointers inside the nested structure of the pom that previously didn't exist. Defend against these in the search for the property value.
Fixes https://github.com/anchore/syft/issues/2060

Fix panic in pom parsing

---

syft/formats/common/cyclonedxhelpers/format.go
syft/formats/common/cyclonedxhelpers/format_test.go

This PR corrects an issue where Syft is not outputting CycloneDX dependencies properly -- instead of one entry for a unique `Ref`, it was outputting multiple entries with the same `Ref`, which is not valid. [The spec states](https://cyclonedx.org/docs/1.5/json/#dependencies): "All items must be unique", which seems to indicate each entry has a unique `Ref` and the `cyclonedx-cli validate` fails.
With this change, the latest `cyclonedx-cli` indicates the BOM is now valid:
```
$ cyclonedx-cli validate --input-file alpine.cdx.json
BOM validated successfully.
```
Fixes: #2062

fix: duplicate entries in cyclonedx dependency list

---

syft/pkg/cataloger/common/cpe/candidate_by_package_type.go
syft/pkg/cataloger/common/cpe/generate_test.go

This PR adds a CPE generation for Django
- In my understanding, syft + grype support Django via GHSA dataset
- If user uses syft SBOM + some tool which supports only NVD (not support GHSA), user will be able to detect Django vuluneravilities by this PR
- If some vuluneravilities are registered on only NVD, user will be able to detect Django vuluneravilities by this PR.
- Sometimes NVD updates their old data, but GHSA will not fetch those data
Fixes #1298 
----
I prepared sample image and check.
Dockerfile
```
FROM python:latest
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
```
requirements.txt
```
Django==4.0.0
```
```
$ grype version
Application:          grype
Version:              0.65.2
Syft Version:         v0.87.1
BuildDate: …
```

add CPE generation for Django

---

syft/pkg/cataloger/java/archive_parser.go
test/integration/regression_java_virtualpath_test.go
test/integration/test-fixtures/image-java-virtualpath-regression/Dockerfile

Implements the following changes in the java archive parser's `discoverMainPackage()` method:
if there is exactly one pom.xml and pom.properties in the jar and if the filename is a prefix of the artifact ID on the pom.properties, prefer, in order, for name and version:
1. A non-empty string on pom.properties
2. A non-empty string on pom.xml
3. A name based on the filename of the top-level jar
4. Name info from the manifest.
Definitely open to feedback and refactoring here, but wanted to show a working fix before spending too much time making it look great.
Fixes https://github.com/anchore/syft/issues/2077

fix: in some cases, try to use pom info to guess name and version to top level jar

---

cmd/syft/cli/cli.go
test/cli/packages_cmd_test.go
test/cli/trait_assertions_test.go

Currently the quiet flag is only responsive with the logger UI, but not the text UI. This PR fixes this regression.

Fix quiet flag

---

cmd/syft/cli/cli.go
cmd/syft/main.go

This allows for consuming applications to use the cobra command directly, which allows for embedding the syft cli into another cli easily. We might do this in the future up in clio but decided to hold off on that for now (related PR https://github.com/anchore/clio/pull/26 ).

Expose cobra command in cli package

---

syft/formats/common/cyclonedxhelpers/external_references.go
syft/formats/common/cyclonedxhelpers/external_references_test.go

Fixes #2079
Validate extracted metadata before encoding into output file as `external_references`.

fix(cdx): validate external refs before encoding

---

cmd/syft/cli/commands/poweruser.go

Cloeses #2046 
the stdout of power-user --help specifies that it doesn't support fs, which is wrong.
removed the line.

fix the help output of power-user

---

Makefile

Previously, there were some data races in syft. Right now, none are detected, so check for data races on the overall command, and on unit tests. (Checking for races on integration tests triples the time needed for those tests, from ~1 minute to ~3 minutes on my workstation, so that was not done at this time.)

chore: enforce race detector

---

syft/formats/common/cyclonedxhelpers/decoder.go

According to [cyclonedx json reference](https://cyclonedx.org/docs/1.4/json/#services) the components field is not mandatory.
This can be verified, by generating a cyclonedx json report using https://github.com/CycloneDX/cyclonedx-maven-plugin in a small maven project.
A missing components field will lead to:
`error during command execution: failed to decode SBOM: unable to identify format`
This fixes the error and still respects [this pr](https://github.com/anchore/syft/pull/1873).

fix: allow cyclonedx json input with no components

---

internal/constants.go
schema/json/schema-10.0.2.json
syft/formats/syftjson/decoder_test.go
syft/formats/syftjson/model/file.go
syft/formats/syftjson/to_format_model.go
syft/formats/syftjson/to_syft_model.go
syft/formats/syftjson/to_syft_model_test.go

This PR corrects an issue that the Syft SBOM `FileLicenses` and `FileContents` were not being encoded/decoded properly.
Fixes: #2069

fix: encode and decode FileLicenses and FileContents in Syft JSON

---

test/cli/test-fixtures/image-bad-binaries/Dockerfile
test/cli/test-fixtures/image-hidden-packages/Dockerfile
test/cli/test-fixtures/image-java-spdx-tools/Dockerfile
test/cli/test-fixtures/image-node-binary/Dockerfile
test/cli/test-fixtures/registry/Dockerfile

Many of these images have a slightly different set of packages when the arm64 variant is pulled, so that leaving this digest unpinned causes the tests to fail on arm64 hosts. Pin the FROM lines to force stable platform values regardless of host architecture.
Fixes #1788.
Draft because waiting on a response to [this comment](https://github.com/anchore/syft/issues/1788#issuecomment-1721432449)

chore: pin all cli test FROM lines to linux/amd64

---

syft/internal/fileresolver/container_image_all_layers_test.go

Now that the test fixture pins to a particular digest, there's no need for platform specific architecture switches in this test.

chore: remove unneeded arch switch in unit test

---

.gitignore
go.mod
go.sum
syft/pkg/cataloger/cpp/parse_conanlock_test.go
syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
syft/pkg/cataloger/sbom/cataloger_test.go

There were two problems found:
- relationships were not being sorted during test assertions, leading to unstable results
- IDs were not being set on packages for conan tests (which will affect the new sorting)
I also added an additional entry to the gitignore for a case that goland keeps generating (erroneously).

Require ordering of relationships when comparing parser output

---

cmd/syft/cli/options/output.go
go.mod
go.sum
syft/formats/common/cyclonedxhelpers/format.go
syft/formats/common/spdxhelpers/to_format_model.go
syft/formats/formats.go
syft/internal/fileresolver/unindexed_directory.go
syft/pkg/cataloger/common/cpe/dictionary/index-generator/generate.go
syft/pkg/cataloger/package_exclusions.go
syft/sbom/sbom.go

Switch slices usage to `Go1.21` standard library's instead of relying to golang/x/exp/slices

chore: switch to stdlib's slices pkg

---

.chronicle.yaml
.github/actions/bootstrap/action.yaml
.github/workflows/release.yaml

Adjustments to the release process based off of the last release:
- don't show the title of the changelog in the release notes
- don't upload assets in the release pipeline (as they are going to be on the github release page anyway)
- bump action-slack to the correct version pin
- there are cache collisions due to the fact that the go-setup action now enables mod and build caching by default https://github.com/actions/setup-go?tab=readme-ov-file#v4

Correcting behavior based on Syft release v0.91.0 run

---

syft/pkg/cataloger/common/cpe/java.go
syft/pkg/cataloger/common/cpe/java_groupid_map.go
test/integration/java_purl_test.go

Previously, iterating over the map to build up a string slice of groupID candidates resulted in non-deterministic selection of the groupID. Fix that by sorting candidates, and update some integration tests that were only passing because of the issue.
There might be more discussion needed here:
1. The comment at https://github.com/anchore/syft/blob/8314c0d2cbc0732ce79b383ab260af4bd31ae1ad/syft/pkg/cataloger/java/package_url.go#L67-L69 seems like it was never true, since the array order coming back from `GetManifestFieldGroupIDs` was non-deterministic due to iterating maps
2. There's no reason to suppose that the lexicographically first group ID is a better choice than whatever group ID happened to win the map iteration.
Fixes https://github.com/anchore/syft/issues/2169, but open to …

fix: deterministic java purls

---

go.mod
go.sum

Pulls in a fix in go-progress that prevents a race in the UI code when scanning large images.

chore: bump stereoscope to fix data race in UI code

---

cmd/syft/cli/options/output.go

- Added usage syntax to CLI help text for `--output` option for better understanding. The new help text looks like:
``` text 
-o, --output stringArray       report output format (<format>=<file> to output to a file), formats=[syft-json github-json syft-table syft-text template cyclonedx-xml cyclonedx-json spdx-tag-value spdx-json] (default [syft-table])
```
- Marked the `--file` option as deprecated, suggesting to use `--output` as an alternative. The new help text looks like:
``` text
--file string              file to write the default report output to (default is STDOUT) (DEPRECATED: use: output)  
```
Resolves: https://github.com/anchore/syft/issues/2165

Refactor --output help text and deprecate --file.

---

cmd/syft/cli/options/writer_test.go

Closes #2192 by replacing the conditional with just the content of one of its branches.

fix: `if` with identical `then` and `else` blocks in cli/options/writer_test.go

---

README.md

It was not clear what was the exact syntax of the conversion command.
You had to do "syft convert -h" to know.

Add exact syntax of the conversion formats

---

syft/formats/common/cyclonedxhelpers/external_references.go
syft/formats/common/cyclonedxhelpers/external_references_test.go

- Fixed the algorithm look up logic by converting the key (algorithm name) to lower case.
- Added unit test for `toCycloneDXAlgorithm`.
Resolves: https://github.com/anchore/syft/issues/2183
The example from the above issue now produces the following final output:
[sboms.zip](https://github.com/anchore/syft/files/12845412/sboms.zip)

Fix: Correctly map algorithm name in CycloneDx 

---

internal/constants.go
schema/json/schema-11.0.1.json
syft/formats/cyclonedxxml/encoder_test.go
syft/formats/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
syft/formats/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
syft/formats/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
syft/formats/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
syft/formats/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
syft/formats/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
syft/formats/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
syft/pkg/cataloger/deb/cataloger_test.go
syft/pkg/cataloger/deb/package.go
syft/pkg/cataloger/deb/parse_dpkg_db.go
syft/pkg/cataloger/deb/parse_dpkg_db_test.go
syft/pkg/cataloger/deb/test-fixtures/status/coreutils-relationships
syft/pkg/cataloger/deb/test-fixtures/status/doc-examples
syft/pkg/cataloger/deb/test-fixtures/status/libpam-runtime
syft/pkg/dpkg_metadata.go

This adds package relationships for debian packages. Specifically the `Depends`, `Pre-Depends`, and `Provides` dpkg status fields are supported, crafting relationships only for installed packages (which for these fields tends to be the case).
This PR does not add dependencies for build-related dependencies (e.g. the `Build-Depends`, `Build-Depends-Indep`, `Build-Depends-Arch`, `Build-Conflicts`, `Build-Conflicts-Indep`, and `Build-Conflicts-Arch` fields) or non-required but related relationships (e.g. the `Recommends`, `Suggests`, `Breaks`, `Conflicts`, `Replaces`, and `Enhances` fields).
Partially addresses #572 
Closes #2040

Add relationships for dpkg packages

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go

Closes #2147
If the jar doesn't have a Bundle-License in the Manifest, or a pom.xml in the archive with the declared license, it falls back to look for a valid license in either the root directory of the jar or in META-INF. I don't think it's necessary to check anywhere else for a license in a jar.
With this fix Syft correctly detects licenses for:
- https://repo1.maven.org/maven2/xerces/xercesImpl/2.12.2/ (META-INF/LICENSE)
- https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/5.1.1/ (LICENSE.txt in root directory)

Detect a license file in the root directory or META-INF of a jar

---

internal/licenses/list.go

These additions help Syft to correctly identify licenses for:
- The widely deployed Spring framework (https://repo1.maven.org/maven2/org/springframework/spring-core/6.0.12/) which has a license in META-INF/license.txt
- https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/5.13.0/ which has licenses in AL2.0 and LGPL2.1 filenames.
For the first point we could instead do a case insensitive check on the filenames, but I thought that was probably overkill.

Add additional license filenames

---

go.mod
go.sum

Pull in https://github.com/anchore/clio/pull/29 to fix a regression (errors should be shown to stderr not stdout).

Report errors to stderr not stdout

---

syft/formats/common/spdxhelpers/download_location.go
syft/formats/common/spdxhelpers/download_location_test.go

See #2102 - this signs off the commits and sets DCO to pass while still giving credit to the author

Add download location when cataloging directory npm package lock

---

.github/scripts/labeler.py
.github/scripts/labeler_test.py
.github/workflows/labeler.yaml
.gitignore
DEVELOPING.md
Makefile

Closes #1938
This adds a utility that will label all new PRs (from forks or internal branches) based on the following criteria:
- if there is a new, deleted or modified json schema then a `json-schema` label will be added to the PR
- if the major version of the new schema version is greater than the major version of the current schema then a `breaking-change` label will be added to the PR
- if a former json schema file is modified or removed, then a sticky comment on the PR will be added warning of a possible issue. This is not necessarily a breaking change or should block the PR since there may be other reason why this change is valid. If a new commit resolves the issue (no more modified or removed schemas) then the stick comment is automatically hidden (folded). If new commits are added …

Label PRs when the json schema changes

---

.github/workflows/release-homebrew.yaml

It looks like for the first release we expected the homebrew release workflow to run it was not triggered. I've adjusted the event types to account for this (🤞 ) and also added `workflow_dispatch` to trigger outside of a release.

Fix homebrew post-release workflow

---

.github/workflows/release-homebrew.yaml

I don't this think fully fixes the homebrew workflow, however, it seems that someone has already put in a PR for the latest syft release, I'll have to give this a go on the next release. These changes improve the behavior, but I was still running into a failure due to token permissions and forking.

Troubleshoot homebrew release workflow

---

syft/pkg/cataloger/cataloger.go
syft/pkg/cataloger/cpp/cataloger.go
syft/pkg/cataloger/cpp/cataloger_test.go
syft/pkg/cataloger/cpp/package.go
syft/pkg/cataloger/cpp/parse_conaninfo.go
syft/pkg/cataloger/cpp/parse_conaninfo_test.go
syft/pkg/cataloger/cpp/test-fixtures/conaninfo/mfast/1.2.2/my_user/my_channel/package/9d1f076b471417647c2022a78d5e2c1f834289ac/conaninfo.txt

Currently, syft only supports parsing conanfile.txt or conan.lock files.
If a conan package is installed inside a docker container (e.g., in $HOME/.conan/data), then this is not detected by syft.
With this MR the corresponding functionality is added.
I.e., every installed conan package contains a `conaninfo.txt`.
We can use this in the globbing to detect the packages and then parse the additional conan package information.

feat: add conaninfo.txt parser to detect conan packages in docker images

---

.github/workflows/update-cpe-dictionary-index.yml

The CPE index update workflow has been silently failing, this PR addresses the reason for the failure and adds a slack notification upon failure.
Example run from this branch: https://github.com/anchore/syft/actions/runs/6628634544

Fix CPE index workflow

---

syft/pkg/cataloger/java/parse_java_manifest.go
syft/pkg/cataloger/java/parse_java_manifest_test.go
syft/pkg/cataloger/java/test-fixtures/manifest/leading-space

This PR removes the `strings.TrimSpace` call which was abruptly ending a manifest parse when a continuation was expected.
This PR adds a test to make sure the continuations are included in the previous fields while still allowing the parser to move forward and catalog the entire document.
Warning levels for this function have been reduced to debug in response to the dev note from #2179

2179 jar chokes empty lines

---

internal/file/zip_file_manifest.go
internal/file/zip_file_manifest_test.go
internal/licenses/list.go
syft/pkg/cataloger/java/archive_parser.go

Following on from https://github.com/anchore/syft/pull/2227, perform case insensitive matching in GlobMatch so that we can check all license files in a case insensitive manner.

Perform case insensitive matching on Java License files

---

Taskfile.yaml

Example of earlier failure: https://github.com/anchore/syft/runs/18167378102#step:5:7

chore: fix cpe generation task

---

README.md

Fixes #2269 
Signed-off-by: Timothy Gerla <tim@gerla.net>

Update README.md to use canonical output format names (fixes #2269)

---

syft/pkg/cataloger/java/parse_gradle_lockfile.go
syft/pkg/cataloger/java/parse_gradle_lockfile_test.go

This adds PURLs when scanning Gradle lock files.
Unintuitively the correct PURL type appears to be `maven` as opposed to `gradle`. See https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst
- `gradle` for Gradle plugins
- `maven` for Maven JARs and related artifacts

add PURLs when scanning Gradle lock files

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go
syft/pkg/cataloger/java/test-fixtures/jar-metadata/Makefile
syft/pkg/cataloger/java/test-fixtures/jar-metadata/README.md
syft/pkg/cataloger/java/test-fixtures/jar-metadata/api-all-2.0.0-sources/META-INF/MANIFEST.MF
syft/pkg/cataloger/java/test-fixtures/jar-metadata/api-all-2.0.0-sources/META-INF/maven/org.apache.directory.api/api-all/pom.properties
syft/pkg/cataloger/java/test-fixtures/jar-metadata/api-all-2.0.0-sources/META-INF/maven/org.apache.directory.api/api-all/pom.xml
syft/pkg/cataloger/java/test-fixtures/jar-metadata/api-all-2.0.0-sources/META-INF/maven/org.apache.directory.api/api-asn1-api/pom.properties
syft/pkg/cataloger/java/test-fixtures/jar-metadata/api-all-2.0.0-sources/META-INF/maven/org.apache.directory.api/api-asn1-api/pom.xml

The restriction to only parse one pom.xml / pom.properties in the archive fails for certain jars that shade multiple dependencies into the jar. For example:
https://repo1.maven.org/maven2/org/apache/directory/api/api-all/2.0.0/
which has:
```
./META-INF/maven/org.apache.directory.api/api-ldap-extras-codec-api/pom.xml
./META-INF/maven/org.apache.directory.api/api-all/pom.xml
./META-INF/maven/org.apache.directory.api/api-ldap-schema-converter/pom.xml
./META-INF/maven/org.apache.directory.api/api-ldap-extras-trigger/pom.xml
./META-INF/maven/org.apache.directory.api/api-ldap-extras-sp/pom.xml
./META-INF/maven/org.apache.directory.api/api-util/pom.xml
./META-INF/maven/org.apache.directory.api/api-ldap-net-mina/pom.xml
./META-INF/maven/org.apache.directory.api/api-ldap-codec-standalone/pom.xml …
```

Syft does not handle the case of parsing a jar with multiple poms

---

syft/pkg/cataloger/golang/licenses.go
syft/pkg/cataloger/golang/licenses_test.go
syft/pkg/cataloger/golang/test-fixtures/licenses/pkg/mod/github.com/someorg/strangelicense@v1.2.3/LiCeNsE.tXt

Similar to the change in #2235, this allows the Go license cataloger to match license files in Go modules in a case-insensitive way.
This allows detection of licenses such as: https://github.com/kr/pretty/blob/v0.3.1/License (without having to add every variation/spelling of license files).

Use case-insensitive matching for Go license files

---

syft/format/cyclonedxjson/decoder.go
syft/format/cyclonedxjson/decoder_test.go
syft/format/cyclonedxjson/test-fixtures/identify/micronaut-1.4.json
syft/format/cyclonedxjson/test-fixtures/identify/micronaut-1.5.json

This PR corrects an issue that identifying CycloneDX JSON documents was being too strict, requiring the `$schema` field be present. Whether this is required or not, Syft can be a bit more lax about parsing CycloneDX JSON and just look for the `bomFormat` and `specVersion` fields.
Fixes #2299

fix: identify CycloneDX JSON without $schema

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go

The code currently only checks Maven Central for a license in a parent pom for the topmost package, and not for any embedded jars.
With this PR it detects a license correctly for xbean-spring which is embedded inside activemq-osgi: https://repo1.maven.org/maven2/org/apache/activemq/activemq-osgi/5.18.2/

Check maven central as well for licenses in parents poms for nested jars

---

syft/source/file_source.go
syft/source/file_source_test.go

I noticed when generating a SPDX SBOM for https://repo1.maven.org/maven2/org/apache/activemq/activemq-osgi/5.18.2/ that it outputs:
```
{
"name": "activemq-osgi-5.18.2.jar",
"SPDXID": "SPDXRef-DocumentRoot-File-activemq-osgi-5.18.2.jar",
"versionInfo": "sha256:sha256:cfbaa968953d5c3a45c8d1e6fcdbcd22aa448baceebb00879084da0a38f1392d",
"supplier": "NOASSERTION",
"downloadLocation": "NOASSERTION",
"filesAnalyzed": false,
"checksums": [
{
"algorithm": "SHA256",
"checksumValue": "cfbaa968953d5c3a45c8d1e6fcdbcd22aa448baceebb00879084da0a38f1392d"
}
],
"primaryPackagePurpose": "FILE"
}
~
```
Note duplicate sha256 tag for versionInfo. This is because in fileSource.deriveIDFromFile, the digest algorithm is already encoded in the digest String.

SPDX file has duplicate sha256 tag in versionInfo

---

internal/constants.go
schema/json/schema-12.0.1.json
syft/file/location.go
syft/format/syftjson/encoder_test.go
syft/format/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
syft/format/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
syft/format/syftjson/test-fixtures/snapshot/TestImageEncoder.golden

This is a follow up to #2259 , where the API now populates the `VirtualPath` field on `file.Location` objects. This updates the JSON schema to v12.0.1 to reflect the new `accessPath`  element.
Partially addresses #1835  (using `accessPath` here instead of `virtualPath`)
Closes #1836

Add accessPath on Location objects to syft-json output

---

syft/pkg/cataloger/java/archive_parser.go

If a Java archive doesn't contain either a pom.xml or pom.properties or a license file, Syft doesn't find an associated license. This PR extends the functionality to search in maven central, this time using groupIDFromJavaMetadata, which can find the right group Id / artifact Id using information stored in the Java Manifest file.
With this PR Syft can find licenses for:
- https://repo1.maven.org/maven2/com/mchange/c3p0/0.9.5.5/
- https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15to18/1.75/
- https://repo1.maven.org/maven2/org/hibernate/hibernate-core/5.4.24.Final/

Fall back to searching maven central using groupIDFromJavaMetadata

---

syft/pkg/cataloger/common/cpe/java_groupid_map.go

Older syft versions correctly identified the maven groupId for the velocity jars as `org.apache.velocity`, but some of our recent adjustments caused these to start being reported as just `org.apache`, so this adds a manual namespace mapping to fall back on to correct the regression for this specific case

fix(java): add manual groupid mappings for org.apache.velocity jars

---

syft/format/syftjson/to_format_model.go

This allows for users that are interested in the other `syft-json` helpers to also be able to synthesize the correct type name from the metadata payload without needing to transform the entire package.

Export syft-json format package metadata type helper

---

syft/source/file_source.go
syft/source/file_source_test.go
syft/source/test-fixtures/symlink
test/cli/symlink_test.go

Previously, building the index of the filesystem when source was file would fail if part of the path syft was passed to the file included a symlinked directory, resulting in cataloging misses.
Fixes #2355. 
Note that this doesn't fix #1962 yet. I'll see if it can.

fix: index file itself when file scan path has symlink

---

syft/source/scope.go
syft/source/scope_test.go

This changes all instances of enum-like values in the API to lowercase / hyphen delimited. The only remaining instance is `source.Scope`. 
(This is work split off from #1383 )

Normalize enums to lowercase with hyphens

---

syft/pkg/cataloger/common/cpe/java_groupid_map.go

According to maven central, the package called "xalan" should just have the group ID xalan, but currently syft isn't able to find that (see https://mvnrepository.com/artifact/xalan/xalan/2.7.2)
Right now Grype fails to find https://github.com/advisories/GHSA-9339-86wc-4qgf because syft is generating the wrong group ID when scanning xalan jars.
Manual testing done:
``` sh
$ curl -s -o ~/work/scratch/xalan-2.7.2.jar https://repo1.maven.org/maven2/xalan/xalan/2.7.2/xalan-2.7.2.jar
$ syft -q -o json ~/work/scratch/xalan-2.7.2.jar | grype
No vulnerabilities found
$ go run cmd/syft/main.go -q -o json ~/work/scratch/xalan-2.7.2.jar | grype
NAME   INSTALLED  FIXED-IN  TYPE          VULNERABILITY        SEVERITY
xalan  2.7.2      2.7.3     java-archive  GHSA-9339-86wc-4qgf  High
```

fix: hardcode xalan group ID

---

cmd/syft/cli/cli.go
cmd/syft/cli/commands/root.go
test/cli/symlink_test.go

This PR applies the fix from PR #2335 to the root command for capturing stdout.
Fixes #2356

fix: capture root command stdout

---

syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable.go

While looking in to an issue that a library parsing DotNET Portable Executables was writing to stdout, I noticed a number of warnings show up, for example, running:
```
syft --platform windows/amd64 registry:mcr.microsoft.com/windows/servercore:ltsc2019
```
Resulted in:
```
✔ Parsed image                                                                                           sha256:c632661e39bb365cf34bfdd943baa4ce5ba1ebdd713d790d1af0b9da20ae0bea
✔ Cataloged packages              [4566 packages]  
[0084]  WARN cataloger failed cataloger=dotnet-portable-executable-cataloger error=unable to parse PE file: DOS Header magic not found location=/Files/Windows/WinSxS/x86_microsoft
[0084]  WARN cataloger failed cataloger=dotnet-portable-executable-cataloger error=unable to parse PE file: DOS …
```

fix: logging level for parsing potential PE files

---

syft/file/cataloger/filemetadata/cataloger.go
syft/file/cataloger/filemetadata/cataloger_test.go

There are two reasons why the file metadata cataloger is not working today when provided explicit file coordinates:
- the channel was immediately closed, so no results could have ever been provided
- we trust the user-provided coordinates exist in the resolver. This can cause a few issues relating to the stereoscope file reference object not being available (or the coordinates are not correct). Either way, the coordinates need to be resolved to a  full location object.
Note: this execution path is not used since it is only possible to catalog all locations today (instead of a certain subset, which  when done these issues start to be noticed).
(This was broken off from #1383 )

Fix file metadata cataloger when passed explicit coordinates

---

syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable.go
syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable_test.go
test/integration/catalog_packages_cases_test.go

This PR attempts to improve the dotnet portable executable identification.
Fixes: #2029 
In order to try to determine reasonable behavior, I created [a spreadsheet of all the PE Version Resources](https://docs.google.com/spreadsheets/d/1GE9T38JFgkiKzhIW7N-KDwaNiuomBojAavchZNnxfXY/edit?usp=sharing) from:
* ghcr.io/linuxserver/grav:1.7.42.3-ls124
* https://www.nuget.org/packages/prometheus-net.AspNetCore/8.0.1
* https://github.com/saferwall/pe/tree/main/test
* mcr.microsoft.com/windows/servercore:ltsc2019
* mcr.microsoft.com/windows-cssc/python:3.9-nanoserver-ltsc2019
The general pattern in this limited data set seems to be: Microsoft PE files used the `FileDescription` while non-Microsoft vendors provided reasonable values in the `ProductName`. Additionally, this PR attempts to improve …

fix: improve dotnet portable executable identification

---

syft/pkg/cataloger/common/cpe/java_groupid_map.go

grype fails to match vulns such as https://github.com/advisories/GHSA-q24v-hpg3-v3jp because syft generates an incorrect groupid (`io.projectreactor.netty.reactor-netty-http` rather than just `io.projectreactor.netty`) for `reactor-netty*` artifacts.  This adds a manual mapping to the correct expected maven namespace for these artifacts when no better source of identification is available

fix(java): improve identification for io.projectreactor.netty artifacts

---

go.mod
go.sum

Previously, pointers to primitive types in config summarization could be printed literally (like "0x123aefef"). Pull in fangs to get the fix for this.
Bump fangs to pull in https://github.com/anchore/fangs/pull/31
Testing:
Before change:
``` sh
$ syft help | rg pretty
pretty: 0x140002ff360
pretty: false
pretty: false
pretty: false
pretty: false
```
after change:
``` sh
$ go run cmd/syft/main.go help | rg pretty
pretty:
pretty: false
pretty: false
pretty: false
pretty: false
```

fix: bump fangs for ptr summarize fix

---

syft/pkg/cataloger/python/package.go
syft/pkg/cataloger/python/parse_wheel_egg.go
syft/pkg/cataloger/python/parse_wheel_egg_metadata.go
syft/pkg/cataloger/python/parse_wheel_egg_metadata_test.go

Syft only finds Python licenses if the Wheel metadata contains a "License" entry. This PR adds support to also parse the License-File entry. With this PR, Syft finds licenses for these packages:
> /PyGithub:1.58.2,LGPL-3.0-only
> /django-watson:1.6.3,BSD-3-Clause
> /setuptools:65.5.1,MIT
Further PRs will follow with enhanced support.

Parse Python licenses from LicenseFile entry in the Wheel Metadata

---

syft/pkg/cataloger/python/package.go
syft/pkg/cataloger/python/parse_wheel_egg_metadata.go
syft/pkg/cataloger/python/parse_wheel_egg_metadata_test.go

This allows Syft to obtain a license for https://pypi.org/project/attrs/ which lists the license using license-expression https://peps.python.org/pep-0639/#add-license-expression-field

Parse Python licenses from LicenseExpression entry in the Wheel Metadata

---

syft/file/cataloger/filedigest/cataloger.go
syft/file/cataloger/filedigest/cataloger_test.go
syft/file/cataloger/filemetadata/cataloger_test.go

This is the same fix as done in #2370 but for the file digest cataloger.
(Found while working on #1383 )

Fix file digest cataloger when passed explicit coordinates

---

syft/cataloging/config.go
syft/pkg/cataloger/java/config.go

This modifies the java cataloger configuration to use the common ArchiveSearchConfig default constructor (also added in this PR). This sets a pattern where other catalogers that want to use this common behavior can at least inherit from a single source of truth. 
(Work broken off from #1383)

Use common archive catalog configuration

---

syft/pkg/cataloger/javascript/config.go
syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_yarn_lock_test.go

Today the javascript cataloger configuration does not expose the fields on the config struct. There are two reasons to expose these fields:
- it will be necessary to create a JSON representation of the config struct in #1383  (which is why struct tags were added)
- simple options should be allowed to be set simply without requiring behavior (methods to be called)
This does not remove any of the builder/fluent API methods in place now.

Expose javascript fields in cataloger configuration

---

syft/pkg/collection.go

Remove "catalog" references from source and comments. Also adds a separate `add()` function to improve readability.
(Broken off from #1383 )

chore: refactor pkg.Collection to remove "catalog" references

---

syft/format/syftjson/encoder_test.go

Without this fix, capturing fixtures will result in hard-to-read failures in testing. (broken off from #1383 )

Fix syft-json snapshot test to use pretty json

---

syft/pkg/cataloger/erlang/erlang_parser.go
syft/pkg/cataloger/erlang/erlang_parser_test.go

Functionality:
* Empty lists
* Single quote strings
* Comments
This allow supporting this erlang file from RabbitMQ (edited for brevity)
```erlang
{application, 'rabbit', [
{description, "RabbitMQ"},
{vsn, "3.12.10"},
{id, "v3.12.9-9-g1f61ca8"},
{modules, ['amqqueue','background_gc']},
{optional_applications, []},
{env, [
{memory_monitor_interval, 2500},
{disk_free_limit, 50000000}, %% 50MB
{msg_store_index_module, rabbit_msg_store_ets_index},
{backing_queue_module, rabbit_variable_queue},
%% 0 ("no limit") would make a better default, but that
%% breaks the QPid Java client
{frame_max, 131072},
%% see rabbitmq-server#1593
{channel_max, 2047}
]}
]}.
```

Add more functionality to the ErLang parser

---

syft/pkg/language.go
syft/pkg/language_test.go

Otherwise, Grype won't match on well-formed .NET purls from other SBOM tools.
Will fix https://github.com/anchore/grype/issues/1065 when Syft is released and Syft is bumped in Grype.

PURLs with "nuget" type are dotnet packages

---

cmd/syft/cli/cli.go
cmd/syft/cli/commands/attest.go
cmd/syft/cli/commands/packages.go
cmd/syft/cli/commands/root.go
cmd/syft/cli/commands/scan.go
syft/source/detection.go
test/cli/cyclonedx_valid_test.go
test/cli/json_schema_test.go
test/cli/root_cmd_test.go
test/cli/scan_cmd_test.go
test/cli/spdx_json_schema_test.go
test/cli/spdx_tooling_validation_test.go
test/cli/symlink_test.go

One of the original ideas for syft was to expand the scope of the tooling to generally answer the question "what are all of the things that are in my artifact" even for things that might not fit into an SBOM. This has sense been focused down to items that can be expressed in an SBOM (which is why the secrets cataloger was removed for instance). For the same reason, as described in #516 , the `packages` command no longer makes sense as a name (since we are always creating SBOMs from what we scan, instead of only showing packages or <other noun here that was not implemented>). This PR addresses this by  deprecating the current `packages` command in favor of `scan` (still aliasing to the root command). 
So any current usage of the `packages` command command...
```
syft packages <input>
``` …

Replace `packages` command with `scan`

---

syft/pkg/cataloger/binary/cataloger_test.go

Before this change there were a lot of fatal errors
i.e.
```
Exception has occurred: panic
"MetadataType: does not exist"
```
```
Exception has occurred: panic
"cannot handle unexported field at Locations({pkg.Package}.Locations)...
```
```
Exception has occurred: panic
"cannot handle unexported field at {pkg.Package}.Licenses.set:\n\t\"g...
```
After the change:
```
Error:      	locations do not match; expected: haproxy1 got: haproxy
```

Fix diff error obfuscating binary test failures message

---

syft/pkg/cataloger/binary/cataloger.go
syft/pkg/cataloger/binary/cataloger_test.go
syft/pkg/cataloger/binary/classifier.go
syft/pkg/cataloger/binary/classifier_test.go

The last rebase of #1383 resulted in bringing in changes from #2469 , which makes the configuration in the JSON output prohibitively large:
```
syft <anything> -o json | jq '.descriptor.configuration.packages'
```
```json 
"packages": {
"binary": {
"classifiers": [
{
"class": "python-binary",
"cpes": [
{
"Edition": "",
"Language": "",
"Other": "",
"Part": "a",
"Product": "python",
"SWEdition": "",
"TargetHW": "",
"TargetSW": "",
"Update": "",
"Vendor": "python_software_foundation",
"Version": ""
},
{
"Edition": "",
"Language": "",
"Other": "",
"Part": "a",
"Product": "python",
"SWEdition": "",
"TargetHW": "",
"TargetSW": "",
"Update": "",
"Vendor": "python",
"Version": ""
}
],
"fileGlob": "**/python*",
"package": "python",
"purl": {
"Name": "python",
"Namespace": "",
"Qualifiers": [], …
```

Condense binary cataloger config in JSON output

---

syft/cataloging/pkgcataloging/config.go

This adds the binary cataloger configuration defaults to the default package config. This was missed on a rebase of the #1383 .

Include binary cataloger configuration defaults

---

syft/create_sbom.go
test/integration/regression_sbom_duplicate_relationships_test.go

Closes #2509 
This PR removes the double call to `relationships.Finalize`.
To validate the fix run the following using the latest release of syft:
```
syft cgr.dev/chainguard/coredns@sha256:238f7d4cff40ffa7262ae5508481722fe3213e4aae1e61a1425f07f4ae2e4d71 -qo json | jq .artifactRelationships > test.json
```
Then using this gist you can evaluate the output relationships from above and find the dupes:
https://gist.github.com/spiffcs/72b641f04ac79d160ce079bcd3816382
```
Duplicate relationship: Parent=007a689559786815, Child=0fdca611631006c5 Type=ownership-by-file-overlap
Duplicate relationship: Parent=007a689559786815, Child=fe672ea9910662d8 Type=evident-by
Duplicate relationship: Parent=014167b5dbcc5b66, Child=2d14b57d501102cf Type=evident-by
Duplicate relationship: Parent=02619b1e06d34738, …
```

fix: remove second call to finalize as the task handles it

---

cmd/syft/cli/options/file.go
cmd/syft/cli/options/file_test.go
cmd/syft/cli/options/source.go
cmd/syft/cli/options/source_test.go
internal/file/digest.go
internal/file/normalize_hashes.go
internal/file/normalize_hashes_test.go
syft/cataloging/filecataloging/config.go
syft/file/cataloger/filedigest/cataloger.go

Today if a user provides duplicate digests via syft application configuration:
```
file:
metadata:
digests: ["sha256", "sha256"]
```
or by the api:
```
syft.DefaultCreateSBOMConfig().
WithFilesConfig(
filecataloging.DefaultConfig().
WithHashers(
[]crypto.Hash{
crypto.SHA256,
crypto.SHA256,
},
),
)
```
This will result in twice the work and output:
```
$ go run ./cmd/syft -q alpine:latest -o json | jq '.files[0].digests'
[
{
"algorithm": "sha256",
"value": "b40e37517d32d4df5d3b3ed924295f118b4965fa6a659d0db43a796a58fdafff"
}
{
"algorithm": "sha256",
"value": "b40e37517d32d4df5d3b3ed924295f118b4965fa6a659d0db43a796a58fdafff"
}
]
```
This PR addresses this issue by:
- deduplicating when reading the application configuration, addressing config display concerns
- deduplicating when providing …

Deduplicate digests from user configuration

---

internal/task/package_tasks.go
test/cli/scan_cmd_test.go
test/cli/trait_assertions_test.go
test/integration/package_catalogers_represented_test.go

It seems that the linux kernel cataloger was inadvertently dropped from the list of catalogers to use when cataloging. This PR re-introduces that cataloger as well as adds two integration tests to defend against future regressions similar to this:
- a test that looks for package constructor definitions in source code and correlates them in the single `package_tasks.go` location where they are wired
- another test that correlates constructed tasks names with the length of known package constructors
Each test by itself has tradeoffs/assumptions (e.g. hard coded file paths, looking for function conventions by glob, etc.) but adding both helps reduce the risk of those assumptions.
Fixes #2524

Re-introduce linux kernel cataloger

---

internal/task/package_tasks.go
test/integration/package_catalogers_represented_test.go
test/integration/sbom_cataloger_test.go

This removes the `sbom-cataloger` from the default set of catalogers used for any scan. If a user would like SBOM contents to be considered then that is an opt-in action:
```
syft --select-catalogers +sbom-cataloger
```
Fixes #1555
~Must merge #2526 first~

Turn off the SBOM cataloger by default

---

syft/format/cyclonedxjson/decoder.go
syft/format/cyclonedxxml/decoder.go
syft/format/decoders.go
syft/format/internal/cyclonedxutil/decoder.go
syft/format/internal/stream/seekable_reader.go
syft/format/internal/stream/seekable_reader_test.go
syft/format/spdxjson/decoder.go
syft/format/spdxtagvalue/decoder.go
syft/format/syftjson/decoder.go
syft/sbom/format.go

This changes the interface for format decoding to accept a more forgiving `io.Reader` instead of requiring a `io.ReadSeeker` for all calls. When provided a `io.ReadSeeker` then the execution will not change, however, when provided a reader without seeking capabilities under the hood it will decorate the reader with a bytes buffer initialized with the reader contents. This can be swapped in the future for a reader that can just-in-time reason about ad-hoc Read and Seek calls to do the same thing more efficiently, however, for the initial implementation a simpler route was taken. This saves callers from having to do the "read-content-and-wrap-with-readseeker" in cases where they do not have a read seeker handy (which is common for non-file IO).

Swap format uses of io.ReadSeeker for io.Reader

---

syft/cpe/by_specificity.go
syft/cpe/cpe.go
syft/cpe/cpe_test.go
syft/format/common/cyclonedxhelpers/cpe.go
syft/format/common/cyclonedxhelpers/format.go
syft/format/common/spdxhelpers/external_refs.go
syft/format/common/spdxhelpers/external_refs_test.go
syft/format/syftjson/to_format_model.go
syft/pkg/cataloger/binary/classifier_test.go
syft/pkg/cataloger/common/cpe/filter.go
syft/pkg/cataloger/common/cpe/generate.go
syft/pkg/cataloger/common/cpe/generate_test.go
syft/pkg/cataloger/golang/cataloger_test.go

Previously, Syft re-exported wfn.Attributes from the nvdtools package as a member of the Package struct. However, Syft doesn't own this struct, and so after Syft 1.0, might be forced to bump a semver major version due to a breaking change in wfn.Attributes. Rather than incur this risk going into 1.0, instead replace Syft's use of wfn.Attributes with Syft's own cpe.CPE type. That type has some pass-through calls to wfn.Attributes, but hides the dependency from the rest of the application.
Fixes #2529 .

chore: stop re-exporting wfn.Attributes

---

internal/constants.go
schema/json/schema-14.0.0.json
syft/pkg/cataloger/redhat/parse_rpm_db.go
syft/pkg/cataloger/redhat/parse_rpm_db_test.go
syft/pkg/rpm.go

Ultimately we need to distinguish between the states of is there a modularity label that can even be expressed vs an empty modularity label value in the RPM DB. This PR makes this adjustment.
The use case for this is really in grype, where there is vulnerability information from redhat that mostly tailored with modularity labels in mind. We should not attempt to use modularity logic if the SBOM which the SBOM was sourced from cannot positively express modularity information.

Allow for RPM modularity to be optional

---

syft/cataloging/pkgcataloging/config.go
syft/pkg/cataloger/binary/cataloger.go
syft/pkg/cataloger/cpp/parse_conanfile.go
syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/java/cataloger.go
syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
syft/pkg/cataloger/java/parse_gradle_lockfile.go
syft/pkg/cataloger/kernel/cataloger.go
syft/pkg/cataloger/nix/cataloger.go
syft/pkg/cataloger/python/cataloger.go
syft/pkg/cataloger/python/parse_pipfile_lock.go
test/integration/package_cataloger_convention_test.go

This PR attempts to reduce the surface area of functions and types exported from the `syft/pkg/cataloger/**` packages.
This additionally adds an integration test to ensure that catalogers added are following conventions:
- Cataloger constructor functions should follow the glob `New*Cataloger`
- Config structs must be named `*Config` and must be paired with a zero parameter function called `Default*Config`

Unexport types and functions cataloger packages

---

README.md
cmd/syft/internal/options/format_template.go
syft/format/encoders.go
syft/format/template/encoder.go
syft/format/template/encoder_test.go
syft/format/template/test-fixtures/csv-hasField.template
syft/format/template/test-fixtures/csv.template
syft/format/template/test-fixtures/legacy/csv-hasField.template
syft/format/template/test-fixtures/legacy/csv.template
syft/format/template/test-fixtures/snapshot/TestFormatWithOptionAndHasField_Legacy.golden
syft/format/template/test-fixtures/snapshot/TestFormatWithOption_Legacy.golden
test/cli/test-fixtures/csv.template

The template functionality today uses the go struct fields from the `syft/format/syftjson/model` directory as input, which means that in order to write a template you need to read the syft source code. For instance:
```
"Package","Version Installed", "Found by"
{{- range .Artifacts}}
"{{.Name}}","{{.Version}}","{{.FoundBy}}"
{{- end}}
```
- `Artifacts` approximates to `artifacts` in the json schema
- `Name` approximates to `name` in the json schema
- `Version` approximates to `version` in the json schema
- `FoundBy` approximates to `foundBy` in the json schema
This change adapts the template input to require the same fields as what you will find in the JSON output of syft (exactly what's in the json schema):
```
"Package","Version Installed", "Found by"
{{- range .artifacts}} …
```

Use the json schema as input for templating

---

syft/pkg/cataloger/golang/package.go
syft/pkg/cataloger/golang/package_test.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

This PR implements the subpath portion of the Purl spec for golang and prevents the subpath from being reported as the package name.
i.e.
```
github.com/coreos/go-systemd/v22
```
Is now reported as `go-systemd` instead of `v22`

Implement golang Purl subpath

---

.binny.yaml
.goreleaser.yaml
test/install/1_download_snapshot_asset_test.sh
test/install/environments/Dockerfile-alpine-3.6
test/install/environments/Dockerfile-ubuntu-20.04

This PR enhances what is produced at release:
- adds signature of the checksums.txt file produced on each release
- adds SBOMs for released binary archives
Here is a tree of the snapshot dir with these changes:
```
snapshot
├── ...
├── metadata.json
├── syft_0.101.1-SNAPSHOT-edc0217a_checksums.txt
├── syft_0.101.1-SNAPSHOT-edc0217a_darwin_amd64.sbom
├── syft_0.101.1-SNAPSHOT-edc0217a_darwin_amd64.tar.gz
├── syft_0.101.1-SNAPSHOT-edc0217a_darwin_arm64.sbom
├── syft_0.101.1-SNAPSHOT-edc0217a_darwin_arm64.tar.gz
├── syft_0.101.1-SNAPSHOT-edc0217a_linux_amd64.deb
├── syft_0.101.1-SNAPSHOT-edc0217a_linux_amd64.rpm
├── syft_0.101.1-SNAPSHOT-edc0217a_linux_amd64.sbom
├── syft_0.101.1-SNAPSHOT-edc0217a_linux_amd64.tar.gz
├── syft_0.101.1-SNAPSHOT-edc0217a_linux_arm64.deb
├── …
```

Sign checksums file and add SBOMs on release

---

syft/pkg/cataloger/java/parse_java_manifest.go
syft/pkg/cataloger/java/parse_java_manifest_test.go

This fixes an issue where filenames containing a period that aren't a group ID, such as some-jar.12.jar, would be mistakenly be reported as having the name "12" by syft, instead of the name "some-jar.12".
Fixes #2563.

fix: Better test for group ID in filename

---

go.mod
go.sum

Pulls in fixes from:
- https://github.com/anchore/stereoscope/pull/214. ([GHSA-hpxr-w9w7-g4gv](https://github.com/anchore/stereoscope/security/advisories/GHSA-hpxr-w9w7-g4gv))
- https://github.com/anchore/archiver/pull/1 ([CVE-2024-0406](https://nvd.nist.gov/vuln/detail/CVE-2024-0406))
To address various tar path traversal bugs, specifically when malicious tar files are passed to syft (e.g. `syft ./path/to/my.tar`).

Bump archiver and stereoscope to address path traversal issues

---

.github/workflows/release.yaml
.goreleaser.yaml

This PR re-adds the cosign signing checksums file, this time with the [appropriate token permissions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings)

Re-add cosign signing checksums file

---

cmd/syft/cli/cli.go
cmd/syft/internal/clio_setup_config.go
cmd/syft/internal/commands/attest.go
cmd/syft/internal/commands/attest_test.go
cmd/syft/internal/commands/commands_test.go
cmd/syft/internal/options/attest.go
go.mod
go.sum
test/cli/scan_cmd_test.go

Pull request adding a new testing pattern for CLIs, based on work over in clio: https://github.com/anchore/clio/pull/37
Some feedback on this PR might inform https://github.com/anchore/clio/pull/37, and this is meant to be merged after https://github.com/anchore/clio/pull/37.
Fixes https://github.com/anchore/syft/issues/2544
* Pulls in updated clio to add unit tests for `SYFT_ATTEST_PASSWORD` env var and `--key` flag on `attest` subcommand.
* https://oci.dag.dev/?blob=ghcr.io%2Fwillmurphyscode%2Ftest_image%40sha256%3A7c20f7ae24e5e9abe27e4fbb21d4a217715ffd29c32085fc47ebde8c08da06ff&jq=.payload&jq=base64+-d&jq=jq&mt=application%2Fvnd.dsse.envelope.v1%2Bjson&size=10752 attestation was created by pushing a test image to ghcr and attesting it with local build of syft on this branch. (Command …

Fix attest with --key

---

syft/format/decoders.go
syft/pkg/cataloger/java/parse_java_manifest_test.go

#2515 accidentally was functionally reverted with https://github.com/anchore/syft/pull/2533 . This PR restores this functionality

Restore io.Reader in format API

---

examples/README.md
examples/create_custom_sbom/alpine_configuration_cataloger.go
examples/create_custom_sbom/main.go
examples/create_simple_sbom/main.go
examples/decode_sbom/alpine.syft.json
examples/decode_sbom/main.go
examples/source_detection/main.go
examples/source_from_image/main.go
syft/cataloging/filecataloging/config.go
syft/create_sbom_config_test.go

This is a starting point to showing how to use the Syft API to do common tasks such as:
- create an SBOM
- create a custom cataloger
- decode/encode an SBOM object from/to a particular format (e.g. SPDX, CycloneDX, Syft-JSON, etc)
- obtain a source object to catalog
This is partially completed at this point, I'm looking for feedback at this stage regarding two topics:
- what high-level examples do you wish were here but aren't?
- what sharp-edges in the API exist that might need refactoring?
Closes #558

Add API examples

---

syft/internal/packagemetadata/generated.go
syft/internal/packagemetadata/names.go
syft/internal/packagemetadata/names_test.go
syft/pkg/cataloger/cpp/package.go
syft/pkg/cataloger/cpp/parse_conanlock.go
syft/pkg/cataloger/cpp/parse_conanlock_test.go
syft/pkg/conan.go

In conan 2.x i see there is a `requries` field listing the packages instead of the `graph_lock`.
For spec change details see https://github.com/conan-io/tribe/blob/main/design/034-new_lockfiles.md. and https://docs.conan.io/2/tutorial/versioning/lockfiles.html#tutorial-versioning-lockfiles.

Add support for conan lock v2

---

schema/json/schema-latest.json
syft/internal/jsonschema/main.go

Because we generate a new JSON schema file every time the schema version changes, the git diff always shows that the file is completely new. Therefore, every time the file is re-generated, also write the schema to a stable path, so that the actual changes to the schema are easily visible in the git diff of the latest schema file.
**One piece of feedback I'm looking for**: the `schema-latest.json` file is really only used during diff, though it should always be byte for byte identical with the "real" JSON schema file (the one with the schema version in its filename). Is there anything needed to signal this distinction?

chore: copy latest schema to stable path for easier diff

---

.github/scripts/labeler.py
.github/scripts/labeler_test.py

Fixes when the PR labeler encounters the new [latest version](https://github.com/anchore/syft/pull/2586) file:
```
Run python .github/scripts/labeler.py
[RUN] gh pr view 2587 --json files --jq '.files.[].path'
Traceback (most recent call last):
File "/home/runner/work/syft/syft/.github/scripts/labeler.py", line 230, in <module>
main(changed_files, merge_base_schema_files)
File "/home/runner/work/syft/syft/.github/scripts/labeler.py", line 55, in main
og_json_schema_files = list_json_schema_files()
File "/home/runner/work/syft/syft/.github/scripts/labeler.py", line 179, in list_json_schema_files
return sort_json_schema_files(list(glob.glob("schema/json/schema-*.json")))
File "/home/runner/work/syft/syft/.github/scripts/labeler.py", line 200, in sort_json_schema_files
versions = …
```

Labeler should ignore latest version

---

syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable.go
syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable_test.go

When choosing the main version for a portable executable, always prefer the product version when it is semantically greater than the file version.  The file version can remain the same across multiple releases of a nuget package, but the product version increments.

fix(dotnet): prefer portable executable product version when semantically greater than file version

---

syft/format/syftjson/to_syft_model.go
syft/format/syftjson/to_syft_model_test.go

if a string is parsed into an int using strconv.Atoi, and subsequently that int is converted into another integer type of a smaller size, the result can produce unexpected values.
This PR adds an upper/lower bound check for the `int` when converting down to `int32` as the file.Mode
https://pkg.go.dev/os#FileMode <-- Points to `fs.FileMode`
https://pkg.go.dev/io/fs#FileMode <-- `fs.FileMode`

fix: incorrect conversion between integer types

---

syft/file/cataloger/executable/cataloger.go
syft/internal/unionreader/union_reader.go

Fix panic when processing SIF images

---

syft/format/common/cyclonedxhelpers/to_format_model.go
syft/format/common/cyclonedxhelpers/to_format_model_test.go
syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden

This PR adds a `BOMRef` to the output CycloneDX OS Component.
Fixes #2101

fix: add BOMRef to CycloneDX OS Component

---

.github/workflows/codeql-analysis.yml

Syft is seeing some failures in codeql because of HD issues. This runner update should give us enough space.

fix: update runner size to use larger HD for codeql

---

cmd/syft/internal/options/catalog.go
internal/task/package_tasks.go
syft/cataloging/pkgcataloging/config.go
syft/pkg/cataloger/binary/cataloger.go
syft/pkg/cataloger/binary/cataloger_test.go

Package catalogers and configurations should be named as specifically as possible to allow room for multiple implementations. In this case #2396 will land potentially another binary cataloger. Renaming this post v1 of syft will require bumping the major version.

Rename binary cataloger to be more unique

---

syft/format/syftjson/schema_test.go

This adds a test that ensures that new definitions added to the JSON schema strictly follow camel case conventions as described [here](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case). There were several exceptions found (this test should have been added a long time ago apparently), but I've decided to not break these fields and to move forward with exception. In a future major release we may decide to break these fields (in the encoding path, but still have decoders for the old shapes).

Test for field conventions in json schema

---

syft/internal/fileresolver/directory_indexer.go
syft/internal/fileresolver/directory_indexer_test.go
syft/internal/fileresolver/directory_test.go
syft/source/directory_source.go
syft/source/directory_source_test.go
syft/source/file_source.go

Fixes #2627
This updates the logic when considering paths to ignore/filter out during the indexing phase of the directory file resolver. Currently we ignore known common paths that mount to filesystems that provide no packages (e.g. `/dev` and `/proc`). This currently doesn't consider cases when the filesystem being scanned isn't mounted at root (when there is a `base-path` to consider). For example, when scanning `/some/mount/path` and there is a path `/some/mount/path/dev`, we should be considering that latter path during indexing to be `/dev`. Ultimately the index value is correct, but filter functions do not have the option to observe the value of `base-path` (i.e. `/some/mount/path`) to calculate the relative path of the target.
This PR changes the behavior to allow filter functions …

Fix considering base path when ignoring known bad unix paths

---

syft/create_sbom_config.go

When the new CreateSBOM function landed, it strongly separated the concerns of `main` from that of lib consumers. This restores some functionality, where today library consumers get no tooling information in SBOMs created. This PR changes this to at least hard code to `syft` and extract the version from the buildinfo section. This is a best-effort value, if the version cannot be extracted then it will remain blank.

Add syft version used to SBOM tool info by default

---

test/install/Makefile

There have been some [flaky test failures](https://github.com/anchore/syft/actions/runs/7978526536/job/21784016112#step:9:751) that all seem to stem from busybox wget usage and a possible solution found is to upgrade the image.

chore: update busybox image for acceptance tests

---

cmd/syft/internal/options/format.go
test/cli/all_formats_expressible_test.go

Using SPDX Tag-Value with a version selector was not working, instead defaulting to the latest version (`2.3`). This PR corrects the issue so selecting other versions works as expected, e.g. `spdx@2.2`.

fix: SPDX tag value version selector

---

syft/pkg/cataloger/golang/licenses.go

Previously, the TUI would hang when scanning directories with lots of go packages, possibly because this path was spamming the partybus with too many events. Since checking on a particular go module is fast, don't show TUI events for each one.
Fixes #2653 .
``` sh
echo 'golang:
search-local-mod-cache-licenses: true
local-mod-cache-dir: ""
search-remote-licenses: true
proxy: ""
no-proxy: ""' > .syft.yaml
go build -o /tmp/nsyft cmd/syft/main.go
/tmp/nsyft ~/work/clio # just a directory with a lot of go dependencies
```
On main, this hangs, but on the current branch, it does not. Happy to add additional testing but not sure how to repro the hang in CI.

fix: stop emitting bus events on go mod events

---

go.mod
go.sum
syft/internal/fileresolver/directory.go
syft/internal/fileresolver/directory_indexer.go
syft/internal/fileresolver/directory_indexer_test.go
syft/internal/fileresolver/directory_test.go

Implements [the suggestion](https://github.com/anchore/syft/issues/2667#issuecomment-1964744118) from @klakin-pivotal to look at the system mounts and determine if the filesystem types indicate which parts of the overall filetree to ignore when indexing for the directory file resolver.
Replaces #2668 
Fixes https://github.com/anchore/syft/issues/2667

Consider filesystem types for mount points when ignoring system paths

---

.chronicle.yaml

This changes the behavior of [chronicle](https://github.com/anchore/chronicle) when determining the next version during release to allow bumping of the major version when there are breaking changes.

Enforce breaking change bump major version

---

syft/pkg/cataloger/dotnet/package.go
syft/pkg/cataloger/dotnet/package_test.go

Previously, the path trimming regex would leave leading path separator in place on Windows.
Probably a better long term fix is to a library path operation.
Fixes #2264 
@wagoodman and I talked about this, and it doesn't seem like an underlying bug in the file abstraction, so I'm considering the investigation that was the last todo completed.

fix: trim path from deps.json in portable way

---

syft/format/table/encoder.go
syft/format/table/encoder_test.go
syft/format/table/test-fixtures/snapshot/TestTableEncoder.golden

The number of rows in the table output does not always match the TUI package counts when there are duplicate packages found (in terms of a `(name, version, type)` tuple). This PR adjusts the output to specifically indicate which rows are duplicated and by how much.
Closes #2672

Mark duplicated rows in table output

---

examples/source_from_registry/main.go

This just adds another simple example of the Syft API usage, which demonstrates how to use a specific source.

docs: add simplest example from regsitry

---

.github/workflows/release.yaml

In an effort to lock down our credentials and permissions in CI, we created various dockerhub and github accounts with different permissions. 
This update uses a more restricted dockerhub account's username/pat and github token that only grants what is relevant.

updating credentials to scoped permissions

---

.github/dependabot.yml

Dependabot is starting to include labels for each ecosystem that is being updated, which is great, but in a repo like syft where we have labels that represent cataloger features/bugs/etc, this is a little confusing. 
PR: https://github.com/anchore/syft/pull/2717
Log: https://github.com/anchore/syft/network/updates/800618339
For the meantime I've deleted the `github_actions` and `github-actions` (duplicate-ish) labels.
From https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
> By default, Dependabot raises all pull requests with the dependencies label. If more than one package manager is defined, Dependabot includes an additional label on each pull request. This indicates which language or ecosystem the …

Dont include labels for dependabot ecosystems

---

syft/pkg/cataloger/javascript/cataloger.go
syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/parse_package_lock_test.go

Extending https://github.com/anchore/syft/pull/2338 to also be able to retrieve remote licenses from package.lock. I only tested v2 package-lock.json.

Adding the ability to retrieve remote licenses from package-lock.json

---

syft/file/cataloger/executable/macho.go
syft/file/cataloger/executable/macho_test.go
syft/file/cataloger/executable/test-fixtures/shared-info/project/Makefile

This PR fixes a panic when scanning binaries without symtab information.
Fixes #2736

fix: panic scanning binaries without symtab

---

syft/pkg/cataloger/internal/cpegenerate/candidate_by_package_type.go

The official NVD-assigned CPE for poco is `pocoproject:poco`
Fixes: https://github.com/anchore/grype/issues/1737

fix: conan poco project cpe

---

syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go
syft/pkg/cataloger/php/parse_pecl_serialized.go

This PR adjusts the regex that the go binary cataloger uses to extract versions when not found in the build flags.

fix: more robust go main version extraction

---

syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/parse_pom_xml_test.go

Previously, if there was more than one layer of variable indirection in the pom property (propert A says it has the same value as property B, property B says it has the same value as property C), then Syft would only dereference one layer. Add a loop to dereference variables until either dereferencing fails, or until the variable is completely dereferenced back to a literal.
Fixes https://github.com/anchore/syft/issues/2776
Manual testing on repro example from that issue:
``` sh
❯ diff <(syft -q dir:spring-boot-empty-project | awk '{print $1 " "  $2 " " $3}') <(/tmp/syft -q dir:spring-boot-empty-project | awk '{print $1 " " $2 " " $3}')
9c9
< spring-boot-starter-actuator ${project.parent.version} java-archive
---
> spring-boot-starter-actuator 3.2.4 java-archive
11,15c11,15
< …
```

Fix: repeatedly dereference pom variables

---

syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/parse_pom_xml_test.go

Previously, Syft would attempt to dereference pom variables, but if it detected a cycle or failed to get back to a non-variable value, it would return the last variable. Instead, return an empty string. Otherwise, certain jars will have versions like "${project.version}" in the SBOM, which is not helpful.
This is a follow up to #2783 and improves the behavior around #2776.

fix: return empty string if dereferncing pom var fails

---

syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
syft/pkg/cataloger/internal/cpegenerate/generate.go

Indexes known CPEs from `pecl.php.net` and `pear.php.net`
This will depend on https://github.com/anchore/syft/pull/2775 which in turn depends on the package-url spec discussion in https://github.com/package-url/purl-spec/pull/300 before we know how to actually make use of it

feat: index known cpes for PHP extensions

---

.github/scripts/labeler.py

The builds were failing on trying to remove a label that is not present in the PR. This PR adds a checks if the label is set on a PR before removing.
But also the error message is wrong (example failed [workflow](https://github.com/anchore/syft/actions/runs/8658807959/job/23743407645#step:3:16)):
```
[RUN] gh pr edit 2769 --remove-label json-schema
Unable to label PR with 'json-schema'
```
This PR also corrects the above error message and makes the error message for adding a label more clear.

Fix removing labels in 'Detect schema changes' job

---

internal/task/package_task_factory.go
syft/pkg/cataloger/common/cpe/create.go
syft/pkg/cataloger/internal/cpegenerate/dictionary/data/cpe-index.json
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate.go
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/generate_test.go
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/expected-cpe-index.json
syft/pkg/cataloger/internal/cpegenerate/dictionary/index-generator/testdata/official-cpe-dictionary_v2.3.xml
syft/pkg/cataloger/internal/cpegenerate/dictionary/types.go
syft/pkg/cataloger/internal/cpegenerate/generate.go
syft/pkg/cataloger/internal/cpegenerate/generate_test.go

It is possible that a given package has multiple known "official" CPEs active in the dictionary at once, so the index should support a slice of CPE strings per package

feat: support multiple known CPEs in index

---

syft/internal/unionreader/union_reader.go
syft/internal/unionreader/union_reader_test.go

Supersedes #2811, at least for now.
Previously, because file.LocationReadCloser embeds a ReadCloser that might be a UnionReader, but doesn't implement the interface itself, the type assertion would fall and Syft would fall back to io.ReadAll to enable seeking on the underlying reader, resulting in a potentially large extra allocation.
Instead, check whether the passed ReadCloser is a
file.LocationReadCloser, and if so, try to use the embedded ReadCloser as a UnionReader.

fix: re-use embedded union reader if possible

---

syft/pkg/cataloger/internal/cpegenerate/candidate_by_package_type.go

This PR adds an appropriate vendor for `dnsmasq` for APK and DPKG.
Partially fixes #2636

fix: add correct vendor for dnsmasq CPE

---

syft/pkg/cataloger/binary/elf_package_cataloger.go
syft/pkg/cataloger/generic/cataloger.go
syft/pkg/cataloger/generic/cataloger_test.go

Previously, the ELF binary package cataloger would leak file handles, and the generic cataloger loop would leak file handles if parsing the file panicked. Instead, ensure both situations `defer close` new file readers as soon as they are made.
The incorrect behavior had been happening for some time, but was probably exposed by #2814 which caused the ELF binary package cataloger to rely more on file handles and less on in-memory buffers.
Fixes #2819 - in my testing, syft 1.3.0 needs about 1500 concurrent file handles to parse `pytorch/pytorch:latest`; after this change, the number is closer to 800.

fix: better clean up of file handles

---

internal/sbomsync/builder.go
syft/create_sbom.go
syft/format/spdxjson/encoder_test.go

Today we show package count on the UI to help the user get a sense of the progress during cataloging:
```
$ syft cgr.dev/chainguard/redis -o json=/tmp/redis.json                           
✔ Loaded image                                                                                                                                                     cgr.dev/chainguard/redis:latest
✔ Parsed image                                                                                                             sha256:b4eb9f8d974e79ce5ea8e8f42d9bd595c5c803f94cb0171148ff7f6586c92ec3
✔ Cataloged contents                                                                                                              e007b0d98c58812eb5244b38b535ea3133ac144f610800c5c903113b293ae6a1
├── ✔ Packages …
```

Fix UI race when showing package count

---

.github/scripts/update-version-file.sh
.github/workflows/release-version-file.yaml
.github/workflows/release.yaml
Taskfile.yaml

It seems that the version file update during release was dropped post v0.94.0, this PR restores this functionality. This is not added in the release job as done in the past, instead a reusable workflow is leveraged in order to allow for running independent of a release or to be able to safely re-run outside of a release incase of failure (bad credentials, bad value, network error, etc).

Restore version file update on release

---

.golangci.yaml
go.mod
go.sum
syft/file/cataloger/executable/cataloger.go
syft/linux/identify_release.go
syft/pkg/cataloger/alpine/parse_apk_db.go
syft/pkg/cataloger/arch/parse_alpm_db.go
syft/pkg/cataloger/binary/classifier.go
syft/pkg/cataloger/debian/package.go
syft/pkg/cataloger/gentoo/parse_portage_contents.go
syft/pkg/cataloger/golang/licenses.go
syft/pkg/cataloger/golang/parse_go_mod.go
syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
syft/pkg/cataloger/javascript/package.go
test/rules/rules.go

See #2826 
Supersedes https://github.com/anchore/syft/pull/2836.
The only hang-up I've seen is that calls to `make lint` can run an old version of the rules unless `./.tool/golangci-lint cache clean` is called first, which could be annoying when PRing future rule changes.

chore: use ruleguard to test for missing defer statements

---

syft/internal/fileresolver/unindexed_directory.go
syft/pkg/cataloger/golang/config.go

Previously, the file resolver was created from incorrect calls (path.Join instead of filepath.Join) which resulted Go license searches always missing on Windows. Use filepath.* functions when initializing the Go config, and when the unindexed file resolver is being created.
See #2615 - this fixes some of the specific problems reported in that issue, but I'm leaving that issue open to track better integration testing of syft and grype on Windows.
TODOs:

fix Windows file paths in local go mod cache

---

README.md

This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org ref: NixOS/foundation#113

README.md: link to official wiki

---

cmd/syft/internal/test/integration/package_binary_elf_relationships_test.go
internal/relationship/binary/binary_dependencies.go
internal/relationship/binary/binary_dependencies_test.go
internal/relationship/binary/shared_library_index_test.go

This PR fixes a subtle behavior when there is an SBOM with binary packages and no ELF packages. Currently the binary packages are being removed since the package comparison is meant to only be considering ELF packages primarily and not all binary packages (which are ELF packages + binary classifier packages).

Fix redundant package deletions when considering ELF packages

---

syft/pkg/cataloger/golang/test-fixtures/glob-paths/src/go.mod

On certain IDE and versions of neovim that develop syft an error can be encountered when running `go list -m -json all`
This is because the IDE or editor tooling tries to run this command for all `go.mod` for a given source tree.
This PR fixes a `bogus` `go.mod` so that it still fulfills the test case, but doesn't break editor tooling:

chore: fix small tooling error for go.mod

---

syft/format/common/spdxhelpers/to_syft_model.go
syft/format/common/spdxhelpers/to_syft_model_test.go

When parsing SPDX SBOMs, translate DEPENDS_ON and DEPENDENCY_OF relationships into a dependency-of relationship in the Syft model.

Capture dependencies when parsing SPDX SBOMs

---

internal/cmptest/common_options.go
internal/cmptest/diff_reporter.go
internal/cmptest/license.go
internal/cmptest/location.go
internal/cmptest/relationship.go
internal/relationship/by_file_ownership.go
internal/relationship/by_file_ownership_test.go
syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
test/rules/rules.go

Related to https://github.com/anchore/grype/pull/1857
This PR adjusts all locations where we are writing references into the `To` and `From` fields of the `artifact.Relationship` type such that no variable references are used in those fields. This allows for consumers to more easily type assert out specific elements without having to also check references for those types.
A new ruleguard linter rule has been introduced to help prevent from this occurring in the future.
While fixing the test for this it became apparent that lifting up `cmp.Diff` options to a common package would be useful, thus the `internal/cmptest` package was created (should only be used in testing).

Use values in relationship To/From fields

---

syft/format/decoders_collection.go
syft/format/decoders_collection_test.go

This fixes a bug where a `DecoderCollection` would inadvertently consume from the input stream it was given while iterating through candidate formats, unless it was passed an `io.ReadSeeker`.
This doesn't seem to currently affect the CLI.

Fix DecoderCollection discarding input from non-seekable Readers

---

README.md

👋 
This PR reduces the length and complexity of the README.md. 
I have removed a lot of additional information and put it in the [wiki](https://github.com/anchore/syft/wiki), linking to those pages from within the README. So, no information has been lost; it's just moved out of the project's front page.
The goal was to make the information here in the README more accessible and less overwhelming. 🙏

chore: Reduce length of readme, moving lengthy content to the wiki

---

syft/pkg/cataloger/golang/parse_go_mod.go
syft/pkg/cataloger/golang/parse_go_mod_test.go
syft/pkg/cataloger/golang/test-fixtures/many-packages

When the goModCataloger processes a Replace directive it currently adds the new package to the resulting package list, but does not remove the old one unless the path is unchanged.
Based on an existing comment in the code, removing the old one seems to be the intended behavior, and results in a more expected end-result, so this does so.

Go Mod Cataloger: Remove Replaced Packages

---

internal/constants.go
schema/json/README.md
schema/json/schema-16.0.12.json
schema/json/schema-latest.json
syft/pkg/cataloger/golang/package.go
syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go
syft/pkg/golang.go

See https://github.com/anchore/grype/issues/1851 for more context.
I was originally going to put this into [`scanFile`](https://github.com/anchore/syft/blob/3023a5a7bc870f70a3dd24213d795516288ca0df/syft/pkg/cataloger/golang/scan_binary.go#L22), but the existing tests made it a little easier to test if I did it in `parse_go_binary.go` instead.
I've also tested this manually, before:
```
$ git checkout main && go install ./cmd/syft && syft ghcr.io/projectcontour/contour | grep stdlib
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
✔ Loaded image …
```

Handle GOEXPERIMENTs in go version

---

syft/pkg/cataloger/lua/parse_rockspec_test.go
syft/pkg/cataloger/lua/rockspec_parser.go
syft/pkg/cataloger/lua/rockspec_parser_test.go
syft/pkg/cataloger/lua/test-fixtures/rockspec/luasyslog-2.0.1-1.rockspec

Base on the Kong image: https://hub.docker.com/_/kong
Before this PR
```
NAME                   VERSION                                  TYPE        
LPeg                   1.0.2-1                                  lua-rocks    
LuaFileSystem          1.8.0-1                                  lua-rocks            
ansicolors             1.0.2-3                                  lua-rocks          
binaryheap             0.4-1                                    lua-rocks             
etlua                  1.3.0-1                                  lua-rocks             
inspect                3.1.3-0                                  lua-rocks             
kong                   3.5.0-0                                  lua-rocks    
kong-lapis             1.14.0.3-1 …
```

Lua: Add support for more advanced syntax

---

syft/pkg/cataloger/redhat/cataloger.go

For long running programs, opening a sql connection without closing it will cause go routine leaks.  Close sql driver after testing sqlite availability.

Close sqlite driver after testing sqlite availability

---

syft/pkg/cataloger/binary/elf_package.go
syft/pkg/cataloger/binary/elf_package_cataloger.go
syft/pkg/cataloger/binary/elf_package_cataloger_test.go
syft/pkg/cataloger/binary/elf_package_test.go

Adds a field for License information into the elf binary package metadata structure, which is set to omit if empty from sbom.

feat: add license field to ELF binary package metadata

---

syft/pkg/cataloger/golang/test-fixtures/image-not-a-module/Dockerfile

This fixes a similar test failure as #2932 due to a drifting golang image version.

Pin golang image version in test fixture

---

syft/pkg/cataloger/wordpress/parse_plugin.go
syft/pkg/cataloger/wordpress/parse_plugin_test.go

It's possible that values being parsed within PHP comments for the wordpress plugin may have whitespace values (e.g. [carriage returns before line endings](https://plugins.trac.wordpress.org/browser/wp-coder/tags/2.5.1/wp-coder.php)). This PR cleans such values before further processing.

Trim whitespace from wordpress values

---

syft/pkg/cataloger/internal/cpegenerate/generate.go
syft/pkg/cataloger/internal/cpegenerate/generate_test.go
syft/pkg/cataloger/internal/cpegenerate/wordpress.go
syft/pkg/cataloger/internal/cpegenerate/wordpress_test.go

Found some examples in the wild where the `Author` field (not just the `AuthorURI` field) is useful when extracting potential vendors during CPE generation (see the code diff for the example). This means that there will generally be more CPEs for all wordpress plugins found, but this seems unavoidable as there is non guidance around populating these fields for wordpress (nor for providing CPEs for this ecosystem in NVD).
Additionally, this encodes `wordpress` as the target software, as several of the CVEs I've found correctly encode this, and wordpress plugins tend to be a bountiful source of false positives when searching by CPE.

Consider `Author` field for wordpress plugins when generating CPEs

---

cmd/syft/internal/options/cache.go
cmd/syft/internal/options/cache_test.go
internal/cache/cache.go
internal/cache/cache_test.go
internal/cache/memory.go

This PR makes the caching behavior a bit more logical and explicit for different values:
* TTL of <= 0 disable caching entirely
* Dir of empty string (`''`) results in an in-memory only cache

fix: make caching options more explicit

---

.github/actions/bootstrap/action.yaml
.github/dependabot.yml

Allows dependabot to also keep the boostrap action updated

chore: enable dependabot to keep boostrap action updated

---

schema/cyclonedx/README.md
schema/cyclonedx/cyclonedx.json
schema/cyclonedx/cyclonedx.xsd
schema/cyclonedx/spdx.xsd
syft/format/cyclonedxjson/test-fixtures/identify/1.6.json
syft/format/cyclonedxjson/test-fixtures/identify/micronaut-1.6.json
syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
syft/format/cyclonedxjson/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
syft/format/cyclonedxxml/test-fixtures/identify/1.6.xml
syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxDirectoryEncoder.golden
syft/format/cyclonedxxml/test-fixtures/snapshot/TestCycloneDxImageEncoder.golden
syft/format/internal/cyclonedxutil/encoder.go
syft/format/internal/cyclonedxutil/versions.go

- Resolves #2974
I had quite the time figuring out what folks were doing for the test-fixtures involved with expanding the supported spec range. In the end I determined it's a copy/paste w/ an updated spec version and a new unique serial number (I was doing some really silly things like compiling a syft snapshot with the default set to 1.6 in order to emit a fixture file). 
There doesn't appear to be any documentation re: supported versions (outside out what is probably generated via the encoder/decoder interface itself). There are a few string mentions of spec versions, but these are input data for tests and not related to the actual supported versions ([e.g.]( https://github.com/anchore/syft/blob/e0e1c4ba0a5ec546692428efce4a3bb9b8bc250d/cmd/syft/internal/options/writer_test.go#L270)) …

Add 1.6 to supported cyclonedx spec versions.

---

syft/pkg/cataloger/binary/test-fixtures/config.yaml
syft/pkg/cataloger/swift/parse_package_resolved.go
syft/pkg/cataloger/swift/parse_package_resolved_test.go
syft/pkg/cataloger/swift/test-fixtures/PackageV3.resolved

Add version 3 support for swift package manager of the resolved files, add test coverage for v3 support as well.
This is a fix for : https://github.com/anchore/syft/issues/2759

Add version 3 support for swift package manager of the resolved files

---

cmd/syft/internal/test/integration/mariner_distroless_test.go
internal/relationship/exclude_binaries_by_file_ownership_overlap.go
internal/relationship/exclude_binaries_by_file_ownership_overlap_test.go
syft/pkg/cataloger/binary/elf_package.go
syft/pkg/cataloger/binary/elf_package_cataloger_test.go

This is a follow up from #2939 and #2890 , fixing package type for packages discovered from ELF notes. Today all ELF packages are shown as binary packages, and though thats technically true, we should be honoring the package type that the ELF package notes list. This is also more useful downstream in Grype to match vulnerabilities.
This PR updates the behavior of when OS packages should override binary packages, specifically when there is a `.Metadata` that indicates that the package originated from a binary package. This allows us to deduplicate packages when we can, but allow for the binary package to remain in some cases.

Infer the package type from ELF package notes

---

syft/format/internal/spdxutil/helpers/download_location.go
syft/format/internal/spdxutil/helpers/download_location_test.go

Php Composer (via `composer.lock` or `installed.json`) have `NOASSERTION` for `downloadLocation` even though the data is captured. This provides the mapping for those packages

Map the downloadLocation field for PHP Composer packages

---

syft/cpe/by_source_then_specificity_test.go
syft/pkg/cataloger/internal/cpegenerate/generate.go
syft/pkg/collection.go

This is not yet fully deterministic but is a branch that attempts to fix #2967 
```
FROM alpine:latest
RUN apk update
RUN apk add jenkins
```
Build the above image and run syft using this branch
```
for i in (seq 1 20); ~/go/bin/syft -o json 2967:test | jq . > test_sbom/test_$i.json; end
```
Then you can use something like the following to show the sha for each sbom
```
#!/opt/homebrew/bin/fish
cd test_sbom
for file in *
if test -f $file  # Check if the item is a regular file
set sha (sha256sum $file)
echo "$sha\t$file"
end
end
```
On main this produces about 7/8 unique sha for 20 sbom generated against the same image.
On this branch there are only 2 unique sha for the same test.
This is currently WIP to determine what the final non determinism that is causing the two different sha.
The …

fix: stabilize cpe sorting during collection sort

---

syft/pkg/cataloger/binary/elf_package_cataloger_test.go
syft/pkg/cataloger/binary/test-fixtures/image-fedora-64bit/Dockerfile

This PR just pins the fedora:41 image used for an ELF binary test

chore: pin fedora image for elf binary test

---

syft/pkg/cataloger/golang/stdlib_package.go
syft/pkg/cataloger/golang/stdlib_package_test.go

Previously, if a Go binary was cataloged with build info indicating that the go compiler version used was "deve", syft would panic on a nil pointer dereference. Instead, skip creating a Go stdlib reference and relationship for such a package.
Fixes #3037

fix: stop panicking on "devel" version go stdlib

---

README.md

These docs are full of great information so make them easily accessible
from the README so they aren't overlooked.
Signed-off-by: Bradley Jones <bradley.jones@anchore.com>

docs: link to contrib/dev docs in readme

---

syft/pkg/cataloger/internal/cpegenerate/generate_test.go
syft/pkg/cataloger/internal/cpegenerate/java.go
syft/pkg/cataloger/internal/cpegenerate/java_test.go

This PR adds Maven `groupId` as an explicit vendor to include when creating CPEs.
Fixes #3042

fix: include CPEs with Maven groupId as vendor

---

syft/pkg/cataloger/redhat/parse_rpm_archive.go

This PR adds debug logging for errors when reading fields in RPM packages.
Related to: #3049

chore: add debug logging for errors reading RPM files

---

cmd/syft/internal/test/integration/catalog_packages_cases_test.go
syft/pkg/cataloger/python/cataloger_test.go
syft/pkg/cataloger/python/package.go
syft/pkg/cataloger/python/package_test.go
syft/pkg/cataloger/python/parse_requirements_test.go
syft/pkg/cataloger/python/test-fixtures/requires/requirements.txt

Fixes https://github.com/anchore/syft/issues/3064 
(provided there is agreement to normalize the names, discussion in the issue).
This PR adds a normalization function according to python packaging specification https://packaging.python.org/en/latest/specifications/name-normalization/ to each of the package types. And adds/updates existing tests.
The name and the purl are updated, the "metadata" still preserves the unnormalized name.

python-cataloger: normalize package names

---

syft/pkg/cataloger/python/parse_requirements.go
syft/pkg/cataloger/python/parse_requirements_test.go
syft/pkg/cataloger/python/test-fixtures/requires/requirements.txt

Its perfectly valid for python packages to have dots in their name
https://packaging.python.org/en/latest/specifications/name-normalization/
It seems like https://github.com/anchore/syft/pull/1966 introduced a regex match which did not include the dot. This results in silently skipping packages with dots in their requirements.txt.
This PR accepts the dot and adds a test.
Noticed this whilst doing https://github.com/anchore/syft/pull/3069 (which does the normalization of the name)
(its possible that this bug may exist in the other parsers but did not investigate that)

python requirements.txt cataloger: allow dots in python package names

---

syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

This prevents matching a version that is targeting a different module the the main one.

Only match ldflag version if it matches the main module or targets main.version

---

syft/pkg/cataloger/python/parse_requirements_test.go

Fixes the normalization in the test case introduced in https://github.com/anchore/syft/pull/3070

python-cataloger: fix normalization test

---

syft/pkg/cataloger/binary/classifier_cataloger_test.go
syft/pkg/cataloger/binary/classifiers.go
syft/pkg/cataloger/binary/test-fixtures/config.yaml

This PR updates a binary cataloger for traefik
Fixes #3038
```
$ go run cmd/syft/main.go -q library/traefik:3.0 --platform linux/arm/v6 | grep traefik
github.com/traefik/grpc-web                                                           v0.16.0                                go-module
github.com/traefik/paerser                                                            v0.2.0                                 go-module
github.com/traefik/traefik/v3                                                         v0.0.0-20240702134203-d42e75bb2eab     go-module
github.com/traefik/yaegi                                                              v0.16.1                                go-module
traefik                                                                               3.0.4 …
```

update traefik classifier for linux/arm/v6, linux/riscv64

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go

**Improving Accuracy of Package Name Retrieval in Java Archives**
This section outlines enhancements to accurately retrieve the main package artifact names and their corresponding SHA1 values. It focuses on resolving issues where incorrect package names were being retrieved, especially for JAR files with multiple internal JARs. The improvements include:
- Correctly retrieving the main package name when the main POM file is present.
- Addressing issues with incorrect package names for specific JAR files, such as those containing multiple JARs.
- Ensuring accurate results by checking prefixes and suffixes, with a fallback mechanism if no exact matches are found.

Ensure accurate java main artifact name retrieval for multi-JARs and refine fallback approach

---

.binny.yaml
syft/format/internal/spdxutil/helpers/originator_supplier.go
syft/format/internal/spdxutil/helpers/originator_supplier_test.go

**Issue**: 
The PackageSupplier and PackageOriginator are set to type 'Person' for JAR files. For example:
```
PackageName: jackson-annotations
SPDXID: SPDXRef-Package-java-archive-jackson-annotations-55544ed7d2a352e0
PackageVersion: 2.9.10
PackageSupplier: Person: FasterXML
PackageOriginator: Person: FasterXML
```
**Fix**:
Updated to set the type as 'Organization' if vendor is specified in the metadata file of the JAR.
**Result**:
```
PackageName: jackson-annotations
SPDXID: SPDXRef-Package-java-archive-jackson-annotations-55544ed7d2a352e0
PackageVersion: 2.9.10
PackageSupplier: Organization: FasterXML
PackageOriginator: Organization: FasterXML
```

Fix: Updated PackageSupplier to type Organization for JAR files

---

.github/ISSUE_TEMPLATE/config.yml
DEVELOPING.md
README.md

This updates the links to the community Slack to Discourse links.

doc: Updates for the Slack to Discourse migration

---

syft/pkg/cataloger/python/cataloger_test.go
syft/pkg/cataloger/python/test-fixtures/image-multi-site-package/Dockerfile

[readchar 4.2.0](https://pypi.org/project/readchar/) was released Aug 11, and seems to be picked up by the python relationship test when we have a 4.1.0 in site packages; this PR updates the test to account for the new version.

chore: fix failing python relationship test

---

syft/format/common/cyclonedxhelpers/to_format_model.go
syft/format/common/cyclonedxhelpers/to_format_model_test.go

Fixes https://github.com/anchore/grype/issues/1759
This PR ensures that `toBomProperties` returns `nil` for images that do not have labels. When an image does not have any labels, `EncodeProperties` returns a `nil` slice and `toBomProperties` then returns a pointer to that `nil` slice (`&props`), resulting in a non-compliant `null` JSON value.
SBOMs generated by syft do not appear to be affected since this code is not in the call path, so it only affects grype as a caller of this code.

fix: add nil check to cyclonedx toBomProperties

---

syft/pkg/cataloger/binary/classifiers.go
syft/pkg/cataloger/binary/test-fixtures/config.yaml

Detect curl binaries via the regex 'curl/[0-9]+\.[0-9]+\.[0-9]+)'.

Detect curl binaries

---

internal/task/package_task_factory.go

ELF packages do not have the `found-by` field set:
```
❯ syft localhost/elf-test -o json | jq '.artifacts[] | select(.name == "alex")'
{
"id": "a428c7d43ccc1e36",
"name": "alex",
"version": "v1.2.3",
"type": "deb",
"foundBy": "",
...
"purl": "pkg:deb/alex@v1.2.3",
"metadataType": "elf-binary-package-note-json-payload",
"metadata": {
"type": "deb"
}
}
``` 
This PR fixes this behavior to always include the cataloger name.

Set cataloger names within package cataloger task

---

syft/pkg/cataloger/binary/classifiers.go

A follow up to https://github.com/anchore/syft/pull/3166 that sets NVD as the authoritative source for all of the CPEs for existing binary catalogers, and adds in some that were missing and were relying on the syft generation

fix: improve known CPEs and set NVD as source for all current binary classifiers

---

internal/task/executor.go

knowing how much a task took in syft can be useful
in this PR we add a log which specifies the time a task took.
closes - https://github.com/anchore/syft/issues/2723

add log time of task

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/maven_resolver.go
syft/pkg/cataloger/java/maven_resolver_test.go
syft/pkg/cataloger/java/parse_pom_xml.go
syft/pkg/cataloger/java/test-fixtures/pom/local/child-2/pom.xml
syft/pkg/cataloger/java/test-fixtures/pom/local/child-3/pom.xml
syft/pkg/cataloger/java/test-fixtures/pom/local/parent-3/pom.xml

While performing maven resolution, there is a code path when resolving relative path parent poms which was not tracking recursion, leading to a stack overflow error. This PR adjusts calls such that recursion should be tracked with this and other code paths during resolution. This also corrects the issue to properly resolve variables in this case, when a variable is needed to populate parent properties but that variable is defined in a relative path parent pom.
Fixes: #3163

Fix maven recursion issue with parent properties specified in relative path parent pom

---

syft/format/internal/cyclonedxutil/helpers/licenses.go
syft/format/internal/cyclonedxutil/helpers/licenses_test.go

This fixes the issue reported at https://github.com/anchore/syft/issues/3172, where Syft would drop SPDX licenses due a logic error in the decoder.
CycloneDX specifications require `components[].licenses[].license` to be `nil` when `components[].licenses[].expression` (SPDX) is non-`nil`.

Fix improper decoding of SPDX license expressions in the CycloneDX format

---

syft/pkg/cataloger/java/archive_filename.go

These are technically not warn-worthy events since there is no action for a user to take to remove the warning.

Less verbose java logging when non-fatal issues arise

---

.github/scripts/ci-check.sh
Taskfile.yaml

This PR restores the `ci-check.sh` script used during a release instead of inlined commands.

chore: restore ci-check.sh script

---

syft/pkg/cataloger/binary/test-fixtures/capture-snippet.sh

Trim the `SELECTED_RESULT` variable using `xargs` before extracting the offset.
It also checks whether xargs is installed on the system, which should be the case for every normal distribution.

fix: capture-snippet.sh can handle leading whitespaces now (#3249)

---

cmd/syft/internal/options/catalog.go
cmd/syft/internal/options/compliance.go
internal/relationship/index.go
internal/relationship/index_test.go
internal/task/package_task_factory.go
internal/task/package_task_factory_test.go
syft/cataloging/compliance.go
syft/create_sbom_config.go
syft/pkg/cataloger/ocaml/parse_opam_test.go

Adds a new compliance configuration to handle what to do when there is a missing name or version:
```yaml
compliance:
missing-name: 'drop'
missing-version: 'stub'
```
Above are the default values, but the possible values a user can put in are:
- `keep`, add a trace log but the non-compliant package is still added to the SBOM
- `drop`, exclude the package from results, add a debug log
- `stub`, replace the non-compliant empty value with `UNKNOWN`
Open questions:
1. configuration-wise should this land within the `pkgcataloging` package? (instead of the `cataloging` package?)
Closes #2132 
Closes #2652 
Closes #2038 
Closes #2039

Add compliance policy for empty name and version

---

syft/internal/fileresolver/path_skipper.go
syft/internal/fileresolver/path_skipper_test.go

👋🏽 we are seeing issues when upgrading the `syft-sbom-indexer` to the latest version of Syft running on latest GitHub Action Runner images (ubuntu-22.04). Effectively the recently introduced mount path checking prevents the mounted filesystem to be analysed. We see the following log message in the GHA logs when enabling debug logging:
```
DEBUG ignoring path based on mountpoint filesystem type condition=/run fs=tmpfs mountpoint=/proc/latency_stats path=/run/src/core/sbom
```
We tracked this down to https://github.com/anchore/syft/pull/2918. 
This PR adds a new test mimicking the file mounts as seen on the GitHub Action Runner image for ubuntu-22.04 and changes the code to let the requested path `/run/src/core/sbom` not get blocked. 
Please take a look at this change and let us know what …

Improve subpath to mount matching

---

syft/pkg/cataloger/binary/classifier_cataloger_test.go
syft/pkg/cataloger/binary/classifiers.go
syft/pkg/cataloger/binary/test-fixtures/config.yaml

This PR updates a binary cataloger for ruby
Fixes #3238
Fixes #3239
```
$ go run cmd/syft/main.go -q ruby:3.4-rc | grep 'ruby '
ruby                          3.4.0preview1                   binary
$ go run cmd/syft/main.go -q ruby:3.3.0-rc1 | grep 'ruby '
ruby                          3.3.0rc1                        binary
$ go run cmd/syft/main.go -q rubylang/ruby:master-jammy | grep 'ruby '
ruby                 3.4.0dev                                 binary
```

update ruby classifier

---

internal/licenses/parser.go

The built-in scanner is never cleaned, so it leaks memory

fix: don't use licensecheck's builtin scanner

---

syft/pkg/cataloger/javascript/parse_package_json.go
syft/pkg/cataloger/javascript/parse_package_json_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-author-non-standard.json

Several npm packages, including those within the AWS CDK ecosystem, use non-standard fields within their `package.json` files (e.g., `"organization": true`). This caused parsing errors and excluded these packages from reports.
This fix modifies the JavaScript package cataloger to correctly handle these non-standard fields, ensuring accurate parsing and inclusion of all packages in the report.
`aws-cdk/package.json`:
```
...
"author": {
"name": "Amazon Web Services",
"url": "https://aws.amazon.com",
"organization": true
},
...
```
Scan example before fix:
```
syft scan XXX
✔ Parsed image sha256:XXX
✔ Cataloged contents XXX
├── ✔ Packages                        [1,519 packages]
├── ✔ File digests                    [32,435 files]
├── ✔ File metadata                   [32,435 locations]
└── …
```

Fix: Parse package.json with non-standard fields in 'author' section

---

README.md

Hello friends.
This follows the same pattern as the other badges at the top of the readme. It adds the mastodon link to the Syft account. 
This also means that the link back here from the Mastodon account's profile page will show as 'Validated' once it lands, which gives the account more authenticity.
- Fixes #
None of these apply, I think.

[chore] Add mastodon link to README.md

---

cmd/syft/internal/options/output_file.go

It's not clear to users that they shoudl use --output FORMAT=PATH instead of --file. Directly suggest the FORMAT=PATH syntax.
Just a docs improvement, made after [this very reasonable question](https://anchorecommunity.discourse.group/t/how-to-specify-file-name-if-flag-is-depreciated/169?u=willmurphy)
``` sh
❯ go run ./cmd/syft -o json --file /tmp/syft.json busybox:latest
Flag --file has been deprecated, use: --output FORMAT=PATH
```

docs: clearer deprecation message for --file

---

RELEASE.md

Adds a short description of what makes up a syft release, also drops the background section (this is a procedure not a philosophy document)

Update the release docs

---

syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

Enhances the go cataloger semver extraction logic to include getting the release version of traefik.  This is based off of the regex pattern that already existed in the [traefik binary classifier](https://github.com/anchore/syft/blob/8095f7b8c14d2b2abf08c9516c7617c08e9fc319/syft/pkg/cataloger/binary/classifiers.go#L278).
The advantage to raising up the release version in the go cataloger rather than just in the binary classifier is that it means the vulnerability matching can take advantage of the GitHub security advisory data for traefik rather than just the NVD CVE entries.  I think this would have prevented https://github.com/anchore/grype/issues/2178 from occurring

fix: improve go binary semver extraction for traefik

---

syft/pkg/cataloger/binary/elf_package.go

https://github.com/anchore/syft/pull/2762 fixed a small bug where creating a CPE would sometimes return a nil error even though it failed. However, this resulted in some needlessly noisy logs. Clean up some of this logging.

fix: stop some log.Warn spam due parsing an empty string as a CPE

---

syft/pkg/cataloger/binary/classifiers.go

With older versions of mariadb the binary name was `mysql`, so this adjusts the binary classifier to additionally search for the expected version pattern in `mysql` binaries.

fix: improve mariadb binary classifer to detect older versions

---

syft/pkg/cataloger/kernel/cataloger_test.go
syft/pkg/cataloger/kernel/package.go

Uses the official cpe `cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*` for the `linux-kernel-cataloger` so that downstream vulnerability matching will function for those building a grype database with operating system type CPEs included

fix: use official CPE for linux kernel

---

go.mod
go.sum
syft/pkg/cataloger/alpine/package_test.go
syft/pkg/cataloger/arch/package_test.go
syft/pkg/cataloger/debian/package_test.go
syft/pkg/cataloger/redhat/package_test.go
syft/pkg/language_test.go

Updates syft to use the latest changes from `anchore/packageurl-go`.

Update to latest packageurl-go

---

syft/pkg/cataloger/debian/cataloger.go
syft/pkg/cataloger/debian/cataloger_test.go
syft/pkg/cataloger/debian/test-fixtures/glob-paths/usr/lib/dpkg/status
syft/pkg/cataloger/debian/test-fixtures/glob-paths/usr/lib/dpkg/status.d/pkg-1.0

This expands the globs handled by the debian cataloger to include `dpkg/status` and `dpkg/status.d` files that are found in directories not located under `var`. This has been observed 'in the wild' in several instances, in which case Syft failed to parse the available package information.
- Fixes #2692

Expanded dpkg cataloger globs to search outside of /var

---

syft/pkg/cataloger/java/internal/maven/resolver.go
syft/pkg/cataloger/java/internal/maven/resolver_test.go
syft/pkg/cataloger/java/internal/maven/test-fixtures/local/circular-1/pom.xml
syft/pkg/cataloger/java/internal/maven/test-fixtures/local/circular-2/pom.xml
syft/pkg/cataloger/java/internal/maven/test-fixtures/maven-repo/my/org/circular/1.2.3/circular-1.2.3.pom

This PR corrects a case where certain malformed pom.xml files could cause an infinite loop.
This was reported [on Discourse](https://anchorecommunity.discourse.group/t/syft-process-getting-hung/197)

fix: malformed pom.xml may cause recursive loop

---

syft/pkg/cataloger/generic/cataloger_test.go

Corrects infinite recursion in test utility.
- Fixes #3379

fix: stack overflow in spyingIoReadCloser

---

cmd/syft/internal/options/catalog.go
cmd/syft/internal/options/javascript.go
cmd/syft/internal/test/integration/node_packages_test.go
syft/pkg/cataloger/javascript/config.go
syft/pkg/cataloger/javascript/parse_package_lock.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/package-lock-2.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/package-lock-3.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-lock/package-lock.json

This updates the Javascript cataloger so that packages that are only present as dev dependencies found in `package-lock.json` files are ignored and not included in the resulting SBOM. This behavior more closely aligns with that of other similar catalogers, such as the Python Pipfile.lock parser.
This change supports all current `package-lock.json` schema versions (`1`, `2`, and `3`) in accordance with the spec found [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json).
- Fixes #2348

Exclude devDependencies from package-lock.json parsing

---

syft/pkg/cataloger/java/graalvm_native_image_cataloger.go
syft/pkg/cataloger/java/graalvm_native_image_cataloger_test.go
syft/pkg/cataloger/java/test-fixtures/graalvm-sbom/micronaut.json

This PR adds support for the "dependencies" and "purl" fields in SBOMs embedded in Native Images. These fields will be included in SBOMs starting from GraalVM for JDK 24.
Other fixes:
- Resolves empty package ID warnings by setting the package ID. For example, warnings like the one below were previously emitted for valid SBOM components.
```
[0000]  WARN found package with empty ID while adding to the collection: Pkg(name="commons-validator" version="1.9.0" type="graalvm-native-image" id="")
```
- Added support for including the component listed under `metadata/component` in "components". 
Note: While such a component ideally belong under `metadata/component`, the Cataloger interface (`[]pkg.Package, []artifact.Relationship, error`) does not allow specifying that.

Add support for dependencies and purl for Native Image SBOMs

---

README.md
cmd/syft/internal/commands/convert.go

Brought back the `Format conversion` documentation. The documentation of this feature was removed in commit 49c458b (May 20th, 2024) and was supposed to appear in the repository's wiki.
- Fixes #3143

Issue #3143 – fixed format conversion docs link

---

internal/task/executor.go
internal/task/package_task_factory.go
internal/unknown/path_error.go
internal/unknown/path_error_test.go
syft/pkg/cataloger/binary/classifier_cataloger.go
syft/pkg/cataloger/binary/classifier_cataloger_test.go
test/cli/test-fixtures/image-unknowns/Dockerfile
test/cli/unknowns_test.go

The latest releases of syft saw a change where `err` was returned by the `executor` causing the main control flow to exit on task failure. This PR reverts this change and instead writes the errors to a multi err value which sets prog warnings in the TUI
- Fixes: NO BUG FILED
Behavior on latest release:
```
✔ Loaded image                                                                                                                                                                                                                        
✔ Parsed image                                                                                                                                                                                 
⠧ Cataloging contents             ━━━━━━━━━━━━━━━━━━━━ …
```

chore: update executor back to default of not bubbling errors to main flow

---

.github/workflows/release.yaml

When generating an SBOM at release time, only target `go.mod`, not entire directory.

chore: build release sbom from go.mod

---

syft/pkg/cataloger/rust/parse_cargo_lock.go
syft/pkg/cataloger/rust/parse_cargo_lock_test.go
syft/pkg/cataloger/rust/test-fixtures/Cargo.lock

Include updating test dependency to have dependencies on multiple versions of the same crate.
Partially implements #572 by adding support for emitting dependency relationships between crates as enumerated in Cargo.lock files.
Fixes #2353.
This is a new feature.

feat: emit dependency relationships found in Cargo.lock

---

syft/format/common/spdxhelpers/to_format_model.go
syft/format/common/spdxhelpers/to_format_model_test.go

The syft format helpers for spdx currently treat `License-Ref-*` as a valid spdx expression. This causes our selection on `l.Value` to be partially incorrect when trying to add licenses to the `hasExtractedLicensingInfos` in the spdx document.
This change updates the spdx helpers so that singular `License-Ref` candidates are added to this section.
- Fixes #3030

3030 license declared spdx correction

---

syft/pkg/license.go
syft/pkg/license_test.go

This PR updates the license constructors to strip unwanted characters from URLs in license metadata and make sure all URLs conform to RFC 3987 IRI-reference.
- Fixes #3122
- Download .jar file [here](https://repo1.maven.org/maven2/eu/bitwalker/UserAgentUtils/1.21/UserAgentUtils-1.21.jar)
- Run the following command using this branch:
`go run cmd/syft/main.go --output cyclonedx-json=file.json --verbose`
The URL now listed for the `UserAgentUtils` should no longer have special characters in it as listed in the issue.

3122 valid license url characters

---

go.mod
go.sum

Bump anchore/clio to pull in anchore/clio#68
Previously, if SYFT_LOG_FILE was not set, and no TTY was present, log.Warn messages were discarded instead of being sent to stderr.
- Fixes #3081

fix: bump clio to pull in logging fix

---

cmd/syft/internal/options/source.go

Please include a summary of the changes along with any relevant motivation and context,
or link to an issue where this is explained.
- Fixes https://github.com/anchore/syft/issues/3428

add set layer limit

---

DEVELOPING.md
Taskfile.yaml

Add task target for updating golden files (output snapshots) used by unit tests.

chore: add and document target for updating unit snapshots

---

syft/format/internal/cyclonedxutil/helpers/licenses.go
syft/format/internal/cyclonedxutil/helpers/licenses_test.go
syft/license/license_test.go

Previously, a bug in the formatter would cause SPDX expressions that were surrounded in redundant parentheses to be dropped instead of normalized.
- Fixes # https://github.com/anchore/syft/issues/3441

fix: stop omitting redundantly parenthesized licenses in CDX formatter

---

.github/pull_request_template.md

Previously, if filling out this template, someone pasted a PR link after "Fixes #", the issue wouldn't automatically close, probably because the extra "#" confused the auto-close regex.

chore: make fixes field in PR template match auto-close regex

---

syft/pkg/cataloger/golang/licenses.go
syft/pkg/cataloger/golang/licenses_test.go
syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_mod.go

This PR corrects an issue where the golang license search returns prematurely when an error occurs attempting to read the local mod directory instead of continuing to search remotely for the license, resulting in no licenses being included when both local mod cache and remote license searching is enabled.
- Fixes #3527

fix: golang remote license search when error reading local mod dir

---

syft/create_sbom_config.go

this PR enables the way to scan only using files cataloger without package cataloger
related to an older request I've submitted 3128 (link below)
- Fixes #3128

disable package scan

---

go.mod
go.sum
syft/format/common/spdxhelpers/to_format_model_test.go
syft/format/github/test-fixtures/snapshot/TestGithubDirectoryEncoder.golden
syft/format/github/test-fixtures/snapshot/TestGithubImageEncoder.golden
syft/format/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
syft/format/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
syft/pkg/cataloger/binary/elf_package_test.go
syft/pkg/cataloger/dart/parse_pubspec_lock_test.go
syft/pkg/cataloger/gentoo/cataloger_test.go
syft/pkg/cataloger/gentoo/purl_test.go
syft/pkg/cataloger/golang/parse_go_binary_test.go
syft/pkg/cataloger/java/cataloger_test.go
syft/pkg/cataloger/java/parse_jvm_release_test.go
syft/pkg/cataloger/python/cataloger_test.go
syft/pkg/cataloger/python/package_test.go
syft/pkg/cataloger/swift/parse_podfile_lock_test.go

This update integrates the purl changes found in: https://github.com/anchore/packageurl-go/pull/23
- Fixes #3577

chore: bump packageurl-go with new parsing rules

---

go.mod
go.sum

dependency update for latest https://github.com/anchore/stereoscope

chore: bump stereoscope to v0.0.13

---

.github/dependabot.yml

Fixes a typo in the dependabot config which was preventing automated updates to the composite bootstrap action definition.

chore(ci): fix composite GitHub action path in dependabot config

---

syft/pkg/cataloger/redhat/package.go

Instead of namespacing them to the specific distro version, such as Leap or Tumbleweed, the namespace value is set to the vendor itself: "opensuse".
This change is similar to that made in https://github.com/anchore/syft/pull/2914.
- Fixes #3534

Fix namespace value for OpenSUSE distros

---

syft/pkg/cataloger/cpp/parse_conanfile.go

Under windows platform, `conanfile.txt` has a line break of `\r\n`, so the parsed version number will have '\r', this problem does not exist under unix platform.
- Fixes

fix: Version parse caused by line breaks on different platforms

---

syft/pkg/cataloger/bitnami/cataloger.go
syft/pkg/cataloger/bitnami/cataloger_test.go
syft/pkg/cataloger/bitnami/test-fixtures/no-rel/opt/bitnami/redis/.spdx-redis.spdx
syft/pkg/cataloger/bitnami/test-fixtures/no-rel/opt/bitnami/redis/bin/redis-server

The bitnami cataloger assigns files under /opt/bitnami/PACKAGE to be owned by PACKAGE unless they are otherwise owned. Previously, this main package was identified only by relationships, leading to an edge case where if there was a bitnami SBOM with a single package in it, there were no relationships, and so there would be no main package to assign the files to, leading to deduplication failures.
Instead, when encountering a bitnami SBOM with exactly one package in it, assume that package is the main package of that SBOM.

fix: find bitnami files even when no relationships

---

cmd/syft/internal/options/catalog.go
cmd/syft/internal/options/dotnet.go
internal/task/package_tasks.go
syft/cataloging/pkgcataloging/config.go
syft/pkg/cataloger/dotnet/cataloger.go
syft/pkg/cataloger/dotnet/cataloger_test.go
syft/pkg/cataloger/dotnet/config.go
syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable.go
syft/pkg/cataloger/dotnet/parse_dotnet_portable_executable_test.go

Introduce a config option for  `dotnet-portable-executable-cataloger` to control whether root certificates should be validated.
Root certificate validation will be disabled by default.
- Fixes #3455

Disable cert validation in `dotnet-portable-executable-cataloger`

---

go.mod
go.sum

This PR updates the packageurl-go to the latest version
Fixes: #3533

chore: update packageurl-go

---

Taskfile.yaml

This PR disables line wrapping of glow output during `make release`. When line wrap is enabled, many of the URLs are split across lines, making it more difficult to copy/paste output or follow the links to clean up the issue labels.

chore: disable line wrapping glow output

---

internal/err_helper.go

When scanning a sif image I see many lines showing `file already closed`
```
[0419] DEBUG unable to close file for location="/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/fused_conv/python/ops/_fused_conv2d_bias_activation_op.so": close /var/folders/c0/4y79v5k56bz8v34chcmvq2k80000gp/T/stereoscope-3851921087/-2735928573/sha256:01819dea9081a6007328ed242e79efa451cdca6573359cbf8d52eb83cdf4815b: file already closed
[0419] DEBUG unable to close file for location="/usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/hadoop/_dataset_ops.so": close /var/folders/c0/4y79v5k56bz8v34chcmvq2k80000gp/T/stereoscope-3851921087/-2735928573/sha256:01819dea9081a6007328ed242e79efa451cdca6573359cbf8d52eb83cdf4815b: file already closed
[0419] DEBUG unable to close file for …
```

Suppress "file already closed" errors

---

syft/pkg/cataloger/java/graalvm_native_image_cataloger.go

This PR adds support for extracting SBOMs embedded in native images where the SBOM symbols are saved in the `.dynsym` section of ELF files. Newer versions of GraalVM Native Image saves the SBOM symbols in the `.dynsym` section while older versions saves them in the `.symtab` section. This PR ensures SBOM extraction works in both cases. 
*No additional tests were added. The new `getSymbols` function is exercised via [TestParseNativeImage that calls fetchPkgs](https://github.com/anchore/syft/blob/e584c9f416028051fbdc80fffda4e624aaed528d/syft/pkg/cataloger/java/graalvm_native_image_cataloger_test.go#L49). This is a negative test testing that an error is thrown when SBOM extraction is attempted on a native image that wasn't created with an embedded SBOM.

Support extracting symbols in .dynsym section for GraalVM Native Images

---

.binny.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/test-fixture-cache-publish.yaml
.golangci.yaml
syft/format/internal/cyclonedxutil/helpers/property_encoder.go

There was a snag where go1.24.1 caused static analysis failures. This PR updates the codebase to pass with go1.24.1.

chore: updates for go 1.24.1

---

internal/cmptest/common_options.go
internal/cmptest/license.go
internal/cmptest/location.go
internal/cmptest/set.go
internal/evidence/constants.go
internal/relationship/by_file_ownership_test.go
syft/file/location_set_test.go
syft/file/locations.go
syft/pkg/cataloger/debian/cataloger_test.go
syft/pkg/cataloger/golang/stdlib_package_test.go
syft/pkg/cataloger/internal/pkgtest/test_generic_parser.go
syft/pkg/cataloger/python/parse_wheel_egg_metadata_test.go
syft/pkg/evidence.go

Today when sorting locations on packages we sort based on the real and access path on these objects. This is almost correct: we should additionally consider first any package annotations that exist (i.e. is this primary evidence or supporting evidence).
This PR adjusts the behavior such that all primary evidence is listed before supporting evidence.
While working on tests for this PR and a soon-to-follow on PR, it made sense to improve some of the `cmptest` options we use around location sets and license sets (which have locations on them and affect comparisons). No functional change was made here.

Location order on packages should consider evidence annotations when sorting

---

syft/pkg/cataloger/dotnet/parse_dotnet_packages_lock.go

This PR updates the `.NET` package parsing logic to set the package ID explicitly. This change ensures consistent package identification and improves downstream processing.
I noticed the issue is the source of some relations missing from the model.
- Added `SetID()` call to `newDotnetPackagesLockPackage`
- Ensured the `Package` object includes an explicit ID assignment

fix: Add set ID to dotnet (lock) packages

---

syft/pkg/cataloger/dart/parse_pubspec_lock.go
syft/pkg/cataloger/dart/parse_pubspec_lock_test.go
syft/pkg/cataloger/dart/test-fixtures/invalid-sdk/pubspec.lock
syft/pkg/cataloger/dart/test-fixtures/missing-sdk/pubspec.lock
syft/pkg/cataloger/dart/test-fixtures/pubspec.lock

Packages that are provided by an SDK, mainly Flutter, will have their version set to 0.0.0 in Dart's pubspec.lock file. Their actual version is linked to that SDK, which is defined either as a version range or a minimum supported version, rather than an explicit, single version.
The pubspec.lock file has a dedicated section to define those SDK version range constraints, which is already stored internally when parsing the file itself. The solution now is to look up such a package's SDK name, retrieve the defined version range / lower version boundary, and set the minimum supported version as the package's new version.
- Fixes #3158

fix: fetch Dart package versions from sdk entries

---

syft/internal/fileresolver/path_skipper.go

PR to fix this issue https://github.com/anchore/syft/issues/3729

Refine containsPath to reduce memory allocation

---

cmd/syft/internal/options/cache.go
cmd/syft/internal/options/cache_test.go
cmd/syft/internal/options/output_file.go
cmd/syft/internal/options/writer.go
cmd/syft/internal/options/writer_test.go
syft/format/template/encoder.go
syft/internal/fileresolver/unindexed_directory.go
syft/pkg/cataloger/golang/config.go
syft/pkg/cataloger/golang/config_test.go
syft/pkg/cataloger/java/internal/maven/config.go
syft/pkg/cataloger/java/internal/maven/config_test.go
syft/source/directorysource/directory_source_provider.go
syft/source/filesource/file_source_provider.go

This PR just has changes from `make lint-fix` to avoid conflicts due to formatting in other PRs.

chore: reformat imports

---

syft/format/syftjson/model/source.go
syft/format/syftjson/model/source_test.go

When decoding an SBOM document that does not have a source or primary purpose package there we should still allow for the decoding to continue without error; today we get this:
```
[0000] ERROR failed to catalog: unable to decode sbom: unable to decode syft-json document: unable to find source metadata type=""
```
With this fix the decoding would be allowed to continue.

Empty source during decoding an SBOM document should not be fatal

---

syft/pkg/cataloger/cpp/parse_conanlock.go

This PR fixes incorrect variable naming in the `parseConanLock` function.
- Renamed the result of `handleConanLockV2` from `v1Pkgs` to `v2Pkgs`
- Renamed the result of `handleConanLockV1` from `v2Pkgs` to `v1Pkgs`
These changes improve the clarity of the code and prevent confusion between Conan lock version 1 and version 2 parsing logic.
- Fixes

Fix: Correct variable names for Conan lock parsing version handling

---

cmd/syft/internal/commands/cataloger_list.go
cmd/syft/internal/commands/cataloger_list_test.go
cmd/syft/internal/options/catalog.go
cmd/syft/internal/options/catalog_test.go

This PR fixes [an issue that was raised on Discourse](https://anchorecommunity.discourse.group/t/package-detect-binary-not-detect/299/5?u=kzantow) where `cataloger list --override-default-catalogers "go-module-binary-cataloger,go-module-file-cataloger"` would cause an error:
```
[0000] ERROR unable to generate cataloger list report: unable to select catalogers: no cataloger tasks respond to the following selections: go-module-binary-cataloger,go-module-file-cataloger
```
With this change:
```
$ go run ./cmd/syft cataloger list --override-default-catalogers "go-module-binary-cataloger,go-module-file-cataloger"                          
[0000]  WARN adding 'file' tag to the default cataloger selection, to override add '-file' to the cataloger selection request
Default selections: 3
• …
```

fix: comma separated selectors in cataloger list command

---

syft/pkg/cataloger/dotnet/cataloger_test.go
syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
syft/pkg/cataloger/dotnet/deps_json.go
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/.gitignore
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/Dockerfile
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/Program.cs
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/helloworld.csproj

Today the PE cataloger considers the `runtime`, `resources`, and `native` target types within a deps.json file, however, the `compile` type is not considered:
>  If a given dependency is only listed for compilation, then its runtime, resources and native properties is omitted. Similarly if the dependency is only listed for runtime, then its compile property is omitted.
Per the [.NET CLI documentation](https://github.com/dotnet/cli/blob/v3.1.426/Documentation/specs/runtime-configuration-file.md).
This mirrors the same logic applied to the runtime and resources type to the compile type, allowing us to pair up deps.json entries that look like this with the DLLs they reference:
```json
... 
"DotNetNuke.Core/9.9.1": {
"dependencies": {
"DotNetNuke.DependencyInjection": "9.9.1"
},
"compile": { …
```

PE cataloger should consider compile target paths from deps.json

---

cmd/syft/internal/options/catalog.go
cmd/syft/internal/options/dotnet.go
internal/licenses/context_test.go
syft/pkg/cataloger/dotnet/cataloger_test.go
syft/pkg/cataloger/dotnet/config.go
syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
syft/pkg/cataloger/dotnet/deps_json.go
syft/pkg/cataloger/dotnet/package.go
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/Dockerfile
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/Program.cs
syft/pkg/cataloger/dotnet/test-fixtures/image-net8-compile-target/src/helloworld.csproj

This augments the .NET cataloger to include packages that themselves do not claim any DLLs but have dependencies that do have DLLs, which is a common convention for larger nuget package groups (for example [Humanizer](https://www.nuget.org/packages/humanizer/) and [Umbraco.Cms](https://www.nuget.org/packages/Umbraco.Cms/15.4.0-rc2)). This logic now applies to both the DLL claims configuration option as well as DLL existence configuration option. A new configurable has been added to control this behavior:
```
dotnet:
propagate-dll-claims-to-parents: true
```
- https://github.com/anchore/syft/pull/3821

Consider DLL claims for dependencies of .NET packages from deps.json

---

syft/source/filesource/file_source.go
syft/source/filesource/file_source_test.go

Currently when an archive file is scanned with a file source, the archive is extracted before scanning
This is different from the default behavior when an archive file is encountered via directory source, in that case archives are only extracted when deemed necessary by catalogers (ie the java archive cataloguer)
As a Syft library user, when scanning with file source I would like the option to skip extracting archives and instead allow cataloguers decide whether to extract them. 
I've added `SkipExtractArchive` to the filesource Config here, and by default it will be `false` so all existing users will be unaffected.

(feat): support skipping archive extraction with file source

---

internal/relationship/by_file_ownership.go
internal/relationship/by_file_ownership_test.go
internal/task/relationship_tasks.go

Today we add relationships between packages that overlap in file ownership, say when the python cataloger finds a package at path `X` and the debian DB cataloger also finds the same package at the same file path `X` --in this case we leave both packages and add a `file-ownership-by-overlap` relationship between them. In the case where the same path conflict occurs and this is between a binary file and a debian package then we remove the binary package altogether.
The problem is that package ownership locations are unresolved strings (copied from the RPM DB or the Dpkg DB, etc) and the package locations are resolved real paths. This can cause issues int he case of https://github.com/anchore/grype/issues/2527 where the debian package writes through the `/bin` symlink to the realpath of …

Resolve owned file paths when searching for overlaps

---

syft/format/internal/spdxutil/helpers/license.go
syft/format/internal/spdxutil/helpers/license_test.go
syft/format/internal/spdxutil/helpers/spdxid.go

This PR takes the recent full text license work and updates how we're interpreting the `value` field when converting to spdx. Given that we no longer worry about `fullText` being included in this field, `value` is now treated like Expressions when calculating the ID for SPDX licenses in the format helpers.
This means longer `value` that exceeded 64 characters in length do not lose information when being set to the SPDX license ID. We previously because `value` was a dump for both full text and anything NOT valid spdx expressions.
- Fixes #3780

Do not use hashes for SPDX license names/expressions

---

syft/format/internal/spdxutil/helpers/license.go
syft/format/internal/spdxutil/helpers/license_test.go
syft/format/spdxjson/test-fixtures/snapshot/TestSPDXJSONDirectoryEncoder.golden
syft/format/spdxjson/test-fixtures/snapshot/TestSPDXJSONImageEncoder.golden
syft/format/spdxjson/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXRelationshipOrder.golden
syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueDirectoryEncoder.golden
syft/format/spdxtagvalue/test-fixtures/snapshot/TestSPDXTagValueImageEncoder.golden
syft/format/syftjson/test-fixtures/snapshot/TestDirectoryEncoder.golden
syft/format/syftjson/test-fixtures/snapshot/TestEncodeFullJSONDocument.golden
syft/format/syftjson/test-fixtures/snapshot/TestImageEncoder.golden
syft/format/syftjson/to_format_model.go
syft/pkg/license.go
syft/pkg/license_set_test.go
syft/pkg/license_test.go

Before we do a release of syft we want to make sure the license fields are not duplicated. This removes `fullText` which was added https://github.com/anchore/syft/pull/3450. It routes the changes of #3450 through `contents` which was added previously here:  https://github.com/anchore/syft/pull/3366
Note to Reviewers: We previously included a struct tag for the contents field that ignored it as part of our `LicenseSet` identification process. This tag has been removed. Given that licenses can now be some combination of `UNKNOWN` -> `CONTENTS` where the difference in licenses is the "content" of their `contents` we could not longer continue ignoring this field. The resulting license sets would only allow for a single `UNKNOWN` license.
I have added a test that illustrates this behavior.

fix: use "contents" field and remove "fullText" license field 

---

syft/internal/fileresolver/container_image_all_layers.go
syft/internal/fileresolver/container_image_all_layers_test.go
syft/internal/fileresolver/container_image_deep_squash.go

#3138 added the concept of annotating locations raised up from a `file.Resolver` with `visible=true` or `visible=false` for any location returned so we can discover packages which have been deleted in higher layers or are otherwise hidden. That PR added a new `file.Resolver` to take advantage of this new capability, this PR extends these kinds of annotations to the `all-layers` file resolver (there are no other file resolvers this makes sense to also apply this to).
Here's an example of the changes for a single package in an alpine image where multiple `apk add` commands were performed each in their own `RUN` line in the Dockerfile:
```
$ syft myimage:latest -s all-layers | jq '.artifacts[] | select(.name == "alpine-release").locations'
```
```json
[
{
"path": "/lib/apk/db/installed", …
```

Annotate visible/hidden paths when all-layers scope

---

syft/pkg/cataloger/dotnet/deps_binary_cataloger.go
syft/pkg/cataloger/dotnet/deps_json.go
syft/pkg/cataloger/dotnet/deps_json_test.go

It is possible for multiple targets in a deps.json to be for the same package, something that is not considered today (so the first target wins). In cases where we process the first target we might associate PE binaries with the deps.json package, however, if we process with other target first (which might have fewer PE references) then we will not associate that PE with the package and create a unique package.
This PR merges targets together so that dependencies and DLL paths are preserved, thus, multiple runs of syft should always produce the same results.
- Fixes #3866

Merge multiple targets for the same .NET package

---

syft/pkg/cataloger/golang/cataloger_test.go
syft/pkg/cataloger/golang/package.go
syft/pkg/cataloger/golang/parse_go_binary.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

This changes the behavior of the go binary cataloger to rause up a blank version over `(devel)` as a value, allowing the package compliance policy to enforce values (by default set it to `UNKNOWN`).
- Fixes #3324

Clear `(devel)` version from go main modules

---

Taskfile.yaml
syft/pkg/cataloger/generic/cataloger.go

I'm seeing partial values referenced in the issue traceback and a nil dereference:
```
unexpected fault address 0x0
fatal error: fault
[0001] DEBUG discovered 0 packages cataloger=go-module-binary-cataloger
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x123a0da]
goroutine 85 gp=0xc000cb36c0 m=21 mp=0xc000278008 [running]:
runtime.throw({0x1c6f462?, 0xb0efc6?})
/opt/hostedtoolcache/go/1.24.2/x64/src/runtime/panic.go:1101 +0x48 fp=0xc002f29938 sp=0xc002f29908 pc=0x479ac8
runtime.sigpanic()
/opt/hostedtoolcache/go/1.24.2/x64/src/runtime/signal_unix.go:939 +0x26c fp=0xc002f29998 sp=0xc002f29938 pc=0x47bbec
github.com/anchore/syft/internal/unknown.visitErrors({0x6168732f7273752f, 0x656e746f642f6572}, 0xc002f29d70)
/home/runner/work/syft/syft/internal/unknown/coordinate_error.go …
```

fix: remove race when writing errors in generic cataloger

---

syft/pkg/cataloger/golang/config.go
syft/pkg/cataloger/golang/parse_go_binary_test.go

Today if no version can be found for a go module within a binary (searching buildinfo or ldflags) then a semver regex is applied to the full contents of the binary. This is costly resource-wise and often raises incorrect versions. For this reason this PR makes this behavior opt-in only.
- #3873

Do not search for main module versions within binary contents by default

---

syft/format/cyclonedxxml/encoder_test.go
syft/pkg/cataloger/python/cataloger_test.go
syft/pkg/cataloger/python/test-fixtures/image-multi-site-package/Dockerfile

This stabilizes fixtures so that we can [fix the existing fixture publish job](https://github.com/anchore/syft/actions/workflows/test-fixture-cache-publish.yaml) to keep CI running as fast as possible.

chore: update fixtures based on CI builds

---

syft/create_sbom_config.go
test/cli/license_test.go
test/cli/trait_assertions_test.go

With the latest syft release of v1.24.0 some users were seeing contents of licenses in their default outputs. This change fixes the link between the lost config values so that contents can be dropped in a post processing step. It also updates the CLI test fixture to use an image that covers this case correctly
On branch
```json
"licenses": [
{
"value": "LicenseRef-sha256:9e3a4384b6d8d2358d44103f62bcd948328b3f8a63a1a6baa66abeb43302d581",
"spdxExpression": "",
"type": "concluded",
"urls": [],
"locations": [
{
"path": "/usr/share/doc/libcom-err2/copyright",
"layerID": "sha256:a8c68591d421fc2d4bdda704f67a796edf5ff880c59358d75107eb5261821650",
"accessPath": "/usr/share/doc/libcom-err2/copyright",
"annotations": {
"evidence": "supporting"
}
}
]
}
],
```
Syft v1.24.0
```json
"licenses": [
{ …
```

fix: include default license config for sbom builder

---

test/cli/test-fixtures/image-unknown-licenses/Dockerfile

Remove unused cli license fixture from cli tests

chore: delete unused cli license fixture

---

syft/pkg/cataloger/java/graalvm_native_image_cataloger.go

This PR improves Syft's visibility into native image binaries by surfacing cases where an expected embedded SBOM cannot be extracted. Previously, this failure was only shown in verbose debug logs and was indistinguishable from other non-native binaries. With this change, users will now receive a structured warning under the unknowns section of the SBOM output when a Java Native Image is found but no embedded SBOM could be retrieved.
- Fixes #3731

fix: Make Native Image contains no embedded SBOM Error Discoverable

---

go.mod
go.sum
syft/pkg/cataloger/redhat/parse_rpm_archive.go
syft/pkg/cataloger/redhat/parse_rpm_db.go

This removes the replace directive added to support #3179 -- though it is functional from the perspective of a syft release, anyone using syft via go module will also need to add the replace directive, which was not intended.
The go-rpmdb fork has been updated to use anchore path references and incorporated the upstream match into the default branch of the fork.
This additionally retracts the release for v1.25.0 as this could cause confusion for folks trying to use the release.

chore: remove go-rpmdb replace directive

---

Dockerfile
Dockerfile.debug

An upstream issue with busy box was causing issues where users would see:
```
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
```
This could cause issues in ci pipelines where users needed the debug image of syft for running pre CI commands before the sbom functionality was invoked.
This PR moves us forward to use the rolling tags for `latest` and `debug` images from distroless debian12
Here is a local demonstration of the fix. PR reviewers can pull down the branch and run `make snapshot` to build the docker images and test on their local:
```
[I] (base-image-updates)> docker run -it --rm --entrypoint /busybox/wget be0d5f30581e --no-check-certificate --spider https://www.google.com
Connecting to www.google.com …
```

chore: update dockerfile base images to latest rolling tags

---

syft/format/internal/backfill.go
syft/format/internal/backfill_test.go
syft/format/internal/cyclonedxutil/helpers/component.go
syft/format/internal/cyclonedxutil/helpers/component_test.go
syft/format/purls/decoder_test.go
syft/pkg/cataloger/redhat/parse_rpm_archive.go
syft/pkg/cataloger/redhat/parse_rpm_db.go

With #3853 we began creating `pkg.JavaArchive.PomProperties` metadata fields populated from the purl fields (groupid = namespace, artifactid = name). This is generally OK, however, can cause confusion when looking at only the syft json output for a package when the SBOM was decoded from any format into syft json: it makes it seem that we conclusively found a `pom.properties` file on disk during the analysis even though that's not necessarily true.
Even more confusing, if you take syft json output that does not have `pkg.JavaArchive.PomProperties` populated and you run `syft convert -o json` (the same format) the field is populated.
For this reason this PR makes a small alteration: we don't generate any `pkg.JavaArchive.PomProperties` from purl info.
However, we don't want to drop …

`pkg.JavaArchive.PomProperties` is being populated even though no `pom.properties` file was present for analysis

---

syft/pkg/cataloger/dotnet/deps_json.go
syft/pkg/cataloger/dotnet/deps_json_test.go

This PR fixes an issue where the Dotnet deps cataloger can get into a loop resolving dependencies.
- Fixes: #3919

fix(dotnet-deps-cataloger): avoid repeated dependency resolution

---

syft/pkg/cataloger/terraform/cataloger_test.go
syft/pkg/cataloger/terraform/test-fixtures/two-providers/.terraform.lock.hcl
syft/pkg/terraform.go

In a `.terraform.lock.hcl` within a provider block the `constraints` attribute is not required (=optional). A lock file like this is valid for Terraform:
```hcl
provider "registry.terraform.io/hashicorp/archive" {
version = "2.7.0"
hashes = [
"h1:YkXq4JfcoAW0L4B9ghskZUxYbYAXIPlfSqqVFrAS06U=",
]
}
provider "registry.terraform.io/hashicorp/aws" {
version     = "5.82.2"
constraints = ">= 2.0.0, >= 3.0.0, >= 3.74.0, >= 4.9.0, >= 4.29.0, >= 4.38.0, >= 4.40.0, >= 4.52.0, >= 5.21.0, >= 5.27.0, >= 5.30.0, >= 5.32.0, >= 5.49.0, 5.82.2"
hashes = [
"h1:RuPaHbllUB8a2TGTyc149wJfoh6zhIEjUvFYKR6iP2E=",
]
}
```
However, the current implementation of syft will not discover any providers and silently fail with an error given the above lock file:
```
[0001] TRACE cataloger returned errors …
```

fix(terraform): terraform provider lock entries should not require constraints

---

cmd/syft/cli/cli.go

This small change updates the syft version command to show the value of `internal.JSONSchemaVersion`. 
Syft users have asked for a simple way to access this value without having to generate a scan document.
` go run cmd/syft/main.go -o json version`
```json
{
"application": "syft",
"buildDate": "[not provided]",
"compiler": "gc",
"gitCommit": "[not provided]",
"gitDescription": "[not provided]",
"goVersion": "go1.24.3",
"platform": "darwin/arm64",
"syftSchemaVersion": "16.0.34",
"version": "[not provided]"
}
```
`go run cmd/syft/main.go version`
```
Application:       syft
Version:           [not provided]
BuildDate:         [not provided]
GitCommit:         [not provided]
GitDescription:    [not provided]
Platform:          darwin/arm64
GoVersion:         go1.24.3
Compiler:          gc …
```

feat: add syft schema version to version command

---

.github/workflows/validations.yaml
.goreleaser.yaml
Dockerfile
Dockerfile.debug
Taskfile.yaml

This PR makes the following changes:
- uses `gcr.io/distroless/static-debian12` as the base image
- ensures the built containers are non-root users
In the process of working on this additional docker manifest updates were made:
- `image_templates` section was missing from the `debug` variant
- the top-level images should be the manifests and the tagged images should always be architecture specific (according to best practices)

Harden Container Runtime with Non-Root User

---

syft/pkg/cataloger/internal/cpegenerate/candidate_by_package_type.go

An extension of https://github.com/anchore/syft/pull/3962 , avoiding CPE matches of Rust crates with non-Rust CPEs in order to avoid matching of CVEs in the non-Rust software.

fix: Remove three Rust crate false positive CPE matches

---

syft/pkg/cataloger/python/cataloger_test.go
syft/pkg/cataloger/python/dependency.go

Previously a dependency relationship between two Python packages was not detected if there were no parentheses around the version specifier in the wheel metadata of the parent package. This pull request allows detection of such relationships.
- Fixes #3958

Fix Python package dependency detection

---

syft/format/syftjson/model/document.go
syft/format/syftjson/model/document_test.go
syft/format/syftjson/model/file.go
syft/format/syftjson/model/file_test.go
syft/format/syftjson/to_syft_model.go
syft/format/syftjson/to_syft_model_test.go

Anchore enterprise has supported in the past one more additional `FileMetadataEntry` data shape, however, the syft json decoders do not support this shape. This adjusts the unmarshalers to account for this case.

Allow decoding of anchorectl json files

---

.goreleaser.yaml
Dockerfile.nonroot

This PR reverts a change to use `nonroot` images by default, and provides an alternate `nonroot` set of tagged images. Using `nonroot` causes a number of issues causing users friction such as accessing and modifying the `docker.sock` and mount volumes.

fix: provide separate nonroot image

---

.github/workflows/release.yaml

With https://github.com/anchore/syft/pull/4062 we updated our security around github actions using the zizmor linter to call out common pitfalls and misaligned files.
This PR reverts a small change in #4062 by setting `persist-credentials: true` for the release step of syft.
Here we are still following the outlined practice in the linter documentation:
https://docs.zizmor.sh/audits/#artipacked
> Unless needed for git operations, [actions/checkout](https://github.com/actions/checkout) should be used with persist-credentials: false. If the persisted credential is needed, it should be made explicit with persist-credentials: true.
We are being explicit with this change that we need `persist-crendentials: true` in this case

chore: update release workflow to persist credentials for tag step

---

syft/pkg/cataloger/java/archive_parser.go
syft/pkg/cataloger/java/archive_parser_test.go
syft/pkg/cataloger/java/test-fixtures/jar-metadata/Makefile
syft/pkg/cataloger/java/test-fixtures/jar-metadata/org.multiple-thename/META-INF/MANIFEST.MF
syft/pkg/cataloger/java/test-fixtures/jar-metadata/org.multiple-thename/META-INF/maven/com.multiple/thename/pom.properties
syft/pkg/cataloger/java/test-fixtures/jar-metadata/org.multiple-thename/META-INF/maven/com.multiple/thename/pom.xml
syft/pkg/cataloger/java/test-fixtures/jar-metadata/org.multiple-thename/META-INF/maven/org.multiple/thename/pom.properties
syft/pkg/cataloger/java/test-fixtures/jar-metadata/org.multiple-thename/META-INF/maven/org.multiple/thename/pom.xml

This PR fixes an issue where the Java archive cataloger could select the groupID in a nondeterministic fashion, resulting in different SBOMs on the same source material. Additionally, the logic to select the groupID and artifactID combination for Maven artifacts did not take into account the potential inclusion of groupID in the filename. As noted in the comment, this PR adjusts the behavior to be what I think is more correct when determining which pom the artifact represents: it will now favor POMs where both groupID and artifactID match, followed by exact match of the filename, and so on.
- Fixes #3521

fix: nondeterministic Java archive cataloging and improve groupID

---

syft/pkg/cataloger/binary/classifier_cataloger.go
syft/pkg/cataloger/binary/classifier_cataloger_test.go
syft/pkg/cataloger/binary/classifiers.go
syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/vault/1.19.4/linux-arm64/vault
syft/pkg/cataloger/binary/test-fixtures/classifiers/snippets/vault/1.20.2/linux-amd64/vault
syft/pkg/cataloger/binary/test-fixtures/config.yaml

The Go Binary Cataloger isn't able to parse the version out of the binary shipped in the DockerHub images of hashicorp/vault because the version of the main module isn't set in the binary. Therefore, add a binary classifier cataloger for this binary.

add binary classifier for hashicorp vault

---

syft/pkg/cataloger/javascript/package.go
syft/pkg/cataloger/javascript/parse_package_json.go
syft/pkg/cataloger/javascript/parse_package_json_test.go
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-all-author-fields.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-authors-array.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-authors-objects.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-both-author-and-authors.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-contributors.json
syft/pkg/cataloger/javascript/test-fixtures/pkg-json/package-maintainers.json

This PR adds support for parsing the `authors` field in `package.json` files. Previously, Syft only recognized the singular `author` field, but the npm ecosystem supports both formats. This change ensures that Syft properly parses both formats and combines them when both are present in a `package.json` file.
The implementation:
1. Adds a new `authors []author` type to handle the plural form
2. Implements `UnmarshalJSON` to handle parsing different formats (array of strings or objects)
3. Adds `AuthorsString()` to convert authors array to a properly formatted string
4. Updates `newPackageJSONPackage` to handle both fields appropriately
This change improves the accuracy of npm package metadata parsing in Syft.
- Fixes #2250

Add support for authors in package.json. Fixes #2250

---

examples/create_custom_sbom/main.go
examples/create_simple_sbom/main.go
examples/select_catalogers/main.go
examples/source_from_registry/main.go
syft/pkg/cataloger/generic/cataloger.go
syft/pkg/cataloger/redhat/cataloger.go
syft/pkg/cataloger/redhat/sqlitetest/no_sqlite_driver_test.go

This PR causes a syft scan to return an error when there is no SQLite driver registered. This may occur when using Syft as a library and not including the import `_ "modernc.org/sqlite"`.
- Fixes #3234

chore: redhat cataloger error when sqlite not regsitered
